window.APP_DATA={
  "title": "《99%的人輸在不會表達》",
  "version": "V3-吉卜力Q版女聲",
  "voice": "Chinese (Taiwan) - HsiaoYu",
  "voiceDurationSeconds": 713.112,
  "spokenDurationSeconds": 713.056,
  "sourceSentenceCount": 123,
  "visualSegmentCount": 244,
  "segments": [
    {
      "id": "\\#001-1",
      "start": 0.1,
      "end": 2.819,
      "duration": 2.719,
      "narration": "你身邊有沒有一種人，明明工作能力極強？",
      "subtitle": "你身邊有沒有一種人，明明工作能力極強？",
      "section": "0. 片頭與提問",
      "sourceShot": "#001",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#001-2",
      "start": 2.819,
      "end": 5.537,
      "duration": 2.718,
      "narration": "你身邊有沒有一種人，明明工作能力極強？",
      "subtitle": "你身邊有沒有一種人，明明工作能力極強？",
      "section": "0. 片頭與提問",
      "sourceShot": "#001",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#002-1",
      "start": 5.537,
      "end": 8.206,
      "duration": 2.669,
      "narration": "但每次開會輪到他發言，他就無比緊張？",
      "subtitle": "但每次開會輪到他發言，他就無比緊張？",
      "section": "0. 片頭與提問",
      "sourceShot": "#002",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#002-2",
      "start": 8.206,
      "end": 10.875,
      "duration": 2.669,
      "narration": "但每次開會輪到他發言，他就無比緊張？",
      "subtitle": "但每次開會輪到他發言，他就無比緊張？",
      "section": "0. 片頭與提問",
      "sourceShot": "#002",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#003-1",
      "start": 10.875,
      "end": 13.812,
      "duration": 2.937,
      "narration": "最後他發言冷場連連，風頭全被別人搶走？",
      "subtitle": "最後他發言冷場連連，風頭全被別人搶走？",
      "section": "0. 片頭與提問",
      "sourceShot": "#003",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#003-2",
      "start": 13.812,
      "end": 16.75,
      "duration": 2.938,
      "narration": "最後他發言冷場連連，風頭全被別人搶走？",
      "subtitle": "最後他發言冷場連連，風頭全被別人搶走？",
      "section": "0. 片頭與提問",
      "sourceShot": "#003",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#004-1",
      "start": 16.75,
      "end": 19.306,
      "duration": 2.556,
      "narration": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "subtitle": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "section": "0. 片頭與提問",
      "sourceShot": "#004",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#004-2",
      "start": 19.306,
      "end": 21.862,
      "duration": 2.556,
      "narration": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "subtitle": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "section": "0. 片頭與提問",
      "sourceShot": "#004",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#005-1",
      "start": 21.862,
      "end": 24.524,
      "duration": 2.662,
      "narration": "對我們而言，你的心裡是不是也曾感到委屈？",
      "subtitle": "對我們而言，你的心裡是不是也曾感到委屈？",
      "section": "0. 片頭與提問",
      "sourceShot": "#005",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#005-2",
      "start": 24.524,
      "end": 27.187,
      "duration": 2.663,
      "narration": "對我們而言，你的心裡是不是也曾感到委屈？",
      "subtitle": "對我們而言，你的心裡是不是也曾感到委屈？",
      "section": "0. 片頭與提問",
      "sourceShot": "#005",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#006-1",
      "start": 27.187,
      "end": 32.15,
      "duration": 4.963,
      "narration": "或者，你是不是也常對外人客客氣氣？",
      "subtitle": "或者，你是不是也常對外人客客氣氣？",
      "section": "0. 片頭與提問",
      "sourceShot": "#006",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#007-1",
      "start": 32.15,
      "end": 34.712,
      "duration": 2.562,
      "narration": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "subtitle": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "section": "0. 片頭與提問",
      "sourceShot": "#007",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#007-2",
      "start": 34.712,
      "end": 37.275,
      "duration": 2.563,
      "narration": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "subtitle": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "section": "0. 片頭與提問",
      "sourceShot": "#007",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#008-1",
      "start": 37.275,
      "end": 39.868,
      "duration": 2.593,
      "narration": "我們都以為好好說話是一件無關緊要的事。",
      "subtitle": "我們都以為好好說話是一件無關緊要的事。",
      "section": "0. 片頭與提問",
      "sourceShot": "#008",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#008-2",
      "start": 39.868,
      "end": 42.462,
      "duration": 2.594,
      "narration": "我們都以為好好說話是一件無關緊要的事。",
      "subtitle": "我們都以為好好說話是一件無關緊要的事。",
      "section": "0. 片頭與提問",
      "sourceShot": "#008",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#009-1",
      "start": 42.462,
      "end": 45.249,
      "duration": 2.787,
      "narration": "卻不知道九九％的人，都輸在不會表達上。",
      "subtitle": "卻不知道九九％的人，都輸在不會表達上。",
      "section": "0. 片頭與提問",
      "sourceShot": "#009",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#009-2",
      "start": 45.249,
      "end": 48.037,
      "duration": 2.788,
      "narration": "卻不知道九九％的人，都輸在不會表達上。",
      "subtitle": "卻不知道九九％的人，都輸在不會表達上。",
      "section": "0. 片頭與提問",
      "sourceShot": "#009",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#010-1",
      "start": 48.037,
      "end": 50.687,
      "duration": 2.65,
      "narration": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "subtitle": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "section": "0. 片頭與提問",
      "sourceShot": "#010",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#010-2",
      "start": 50.687,
      "end": 53.337,
      "duration": 2.65,
      "narration": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "subtitle": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "section": "0. 片頭與提問",
      "sourceShot": "#010",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#011-1",
      "start": 53.337,
      "end": 56.012,
      "duration": 2.675,
      "narration": "這本書將帶我們看懂生活中所有的溝通死角。",
      "subtitle": "這本書將帶我們看懂生活中所有的溝通死角。",
      "section": "0. 片頭與提問",
      "sourceShot": "#011",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#011-2",
      "start": 56.012,
      "end": 58.687,
      "duration": 2.675,
      "narration": "這本書將帶我們看懂生活中所有的溝通死角。",
      "subtitle": "這本書將帶我們看懂生活中所有的溝通死角。",
      "section": "0. 片頭與提問",
      "sourceShot": "#011",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#012-1",
      "start": 58.687,
      "end": 61.624,
      "duration": 2.937,
      "narration": "無論是職場應對、陌生破冰、還是家庭相處。",
      "subtitle": "無論是職場應對、陌生破冰、還是家庭相處。",
      "section": "0. 片頭與提問",
      "sourceShot": "#012",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#012-2",
      "start": 61.624,
      "end": 64.562,
      "duration": 2.938,
      "narration": "無論是職場應對、陌生破冰、還是家庭相處。",
      "subtitle": "無論是職場應對、陌生破冰、還是家庭相處。",
      "section": "0. 片頭與提問",
      "sourceShot": "#012",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#013-1",
      "start": 64.562,
      "end": 67.124,
      "duration": 2.562,
      "narration": "話說對了，人生中所有的麻煩，就沒了。",
      "subtitle": "話說對了，人生中所有的麻煩，就沒了。",
      "section": "0. 片頭與提問",
      "sourceShot": "#013",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#013-2",
      "start": 67.124,
      "end": 69.687,
      "duration": 2.563,
      "narration": "話說對了，人生中所有的麻煩，就沒了。",
      "subtitle": "話說對了，人生中所有的麻煩，就沒了。",
      "section": "0. 片頭與提問",
      "sourceShot": "#013",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#014-1",
      "start": 69.687,
      "end": 72.762,
      "duration": 3.075,
      "narration": "《99%的人輸在不會表達》是一本溝通聖經。",
      "subtitle": "《99%的人輸在不會表達》是一本溝通聖經。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#014",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#014-2",
      "start": 72.762,
      "end": 75.837,
      "duration": 3.075,
      "narration": "《99%的人輸在不會表達》是一本溝通聖經。",
      "subtitle": "《99%的人輸在不會表達》是一本溝通聖經。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#014",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#015-1",
      "start": 75.837,
      "end": 78.862,
      "duration": 3.025,
      "narration": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "subtitle": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#015",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#015-2",
      "start": 78.862,
      "end": 81.887,
      "duration": 3.025,
      "narration": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "subtitle": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#015",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#016-1",
      "start": 81.887,
      "end": 84.856,
      "duration": 2.969,
      "narration": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "subtitle": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#016",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#016-2",
      "start": 84.856,
      "end": 87.825,
      "duration": 2.969,
      "narration": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "subtitle": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#016",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#017-1",
      "start": 87.825,
      "end": 90.312,
      "duration": 2.487,
      "narration": "李勁在書中，提出了一個非常震撼的觀點。",
      "subtitle": "李勁在書中，提出了一個非常震撼的觀點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#017",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#017-2",
      "start": 90.312,
      "end": 92.8,
      "duration": 2.488,
      "narration": "李勁在書中，提出了一個非常震撼的觀點。",
      "subtitle": "李勁在書中，提出了一個非常震撼的觀點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#017",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#018-1",
      "start": 92.8,
      "end": 95.743,
      "duration": 2.943,
      "narration": "一個人的成功，只有百分之十五取決於專業技術。",
      "subtitle": "一個人的成功，只有百分之十五取決於專業技術。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#018",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#018-2",
      "start": 95.743,
      "end": 98.687,
      "duration": 2.944,
      "narration": "一個人的成功，只有百分之十五取決於專業技術。",
      "subtitle": "一個人的成功，只有百分之十五取決於專業技術。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#018",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#019-1",
      "start": 98.687,
      "end": 101.45,
      "duration": 2.763,
      "narration": "而其餘的百分之八十五，全取決於有效溝通。",
      "subtitle": "而其餘的百分之八十五，全取決於有效溝通。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#019",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#019-2",
      "start": 101.45,
      "end": 104.212,
      "duration": 2.762,
      "narration": "而其餘的百分之八十五，全取決於有效溝通。",
      "subtitle": "而其餘的百分之八十五，全取決於有效溝通。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#019",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#020-1",
      "start": 104.212,
      "end": 106.881,
      "duration": 2.669,
      "narration": "這本書想解決能力優秀、卻不會表達的痛點。",
      "subtitle": "這本書想解決能力優秀、卻不會表達的痛點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#020",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#020-2",
      "start": 106.881,
      "end": 109.55,
      "duration": 2.669,
      "narration": "這本書想解決能力優秀、卻不會表達的痛點。",
      "subtitle": "這本書想解決能力優秀、卻不會表達的痛點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#020",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#021-1",
      "start": 109.55,
      "end": 112.612,
      "duration": 3.062,
      "narration": "它非常適合職場人士、樂齡族與家庭經營者。",
      "subtitle": "它非常適合職場人士、樂齡族與家庭經營者。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#021",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#021-2",
      "start": 112.612,
      "end": 115.675,
      "duration": 3.063,
      "narration": "它非常適合職場人士、樂齡族與家庭經營者。",
      "subtitle": "它非常適合職場人士、樂齡族與家庭經營者。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#021",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#022-1",
      "start": 115.675,
      "end": 118.368,
      "duration": 2.693,
      "narration": "全書十二個章節，呈現出嚴密的遞進架構。",
      "subtitle": "全書十二個章節，呈現出嚴密的遞進架構。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#022",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#022-2",
      "start": 118.368,
      "end": 121.062,
      "duration": 2.694,
      "narration": "全書十二個章節，呈現出嚴密的遞進架構。",
      "subtitle": "全書十二個章節，呈現出嚴密的遞進架構。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#022",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#023-1",
      "start": 121.062,
      "end": 123.85,
      "duration": 2.788,
      "narration": "今天我將為大家，進行最完整的逐章拆解。",
      "subtitle": "今天我將為大家，進行最完整的逐章拆解。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#023",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#023-2",
      "start": 123.85,
      "end": 126.637,
      "duration": 2.787,
      "narration": "今天我將為大家，進行最完整的逐章拆解。",
      "subtitle": "今天我將為大家，進行最完整的逐章拆解。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#023",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#024-1",
      "start": 126.637,
      "end": 130.337,
      "duration": 3.7,
      "narration": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "subtitle": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#024",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#024-2",
      "start": 130.337,
      "end": 134.037,
      "duration": 3.7,
      "narration": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "subtitle": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#024",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#025-1",
      "start": 134.037,
      "end": 136.95,
      "duration": 2.913,
      "narration": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "subtitle": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#025",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#025-2",
      "start": 136.95,
      "end": 139.862,
      "duration": 2.912,
      "narration": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "subtitle": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#025",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#026-1",
      "start": 139.862,
      "end": 142.581,
      "duration": 2.719,
      "narration": "明明很有才華，卻常因為緊張而不敢開口？",
      "subtitle": "明明很有才華，卻常因為緊張而不敢開口？",
      "section": "2. 第一章至第三章",
      "sourceShot": "#026",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#026-2",
      "start": 142.581,
      "end": 145.3,
      "duration": 2.719,
      "narration": "明明很有才華，卻常因為緊張而不敢開口？",
      "subtitle": "明明很有才華，卻常因為緊張而不敢開口？",
      "section": "2. 第一章至第三章",
      "sourceShot": "#026",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#027-1",
      "start": 145.3,
      "end": 148.3,
      "duration": 3.0,
      "narration": "作者指出，社交緊張大多源自於過強的自尊心。",
      "subtitle": "作者指出，社交緊張大多源自於過強的自尊心。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#027",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#027-2",
      "start": 148.3,
      "end": 151.3,
      "duration": 3.0,
      "narration": "作者指出，社交緊張大多源自於過強的自尊心。",
      "subtitle": "作者指出，社交緊張大多源自於過強的自尊心。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#027",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#028-1",
      "start": 151.3,
      "end": 154.331,
      "duration": 3.031,
      "narration": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "subtitle": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#028",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#028-2",
      "start": 154.331,
      "end": 157.362,
      "duration": 3.031,
      "narration": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "subtitle": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#028",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#029-1",
      "start": 157.362,
      "end": 160.149,
      "duration": 2.787,
      "narration": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "subtitle": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#029",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#029-2",
      "start": 160.149,
      "end": 162.937,
      "duration": 2.788,
      "narration": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "subtitle": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#029",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#030-1",
      "start": 162.937,
      "end": 165.931,
      "duration": 2.994,
      "narration": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "subtitle": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#030",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#030-2",
      "start": 165.931,
      "end": 168.925,
      "duration": 2.994,
      "narration": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "subtitle": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#030",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#031-1",
      "start": 168.925,
      "end": 171.869,
      "duration": 2.944,
      "narration": "我們也可以在開口之前，進行黃金心理暗示法。",
      "subtitle": "我們也可以在開口之前，進行黃金心理暗示法。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#031",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#031-2",
      "start": 171.869,
      "end": 174.812,
      "duration": 2.943,
      "narration": "我們也可以在開口之前，進行黃金心理暗示法。",
      "subtitle": "我們也可以在開口之前，進行黃金心理暗示法。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#031",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#032-1",
      "start": 174.812,
      "end": 178.125,
      "duration": 3.313,
      "narration": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "subtitle": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#032",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#032-2",
      "start": 178.125,
      "end": 181.437,
      "duration": 3.312,
      "narration": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "subtitle": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#032",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#033-1",
      "start": 181.437,
      "end": 184.444,
      "duration": 3.007,
      "narration": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "subtitle": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#033",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#033-2",
      "start": 184.444,
      "end": 187.45,
      "duration": 3.006,
      "narration": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "subtitle": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#033",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#034-1",
      "start": 187.45,
      "end": 190.55,
      "duration": 3.1,
      "narration": "不追求完美表現，每天練習對店員微笑對視吧。",
      "subtitle": "不追求完美表現，每天練習對店員微笑對視吧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#034",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#034-2",
      "start": 190.55,
      "end": 193.65,
      "duration": 3.1,
      "narration": "不追求完美表現，每天練習對店員微笑對視吧。",
      "subtitle": "不追求完美表現，每天練習對店員微笑對視吧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#034",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#035-1",
      "start": 193.65,
      "end": 196.569,
      "duration": 2.919,
      "narration": "第二章，先學會閱人，然後說到對方的心理去。",
      "subtitle": "第二章，先學會閱人，然後說到對方的心理去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#035",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#035-2",
      "start": 196.569,
      "end": 199.487,
      "duration": 2.918,
      "narration": "第二章，先學會閱人，然後說到對方的心理去。",
      "subtitle": "第二章，先學會閱人，然後說到對方的心理去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#035",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#036-1",
      "start": 199.487,
      "end": 202.043,
      "duration": 2.556,
      "narration": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "subtitle": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#036",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#036-2",
      "start": 202.043,
      "end": 204.6,
      "duration": 2.557,
      "narration": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "subtitle": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#036",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#037-1",
      "start": 204.6,
      "end": 207.519,
      "duration": 2.919,
      "narration": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "subtitle": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#037",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#037-2",
      "start": 207.519,
      "end": 210.437,
      "duration": 2.918,
      "narration": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "subtitle": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#037",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#038-1",
      "start": 210.437,
      "end": 213.306,
      "duration": 2.869,
      "narration": "葛天專門花了半個月的時間，去研究中國美術史。",
      "subtitle": "葛天專門花了半個月的時間，去研究中國美術史。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#038",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#038-2",
      "start": 213.306,
      "end": 216.175,
      "duration": 2.869,
      "narration": "葛天專門花了半個月的時間，去研究中國美術史。",
      "subtitle": "葛天專門花了半個月的時間，去研究中國美術史。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#038",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#039-1",
      "start": 216.175,
      "end": 219.219,
      "duration": 3.044,
      "narration": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "subtitle": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#039",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#039-2",
      "start": 219.219,
      "end": 222.262,
      "duration": 3.043,
      "narration": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "subtitle": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#039",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#040-1",
      "start": 222.262,
      "end": 225.424,
      "duration": 3.162,
      "narration": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "subtitle": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#040",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#040-2",
      "start": 225.424,
      "end": 228.587,
      "duration": 3.163,
      "narration": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "subtitle": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#040",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#041-1",
      "start": 228.587,
      "end": 231.637,
      "duration": 3.05,
      "narration": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "subtitle": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#041",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#041-2",
      "start": 231.637,
      "end": 234.687,
      "duration": 3.05,
      "narration": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "subtitle": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#041",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#042-1",
      "start": 234.687,
      "end": 237.394,
      "duration": 2.707,
      "narration": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "subtitle": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#042",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#042-2",
      "start": 237.394,
      "end": 240.1,
      "duration": 2.706,
      "narration": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "subtitle": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#042",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#043-1",
      "start": 240.1,
      "end": 243.118,
      "duration": 3.018,
      "narration": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "subtitle": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#043",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#043-2",
      "start": 243.118,
      "end": 246.137,
      "duration": 3.019,
      "narration": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "subtitle": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#043",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#044-1",
      "start": 246.137,
      "end": 249.069,
      "duration": 2.932,
      "narration": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "subtitle": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#044",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#044-2",
      "start": 249.069,
      "end": 252.0,
      "duration": 2.931,
      "narration": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "subtitle": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#044",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#045-1",
      "start": 252.0,
      "end": 254.713,
      "duration": 2.713,
      "narration": "第三章，掌握好的開場，就是成功的一半以上。",
      "subtitle": "第三章，掌握好的開場，就是成功的一半以上。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#045",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#045-2",
      "start": 254.713,
      "end": 257.425,
      "duration": 2.712,
      "narration": "第三章，掌握好的開場，就是成功的一半以上。",
      "subtitle": "第三章，掌握好的開場，就是成功的一半以上。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#045",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#046-1",
      "start": 257.425,
      "end": 260.025,
      "duration": 2.6,
      "narration": "初次見面的最初三十秒，決定了第一印象。",
      "subtitle": "初次見面的最初三十秒，決定了第一印象。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#046",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#046-2",
      "start": 260.025,
      "end": 262.625,
      "duration": 2.6,
      "narration": "初次見面的最初三十秒，決定了第一印象。",
      "subtitle": "初次見面的最初三十秒，決定了第一印象。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#046",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#047-1",
      "start": 262.625,
      "end": 265.688,
      "duration": 3.063,
      "narration": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "subtitle": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#047",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#047-2",
      "start": 265.688,
      "end": 268.75,
      "duration": 3.062,
      "narration": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "subtitle": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#047",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#048-1",
      "start": 268.75,
      "end": 271.806,
      "duration": 3.056,
      "narration": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "subtitle": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#048",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#048-2",
      "start": 271.806,
      "end": 274.862,
      "duration": 3.056,
      "narration": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "subtitle": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#048",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#049-1",
      "start": 274.862,
      "end": 277.781,
      "duration": 2.919,
      "narration": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "subtitle": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#049",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#049-2",
      "start": 277.781,
      "end": 280.7,
      "duration": 2.919,
      "narration": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "subtitle": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#049",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#050-1",
      "start": 280.7,
      "end": 283.719,
      "duration": 3.019,
      "narration": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "subtitle": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#050",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#050-2",
      "start": 283.719,
      "end": 286.737,
      "duration": 3.018,
      "narration": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "subtitle": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#050",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#051-1",
      "start": 286.737,
      "end": 289.462,
      "duration": 2.725,
      "narration": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "subtitle": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#051",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#051-2",
      "start": 289.462,
      "end": 292.187,
      "duration": 2.725,
      "narration": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "subtitle": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#051",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#052-1",
      "start": 292.187,
      "end": 295.024,
      "duration": 2.837,
      "narration": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "subtitle": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#052",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#052-2",
      "start": 295.024,
      "end": 297.862,
      "duration": 2.838,
      "narration": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "subtitle": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#052",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#053-1",
      "start": 297.862,
      "end": 300.7,
      "duration": 2.838,
      "narration": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "subtitle": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#053",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#053-2",
      "start": 300.7,
      "end": 303.537,
      "duration": 2.837,
      "narration": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "subtitle": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#053",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#054-1",
      "start": 303.537,
      "end": 306.706,
      "duration": 3.169,
      "narration": "第四章，說話只說三分，點到為止反而更有分量。",
      "subtitle": "第四章，說話只說三分，點到為止反而更有分量。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#054",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#054-2",
      "start": 306.706,
      "end": 309.875,
      "duration": 3.169,
      "narration": "第四章，說話只說三分，點到為止反而更有分量。",
      "subtitle": "第四章，說話只說三分，點到為止反而更有分量。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#054",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#055-1",
      "start": 309.875,
      "end": 312.793,
      "duration": 2.918,
      "narration": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "subtitle": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#055",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#055-2",
      "start": 312.793,
      "end": 315.712,
      "duration": 2.919,
      "narration": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "subtitle": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#055",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#056-1",
      "start": 315.712,
      "end": 318.256,
      "duration": 2.544,
      "narration": "批評他人之前，必須先給對方戴高帽子。",
      "subtitle": "批評他人之前，必須先給對方戴高帽子。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#056",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#056-2",
      "start": 318.256,
      "end": 320.8,
      "duration": 2.544,
      "narration": "批評他人之前，必須先給對方戴高帽子。",
      "subtitle": "批評他人之前，必須先給對方戴高帽子。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#056",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#057-1",
      "start": 320.8,
      "end": 323.788,
      "duration": 2.988,
      "narration": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "subtitle": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#057",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#057-2",
      "start": 323.788,
      "end": 326.775,
      "duration": 2.987,
      "narration": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "subtitle": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#057",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#058-1",
      "start": 326.775,
      "end": 329.525,
      "duration": 2.75,
      "narration": "提出不同意見時要繞圈子說，用商量的口吻。",
      "subtitle": "提出不同意見時要繞圈子說，用商量的口吻。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#058",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#058-2",
      "start": 329.525,
      "end": 332.275,
      "duration": 2.75,
      "narration": "提出不同意見時要繞圈子說，用商量的口吻。",
      "subtitle": "提出不同意見時要繞圈子說，用商量的口吻。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#058",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#059-1",
      "start": 332.275,
      "end": 335.681,
      "duration": 3.406,
      "narration": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "subtitle": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#059",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#059-2",
      "start": 335.681,
      "end": 339.087,
      "duration": 3.406,
      "narration": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "subtitle": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#059",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#060-1",
      "start": 339.087,
      "end": 342.399,
      "duration": 3.312,
      "narration": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "subtitle": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#060",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#060-2",
      "start": 342.399,
      "end": 345.712,
      "duration": 3.313,
      "narration": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "subtitle": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#060",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#061-1",
      "start": 345.712,
      "end": 348.549,
      "duration": 2.837,
      "narration": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "subtitle": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#061",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#061-2",
      "start": 348.549,
      "end": 351.387,
      "duration": 2.838,
      "narration": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "subtitle": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#061",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#062-1",
      "start": 351.387,
      "end": 354.131,
      "duration": 2.744,
      "narration": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "subtitle": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#062",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#062-2",
      "start": 354.131,
      "end": 356.875,
      "duration": 2.744,
      "narration": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "subtitle": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#062",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#063-1",
      "start": 356.875,
      "end": 359.881,
      "duration": 3.006,
      "narration": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "subtitle": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#063",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#063-2",
      "start": 359.881,
      "end": 362.887,
      "duration": 3.006,
      "narration": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "subtitle": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#063",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#064-1",
      "start": 362.887,
      "end": 365.793,
      "duration": 2.906,
      "narration": "口才不是你聊個不停，而是專注聽完對方說法。",
      "subtitle": "口才不是你聊個不停，而是專注聽完對方說法。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#064",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#064-2",
      "start": 365.793,
      "end": 368.7,
      "duration": 2.907,
      "narration": "口才不是你聊個不停，而是專注聽完對方說法。",
      "subtitle": "口才不是你聊個不停，而是專注聽完對方說法。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#064",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#065-1",
      "start": 368.7,
      "end": 371.528,
      "duration": 2.828,
      "narration": "學會承認「不知道」，反而能給對方表現機會。",
      "subtitle": "學會承認「不知道」，反而能給對方表現機會。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#065",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#065-2",
      "start": 371.528,
      "end": 374.356,
      "duration": 2.828,
      "narration": "學會承認「不知道」，反而能給對方表現機會。",
      "subtitle": "學會承認「不知道」，反而能給對方表現機會。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#065",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#066-1",
      "start": 374.356,
      "end": 376.899,
      "duration": 2.543,
      "narration": "不要一開口就說「不對」，用認同包裝否定。",
      "subtitle": "不要一開口就說「不對」，用認同包裝否定。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#066",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#066-2",
      "start": 376.899,
      "end": 379.443,
      "duration": 2.544,
      "narration": "不要一開口就說「不對」，用認同包裝否定。",
      "subtitle": "不要一開口就說「不對」，用認同包裝否定。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#066",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#067-1",
      "start": 379.443,
      "end": 382.53,
      "duration": 3.087,
      "narration": "只要你會提問、拋球，話題不深也能延續熱度。",
      "subtitle": "只要你會提問、拋球，話題不深也能延續熱度。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#067",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#067-2",
      "start": 382.53,
      "end": 385.618,
      "duration": 3.088,
      "narration": "只要你會提問、拋球，話題不深也能延續熱度。",
      "subtitle": "只要你會提問、拋球，話題不深也能延續熱度。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#067",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#068-1",
      "start": 385.618,
      "end": 388.468,
      "duration": 2.85,
      "narration": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "subtitle": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#068",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#068-2",
      "start": 388.468,
      "end": 391.318,
      "duration": 2.85,
      "narration": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "subtitle": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#068",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#069-1",
      "start": 391.318,
      "end": 394.218,
      "duration": 2.9,
      "narration": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "subtitle": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#069",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#069-2",
      "start": 394.218,
      "end": 397.118,
      "duration": 2.9,
      "narration": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "subtitle": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#069",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#070-1",
      "start": 397.118,
      "end": 400.325,
      "duration": 3.207,
      "narration": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "subtitle": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#070",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#070-2",
      "start": 400.325,
      "end": 403.531,
      "duration": 3.206,
      "narration": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "subtitle": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#070",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#071-1",
      "start": 403.531,
      "end": 406.637,
      "duration": 3.106,
      "narration": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "subtitle": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#071",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#071-2",
      "start": 406.637,
      "end": 409.743,
      "duration": 3.106,
      "narration": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "subtitle": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#071",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#072-1",
      "start": 409.743,
      "end": 412.725,
      "duration": 2.982,
      "narration": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "subtitle": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#072",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#072-2",
      "start": 412.725,
      "end": 415.706,
      "duration": 2.981,
      "narration": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "subtitle": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#072",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#073-1",
      "start": 415.706,
      "end": 418.956,
      "duration": 3.25,
      "narration": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "subtitle": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#073",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#073-2",
      "start": 418.956,
      "end": 422.206,
      "duration": 3.25,
      "narration": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "subtitle": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#073",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#074-1",
      "start": 422.206,
      "end": 425.293,
      "duration": 3.087,
      "narration": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "subtitle": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#074",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#074-2",
      "start": 425.293,
      "end": 428.381,
      "duration": 3.088,
      "narration": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "subtitle": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#074",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#075-1",
      "start": 428.381,
      "end": 431.093,
      "duration": 2.712,
      "narration": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "subtitle": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#075",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#075-2",
      "start": 431.093,
      "end": 433.806,
      "duration": 2.713,
      "narration": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "subtitle": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#075",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#076-1",
      "start": 433.806,
      "end": 436.625,
      "duration": 2.819,
      "narration": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "subtitle": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#076",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#076-2",
      "start": 436.625,
      "end": 439.443,
      "duration": 2.818,
      "narration": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "subtitle": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#076",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#077-1",
      "start": 439.443,
      "end": 442.287,
      "duration": 2.844,
      "narration": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "subtitle": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#077",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#077-2",
      "start": 442.287,
      "end": 445.131,
      "duration": 2.844,
      "narration": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "subtitle": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#077",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#078-1",
      "start": 445.131,
      "end": 448.062,
      "duration": 2.931,
      "narration": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "subtitle": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#078",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#078-2",
      "start": 448.062,
      "end": 450.993,
      "duration": 2.931,
      "narration": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "subtitle": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#078",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#079-1",
      "start": 450.993,
      "end": 453.993,
      "duration": 3.0,
      "narration": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "subtitle": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#079",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#079-2",
      "start": 453.993,
      "end": 456.993,
      "duration": 3.0,
      "narration": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "subtitle": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#079",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#080-1",
      "start": 456.993,
      "end": 460.162,
      "duration": 3.169,
      "narration": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "subtitle": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#080",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#080-2",
      "start": 460.162,
      "end": 463.331,
      "duration": 3.169,
      "narration": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "subtitle": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#080",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#081-1",
      "start": 463.331,
      "end": 466.012,
      "duration": 2.681,
      "narration": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "subtitle": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#081",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#081-2",
      "start": 466.012,
      "end": 468.693,
      "duration": 2.681,
      "narration": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "subtitle": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#081",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#082-1",
      "start": 468.693,
      "end": 471.793,
      "duration": 3.1,
      "narration": "第八章，公司和社團開會，說什麼才容易被接受。",
      "subtitle": "第八章，公司和社團開會，說什麼才容易被接受。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#082",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#082-2",
      "start": 471.793,
      "end": 474.893,
      "duration": 3.1,
      "narration": "第八章，公司和社團開會，說什麼才容易被接受。",
      "subtitle": "第八章，公司和社團開會，說什麼才容易被接受。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#082",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#083-1",
      "start": 474.893,
      "end": 477.824,
      "duration": 2.931,
      "narration": "在公司或團體中，只會默默做事很難被看見。",
      "subtitle": "在公司或團體中，只會默默做事很難被看見。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#083",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#083-2",
      "start": 477.824,
      "end": 480.756,
      "duration": 2.932,
      "narration": "在公司或團體中，只會默默做事很難被看見。",
      "subtitle": "在公司或團體中，只會默默做事很難被看見。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#083",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#084-1",
      "start": 480.756,
      "end": 483.587,
      "duration": 2.831,
      "narration": "主動且得體向主管匯報工作，是生存的必修課。",
      "subtitle": "主動且得體向主管匯報工作，是生存的必修課。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#084",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#084-2",
      "start": 483.587,
      "end": 486.418,
      "duration": 2.831,
      "narration": "主動且得體向主管匯報工作，是生存的必修課。",
      "subtitle": "主動且得體向主管匯報工作，是生存的必修課。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#084",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#085-1",
      "start": 486.418,
      "end": 489.375,
      "duration": 2.957,
      "narration": "匯報要結論先行、條理清晰，展現組織能力。",
      "subtitle": "匯報要結論先行、條理清晰，展現組織能力。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#085",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#085-2",
      "start": 489.375,
      "end": 492.331,
      "duration": 2.956,
      "narration": "匯報要結論先行、條理清晰，展現組織能力。",
      "subtitle": "匯報要結論先行、條理清晰，展現組織能力。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#085",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#086-1",
      "start": 492.331,
      "end": 495.244,
      "duration": 2.913,
      "narration": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "subtitle": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#086",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#086-2",
      "start": 495.244,
      "end": 498.156,
      "duration": 2.912,
      "narration": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "subtitle": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#086",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#087-1",
      "start": 498.156,
      "end": 501.049,
      "duration": 2.893,
      "narration": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "subtitle": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#087",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#087-2",
      "start": 501.049,
      "end": 503.943,
      "duration": 2.894,
      "narration": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "subtitle": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#087",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#088-1",
      "start": 503.943,
      "end": 506.849,
      "duration": 2.906,
      "narration": "不發牢騷，只提建設性方案，才能贏得支持。",
      "subtitle": "不發牢騷，只提建設性方案，才能贏得支持。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#088",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#088-2",
      "start": 506.849,
      "end": 509.756,
      "duration": 2.907,
      "narration": "不發牢騷，只提建設性方案，才能贏得支持。",
      "subtitle": "不發牢騷，只提建設性方案，才能贏得支持。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#088",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#089-1",
      "start": 509.756,
      "end": 512.718,
      "duration": 2.962,
      "narration": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "subtitle": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#089",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#089-2",
      "start": 512.718,
      "end": 515.681,
      "duration": 2.963,
      "narration": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "subtitle": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#089",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#090-1",
      "start": 515.681,
      "end": 518.881,
      "duration": 3.2,
      "narration": "訊息和電話不是任性工具，必須充分尊重時間。",
      "subtitle": "訊息和電話不是任性工具，必須充分尊重時間。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#090",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#090-2",
      "start": 518.881,
      "end": 522.081,
      "duration": 3.2,
      "narration": "訊息和電話不是任性工具，必須充分尊重時間。",
      "subtitle": "訊息和電話不是任性工具，必須充分尊重時間。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#090",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#091-1",
      "start": 522.081,
      "end": 524.925,
      "duration": 2.844,
      "narration": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "subtitle": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#091",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#091-2",
      "start": 524.925,
      "end": 527.768,
      "duration": 2.843,
      "narration": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "subtitle": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#091",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#092-1",
      "start": 527.768,
      "end": 530.737,
      "duration": 2.969,
      "narration": "善用引導式提問，先引導對方在交談中說「是」。",
      "subtitle": "善用引導式提問，先引導對方在交談中說「是」。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#092",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#092-2",
      "start": 530.737,
      "end": 533.706,
      "duration": 2.969,
      "narration": "善用引導式提問，先引導對方在交談中說「是」。",
      "subtitle": "善用引導式提問，先引導對方在交談中說「是」。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#092",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#093-1",
      "start": 533.706,
      "end": 536.55,
      "duration": 2.844,
      "narration": "引導對方相信，那本來就是他自己的明智想法。",
      "subtitle": "引導對方相信，那本來就是他自己的明智想法。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#093",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#093-2",
      "start": 536.55,
      "end": 539.393,
      "duration": 2.843,
      "narration": "引導對方相信，那本來就是他自己的明智想法。",
      "subtitle": "引導對方相信，那本來就是他自己的明智想法。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#093",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\*\\*\\#094-1",
      "start": 539.393,
      "end": 542.25,
      "duration": 2.857,
      "narration": "面對被拒絕時，要展現出大度且成熟的態度。",
      "subtitle": "面對被拒絕時，要展現出大度且成熟的態度。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#094",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\*\\*\\#094-2",
      "start": 542.25,
      "end": 545.106,
      "duration": 2.856,
      "narration": "面對被拒絕時，要展現出大度且成熟的態度。",
      "subtitle": "面對被拒絕時，要展現出大度且成熟的態度。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#094",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#095-1",
      "start": 545.106,
      "end": 547.949,
      "duration": 2.843,
      "narration": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "subtitle": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#095",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#095-2",
      "start": 547.949,
      "end": 550.793,
      "duration": 2.844,
      "narration": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "subtitle": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#095",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#096-1",
      "start": 550.793,
      "end": 553.668,
      "duration": 2.875,
      "narration": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "subtitle": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#096",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#096-2",
      "start": 553.668,
      "end": 556.543,
      "duration": 2.875,
      "narration": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "subtitle": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#096",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#097-1",
      "start": 556.543,
      "end": 559.562,
      "duration": 3.019,
      "narration": "其實會前與會後的非正式溝通，往往決定成敗。",
      "subtitle": "其實會前與會後的非正式溝通，往往決定成敗。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#097",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#097-2",
      "start": 559.562,
      "end": 562.581,
      "duration": 3.019,
      "narration": "其實會前與會後的非正式溝通，往往決定成敗。",
      "subtitle": "其實會前與會後的非正式溝通，往往決定成敗。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#097",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#098-1",
      "start": 562.581,
      "end": 565.656,
      "duration": 3.075,
      "narration": "發言要在專業內容中，注入適度的熱切與熱情。",
      "subtitle": "發言要在專業內容中，注入適度的熱切與熱情。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#098",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#098-2",
      "start": 565.656,
      "end": 568.731,
      "duration": 3.075,
      "narration": "發言要在專業內容中，注入適度的熱切與熱情。",
      "subtitle": "發言要在專業內容中，注入適度的熱切與熱情。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#098",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#099-1",
      "start": 568.731,
      "end": 571.574,
      "duration": 2.843,
      "narration": "給出一個強而有力的結尾，明確指出下一步行動。",
      "subtitle": "給出一個強而有力的結尾，明確指出下一步行動。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#099",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#099-2",
      "start": 571.574,
      "end": 574.418,
      "duration": 2.844,
      "narration": "給出一個強而有力的結尾，明確指出下一步行動。",
      "subtitle": "給出一個強而有力的結尾，明確指出下一步行動。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#099",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#100-1",
      "start": 574.418,
      "end": 577.35,
      "duration": 2.932,
      "narration": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "subtitle": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#100",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#100-2",
      "start": 577.35,
      "end": 580.281,
      "duration": 2.931,
      "narration": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "subtitle": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#100",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#101-1",
      "start": 580.281,
      "end": 583.043,
      "duration": 2.762,
      "narration": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "subtitle": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#101",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#101-2",
      "start": 583.043,
      "end": 585.806,
      "duration": 2.763,
      "narration": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "subtitle": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#101",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#102-1",
      "start": 585.806,
      "end": 589.093,
      "duration": 3.287,
      "narration": "第十一章，九九％的人不懂如何和親近家人表達。",
      "subtitle": "第十一章，九九％的人不懂如何和親近家人表達。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#102",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#102-2",
      "start": 589.093,
      "end": 592.381,
      "duration": 3.288,
      "narration": "第十一章，九九％的人不懂如何和親近家人表達。",
      "subtitle": "第十一章，九九％的人不懂如何和親近家人表達。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#102",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#103-1",
      "start": 592.381,
      "end": 595.212,
      "duration": 2.831,
      "narration": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "subtitle": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#103",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#103-2",
      "start": 595.212,
      "end": 598.043,
      "duration": 2.831,
      "narration": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "subtitle": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#103",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#104-1",
      "start": 598.043,
      "end": 600.737,
      "duration": 2.694,
      "narration": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "subtitle": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#104",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#104-2",
      "start": 600.737,
      "end": 603.431,
      "duration": 2.694,
      "narration": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "subtitle": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#104",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#105-1",
      "start": 603.431,
      "end": 606.199,
      "duration": 2.768,
      "narration": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "subtitle": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#105",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#105-2",
      "start": 606.199,
      "end": 608.968,
      "duration": 2.769,
      "narration": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "subtitle": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#105",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#106-1",
      "start": 608.968,
      "end": 611.993,
      "duration": 3.025,
      "narration": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "subtitle": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#106",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#106-2",
      "start": 611.993,
      "end": 615.018,
      "duration": 3.025,
      "narration": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "subtitle": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#106",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#107-1",
      "start": 615.018,
      "end": 617.887,
      "duration": 2.869,
      "narration": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "subtitle": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#107",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#107-2",
      "start": 617.887,
      "end": 620.756,
      "duration": 2.869,
      "narration": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "subtitle": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#107",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#108-1",
      "start": 620.756,
      "end": 623.712,
      "duration": 2.956,
      "narration": "每天進家門前，強迫自己做好角色切換三秒。",
      "subtitle": "每天進家門前，強迫自己做好角色切換三秒。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#108",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#108-2",
      "start": 623.712,
      "end": 626.668,
      "duration": 2.956,
      "narration": "每天進家門前，強迫自己做好角色切換三秒。",
      "subtitle": "每天進家門前，強迫自己做好角色切換三秒。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#108",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#109-1",
      "start": 626.668,
      "end": 629.63,
      "duration": 2.962,
      "narration": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "subtitle": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#109",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#109-2",
      "start": 629.63,
      "end": 632.593,
      "duration": 2.963,
      "narration": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "subtitle": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#109",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#110-1",
      "start": 632.593,
      "end": 635.374,
      "duration": 2.781,
      "narration": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "subtitle": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#110",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#110-2",
      "start": 635.374,
      "end": 638.156,
      "duration": 2.782,
      "narration": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "subtitle": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#110",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#111-1",
      "start": 638.156,
      "end": 640.768,
      "duration": 2.612,
      "narration": "肯定你的愛人，他才會長成你理想中的樣子。",
      "subtitle": "肯定你的愛人，他才會長成你理想中的樣子。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#111",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#111-2",
      "start": 640.768,
      "end": 643.381,
      "duration": 2.613,
      "narration": "肯定你的愛人，他才會長成你理想中的樣子。",
      "subtitle": "肯定你的愛人，他才會長成你理想中的樣子。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#111",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#112-1",
      "start": 643.381,
      "end": 646.343,
      "duration": 2.962,
      "narration": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "subtitle": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#112",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#112-2",
      "start": 646.343,
      "end": 649.306,
      "duration": 2.963,
      "narration": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "subtitle": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#112",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#113-1",
      "start": 649.306,
      "end": 652.231,
      "duration": 2.925,
      "narration": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "subtitle": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#113",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#113-2",
      "start": 652.231,
      "end": 655.156,
      "duration": 2.925,
      "narration": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "subtitle": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#113",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#114-1",
      "start": 655.156,
      "end": 657.806,
      "duration": 2.65,
      "narration": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "subtitle": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#114",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#114-2",
      "start": 657.806,
      "end": 660.456,
      "duration": 2.65,
      "narration": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "subtitle": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#114",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#115-1",
      "start": 660.456,
      "end": 663.35,
      "duration": 2.894,
      "narration": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "subtitle": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#115",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#115-2",
      "start": 663.35,
      "end": 666.243,
      "duration": 2.893,
      "narration": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "subtitle": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#115",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#116-1",
      "start": 666.243,
      "end": 668.981,
      "duration": 2.738,
      "narration": "看完這十二個章節，你是不是也有很深的觸動？",
      "subtitle": "看完這十二個章節，你是不是也有很深的觸動？",
      "section": "6. 全書統整與結語",
      "sourceShot": "#116",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#116-2",
      "start": 668.981,
      "end": 671.718,
      "duration": 2.737,
      "narration": "看完這十二個章節，你是不是也有很深的觸動？",
      "subtitle": "看完這十二個章節，你是不是也有很深的觸動？",
      "section": "6. 全書統整與結語",
      "sourceShot": "#116",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#117-1",
      "start": 671.718,
      "end": 674.643,
      "duration": 2.925,
      "narration": "表達力不是口才炫技，而是理解與尊重的修行。",
      "subtitle": "表達力不是口才炫技，而是理解與尊重的修行。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#117",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#117-2",
      "start": 674.643,
      "end": 677.568,
      "duration": 2.925,
      "narration": "表達力不是口才炫技，而是理解與尊重的修行。",
      "subtitle": "表達力不是口才炫技，而是理解與尊重的修行。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#117",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#118-1",
      "start": 677.568,
      "end": 680.493,
      "duration": 2.925,
      "narration": "今天，我為大家規劃了可立即實踐的三項行動。",
      "subtitle": "今天，我為大家規劃了可立即實踐的三項行動。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#118",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#118-2",
      "start": 680.493,
      "end": 683.418,
      "duration": 2.925,
      "narration": "今天，我為大家規劃了可立即實踐的三項行動。",
      "subtitle": "今天，我為大家規劃了可立即實踐的三項行動。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#118",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#119-1",
      "start": 683.418,
      "end": 686.649,
      "duration": 3.231,
      "narration": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "subtitle": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#119",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#119-2",
      "start": 686.649,
      "end": 689.881,
      "duration": 3.232,
      "narration": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "subtitle": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#119",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#120-1",
      "start": 689.881,
      "end": 692.987,
      "duration": 3.106,
      "narration": "第二，職場結論先行，批評前先肯定對方的優點。",
      "subtitle": "第二，職場結論先行，批評前先肯定對方的優點。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#120",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#120-2",
      "start": 692.987,
      "end": 696.093,
      "duration": 3.106,
      "narration": "第二，職場結論先行，批評前先肯定對方的優點。",
      "subtitle": "第二，職場結論先行，批評前先肯定對方的優點。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#120",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#121-1",
      "start": 696.093,
      "end": 699.318,
      "duration": 3.225,
      "narration": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "subtitle": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#121",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#121-2",
      "start": 699.318,
      "end": 702.543,
      "duration": 3.225,
      "narration": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "subtitle": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#121",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#122-1",
      "start": 702.543,
      "end": 705.462,
      "duration": 2.919,
      "narration": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "subtitle": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#122",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#122-2",
      "start": 705.462,
      "end": 708.381,
      "duration": 2.919,
      "narration": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "subtitle": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#122",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#123-1",
      "start": 708.381,
      "end": 713.056,
      "duration": 4.675,
      "narration": "謝謝大家，我們下期讀書會再見。",
      "subtitle": "謝謝大家，我們下期讀書會再見。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#123",
      "motion": "zoom-in",
      "description": null
    }
  ],
  "captions": [
    {
      "id": 1,
      "sourceShot": "#001",
      "start": 0.1,
      "end": 5.537,
      "text": "你身邊有沒有一種人，明明工作能力極強？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 2,
      "sourceShot": "#002",
      "start": 5.537,
      "end": 10.875,
      "text": "但每次開會輪到他發言，他就無比緊張？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 3,
      "sourceShot": "#003",
      "start": 10.875,
      "end": 16.75,
      "text": "最後他發言冷場連連，風頭全被別人搶走？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 4,
      "sourceShot": "#004",
      "start": 16.75,
      "end": 21.862,
      "text": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 5,
      "sourceShot": "#005",
      "start": 21.862,
      "end": 27.187,
      "text": "對我們而言，你的心裡是不是也曾感到委屈？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 6,
      "sourceShot": "#006",
      "start": 27.187,
      "end": 32.15,
      "text": "或者，你是不是也常對外人客客氣氣？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 7,
      "sourceShot": "#007",
      "start": 32.15,
      "end": 37.275,
      "text": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 8,
      "sourceShot": "#008",
      "start": 37.275,
      "end": 42.462,
      "text": "我們都以為好好說話是一件無關緊要的事。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 9,
      "sourceShot": "#009",
      "start": 42.462,
      "end": 48.037,
      "text": "卻不知道九九％的人，都輸在不會表達上。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 10,
      "sourceShot": "#010",
      "start": 48.037,
      "end": 53.337,
      "text": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 11,
      "sourceShot": "#011",
      "start": 53.337,
      "end": 58.687,
      "text": "這本書將帶我們看懂生活中所有的溝通死角。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 12,
      "sourceShot": "#012",
      "start": 58.687,
      "end": 64.562,
      "text": "無論是職場應對、陌生破冰、還是家庭相處。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 13,
      "sourceShot": "#013",
      "start": 64.562,
      "end": 69.687,
      "text": "話說對了，人生中所有的麻煩，就沒了。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 14,
      "sourceShot": "#014",
      "start": 69.687,
      "end": 75.837,
      "text": "《99%的人輸在不會表達》是一本溝通聖經。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 15,
      "sourceShot": "#015",
      "start": 75.837,
      "end": 81.887,
      "text": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 16,
      "sourceShot": "#016",
      "start": 81.887,
      "end": 87.825,
      "text": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 17,
      "sourceShot": "#017",
      "start": 87.825,
      "end": 92.8,
      "text": "李勁在書中，提出了一個非常震撼的觀點。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 18,
      "sourceShot": "#018",
      "start": 92.8,
      "end": 98.687,
      "text": "一個人的成功，只有百分之十五取決於專業技術。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 19,
      "sourceShot": "#019",
      "start": 98.687,
      "end": 104.212,
      "text": "而其餘的百分之八十五，全取決於有效溝通。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 20,
      "sourceShot": "#020",
      "start": 104.212,
      "end": 109.55,
      "text": "這本書想解決能力優秀、卻不會表達的痛點。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 21,
      "sourceShot": "#021",
      "start": 109.55,
      "end": 115.675,
      "text": "它非常適合職場人士、樂齡族與家庭經營者。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 22,
      "sourceShot": "#022",
      "start": 115.675,
      "end": 121.062,
      "text": "全書十二個章節，呈現出嚴密的遞進架構。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 23,
      "sourceShot": "#023",
      "start": 121.062,
      "end": 126.637,
      "text": "今天我將為大家，進行最完整的逐章拆解。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 24,
      "sourceShot": "#024",
      "start": 126.637,
      "end": 134.037,
      "text": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 25,
      "sourceShot": "#025",
      "start": 134.037,
      "end": 139.862,
      "text": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 26,
      "sourceShot": "#026",
      "start": 139.862,
      "end": 145.3,
      "text": "明明很有才華，卻常因為緊張而不敢開口？",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 27,
      "sourceShot": "#027",
      "start": 145.3,
      "end": 151.3,
      "text": "作者指出，社交緊張大多源自於過強的自尊心。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 28,
      "sourceShot": "#028",
      "start": 151.3,
      "end": 157.362,
      "text": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 29,
      "sourceShot": "#029",
      "start": 157.362,
      "end": 162.937,
      "text": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 30,
      "sourceShot": "#030",
      "start": 162.937,
      "end": 168.925,
      "text": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 31,
      "sourceShot": "#031",
      "start": 168.925,
      "end": 174.812,
      "text": "我們也可以在開口之前，進行黃金心理暗示法。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 32,
      "sourceShot": "#032",
      "start": 174.812,
      "end": 181.437,
      "text": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 33,
      "sourceShot": "#033",
      "start": 181.437,
      "end": 187.45,
      "text": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 34,
      "sourceShot": "#034",
      "start": 187.45,
      "end": 193.65,
      "text": "不追求完美表現，每天練習對店員微笑對視吧。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 35,
      "sourceShot": "#035",
      "start": 193.65,
      "end": 199.487,
      "text": "第二章，先學會閱人，然後說到對方的心理去。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 36,
      "sourceShot": "#036",
      "start": 199.487,
      "end": 204.6,
      "text": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 37,
      "sourceShot": "#037",
      "start": 204.6,
      "end": 210.437,
      "text": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 38,
      "sourceShot": "#038",
      "start": 210.437,
      "end": 216.175,
      "text": "葛天專門花了半個月的時間，去研究中國美術史。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 39,
      "sourceShot": "#039",
      "start": 216.175,
      "end": 222.262,
      "text": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 40,
      "sourceShot": "#040",
      "start": 222.262,
      "end": 228.587,
      "text": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 41,
      "sourceShot": "#041",
      "start": 228.587,
      "end": 234.687,
      "text": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 42,
      "sourceShot": "#042",
      "start": 234.687,
      "end": 240.1,
      "text": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 43,
      "sourceShot": "#043",
      "start": 240.1,
      "end": 246.137,
      "text": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 44,
      "sourceShot": "#044",
      "start": 246.137,
      "end": 252.0,
      "text": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 45,
      "sourceShot": "#045",
      "start": 252.0,
      "end": 257.425,
      "text": "第三章，掌握好的開場，就是成功的一半以上。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 46,
      "sourceShot": "#046",
      "start": 257.425,
      "end": 262.625,
      "text": "初次見面的最初三十秒，決定了第一印象。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 47,
      "sourceShot": "#047",
      "start": 262.625,
      "end": 268.75,
      "text": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 48,
      "sourceShot": "#048",
      "start": 268.75,
      "end": 274.862,
      "text": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 49,
      "sourceShot": "#049",
      "start": 274.862,
      "end": 280.7,
      "text": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 50,
      "sourceShot": "#050",
      "start": 280.7,
      "end": 286.737,
      "text": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 51,
      "sourceShot": "#051",
      "start": 286.737,
      "end": 292.187,
      "text": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 52,
      "sourceShot": "#052",
      "start": 292.187,
      "end": 297.862,
      "text": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 53,
      "sourceShot": "#053",
      "start": 297.862,
      "end": 303.537,
      "text": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 54,
      "sourceShot": "#054",
      "start": 303.537,
      "end": 309.875,
      "text": "第四章，說話只說三分，點到為止反而更有分量。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 55,
      "sourceShot": "#055",
      "start": 309.875,
      "end": 315.712,
      "text": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 56,
      "sourceShot": "#056",
      "start": 315.712,
      "end": 320.8,
      "text": "批評他人之前，必須先給對方戴高帽子。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 57,
      "sourceShot": "#057",
      "start": 320.8,
      "end": 326.775,
      "text": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 58,
      "sourceShot": "#058",
      "start": 326.775,
      "end": 332.275,
      "text": "提出不同意見時要繞圈子說，用商量的口吻。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 59,
      "sourceShot": "#059",
      "start": 332.275,
      "end": 339.087,
      "text": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 60,
      "sourceShot": "#060",
      "start": 339.087,
      "end": 345.712,
      "text": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 61,
      "sourceShot": "#061",
      "start": 345.712,
      "end": 351.387,
      "text": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 62,
      "sourceShot": "#062",
      "start": 351.387,
      "end": 356.875,
      "text": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 63,
      "sourceShot": "#063",
      "start": 356.875,
      "end": 362.887,
      "text": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 64,
      "sourceShot": "#064",
      "start": 362.887,
      "end": 368.7,
      "text": "口才不是你聊個不停，而是專注聽完對方說法。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 65,
      "sourceShot": "#065",
      "start": 368.7,
      "end": 374.356,
      "text": "學會承認「不知道」，反而能給對方表現機會。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 66,
      "sourceShot": "#066",
      "start": 374.356,
      "end": 379.443,
      "text": "不要一開口就說「不對」，用認同包裝否定。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 67,
      "sourceShot": "#067",
      "start": 379.443,
      "end": 385.618,
      "text": "只要你會提問、拋球，話題不深也能延續熱度。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 68,
      "sourceShot": "#068",
      "start": 385.618,
      "end": 391.318,
      "text": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 69,
      "sourceShot": "#069",
      "start": 391.318,
      "end": 397.118,
      "text": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 70,
      "sourceShot": "#070",
      "start": 397.118,
      "end": 403.531,
      "text": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 71,
      "sourceShot": "#071",
      "start": 403.531,
      "end": 409.743,
      "text": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 72,
      "sourceShot": "#072",
      "start": 409.743,
      "end": 415.706,
      "text": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 73,
      "sourceShot": "#073",
      "start": 415.706,
      "end": 422.206,
      "text": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 74,
      "sourceShot": "#074",
      "start": 422.206,
      "end": 428.381,
      "text": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 75,
      "sourceShot": "#075",
      "start": 428.381,
      "end": 433.806,
      "text": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 76,
      "sourceShot": "#076",
      "start": 433.806,
      "end": 439.443,
      "text": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 77,
      "sourceShot": "#077",
      "start": 439.443,
      "end": 445.131,
      "text": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 78,
      "sourceShot": "#078",
      "start": 445.131,
      "end": 450.993,
      "text": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 79,
      "sourceShot": "#079",
      "start": 450.993,
      "end": 456.993,
      "text": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 80,
      "sourceShot": "#080",
      "start": 456.993,
      "end": 463.331,
      "text": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 81,
      "sourceShot": "#081",
      "start": 463.331,
      "end": 468.693,
      "text": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 82,
      "sourceShot": "#082",
      "start": 468.693,
      "end": 474.893,
      "text": "第八章，公司和社團開會，說什麼才容易被接受。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 83,
      "sourceShot": "#083",
      "start": 474.893,
      "end": 480.756,
      "text": "在公司或團體中，只會默默做事很難被看見。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 84,
      "sourceShot": "#084",
      "start": 480.756,
      "end": 486.418,
      "text": "主動且得體向主管匯報工作，是生存的必修課。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 85,
      "sourceShot": "#085",
      "start": 486.418,
      "end": 492.331,
      "text": "匯報要結論先行、條理清晰，展現組織能力。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 86,
      "sourceShot": "#086",
      "start": 492.331,
      "end": 498.156,
      "text": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 87,
      "sourceShot": "#087",
      "start": 498.156,
      "end": 503.943,
      "text": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 88,
      "sourceShot": "#088",
      "start": 503.943,
      "end": 509.756,
      "text": "不發牢騷，只提建設性方案，才能贏得支持。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 89,
      "sourceShot": "#089",
      "start": 509.756,
      "end": 515.681,
      "text": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 90,
      "sourceShot": "#090",
      "start": 515.681,
      "end": 522.081,
      "text": "訊息和電話不是任性工具，必須充分尊重時間。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 91,
      "sourceShot": "#091",
      "start": 522.081,
      "end": 527.768,
      "text": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 92,
      "sourceShot": "#092",
      "start": 527.768,
      "end": 533.706,
      "text": "善用引導式提問，先引導對方在交談中說「是」。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 93,
      "sourceShot": "#093",
      "start": 533.706,
      "end": 539.393,
      "text": "引導對方相信，那本來就是他自己的明智想法。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 94,
      "sourceShot": "#094",
      "start": 539.393,
      "end": 545.106,
      "text": "面對被拒絕時，要展現出大度且成熟的態度。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 95,
      "sourceShot": "#095",
      "start": 545.106,
      "end": 550.793,
      "text": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 96,
      "sourceShot": "#096",
      "start": 550.793,
      "end": 556.543,
      "text": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 97,
      "sourceShot": "#097",
      "start": 556.543,
      "end": 562.581,
      "text": "其實會前與會後的非正式溝通，往往決定成敗。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 98,
      "sourceShot": "#098",
      "start": 562.581,
      "end": 568.731,
      "text": "發言要在專業內容中，注入適度的熱切與熱情。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 99,
      "sourceShot": "#099",
      "start": 568.731,
      "end": 574.418,
      "text": "給出一個強而有力的結尾，明確指出下一步行動。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 100,
      "sourceShot": "#100",
      "start": 574.418,
      "end": 580.281,
      "text": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 101,
      "sourceShot": "#101",
      "start": 580.281,
      "end": 585.806,
      "text": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 102,
      "sourceShot": "#102",
      "start": 585.806,
      "end": 592.381,
      "text": "第十一章，九九％的人不懂如何和親近家人表達。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 103,
      "sourceShot": "#103",
      "start": 592.381,
      "end": 598.043,
      "text": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 104,
      "sourceShot": "#104",
      "start": 598.043,
      "end": 603.431,
      "text": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 105,
      "sourceShot": "#105",
      "start": 603.431,
      "end": 608.968,
      "text": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 106,
      "sourceShot": "#106",
      "start": 608.968,
      "end": 615.018,
      "text": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 107,
      "sourceShot": "#107",
      "start": 615.018,
      "end": 620.756,
      "text": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 108,
      "sourceShot": "#108",
      "start": 620.756,
      "end": 626.668,
      "text": "每天進家門前，強迫自己做好角色切換三秒。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 109,
      "sourceShot": "#109",
      "start": 626.668,
      "end": 632.593,
      "text": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 110,
      "sourceShot": "#110",
      "start": 632.593,
      "end": 638.156,
      "text": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 111,
      "sourceShot": "#111",
      "start": 638.156,
      "end": 643.381,
      "text": "肯定你的愛人，他才會長成你理想中的樣子。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 112,
      "sourceShot": "#112",
      "start": 643.381,
      "end": 649.306,
      "text": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 113,
      "sourceShot": "#113",
      "start": 649.306,
      "end": 655.156,
      "text": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 114,
      "sourceShot": "#114",
      "start": 655.156,
      "end": 660.456,
      "text": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 115,
      "sourceShot": "#115",
      "start": 660.456,
      "end": 666.243,
      "text": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 116,
      "sourceShot": "#116",
      "start": 666.243,
      "end": 671.718,
      "text": "看完這十二個章節，你是不是也有很深的觸動？",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 117,
      "sourceShot": "#117",
      "start": 671.718,
      "end": 677.568,
      "text": "表達力不是口才炫技，而是理解與尊重的修行。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 118,
      "sourceShot": "#118",
      "start": 677.568,
      "end": 683.418,
      "text": "今天，我為大家規劃了可立即實踐的三項行動。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 119,
      "sourceShot": "#119",
      "start": 683.418,
      "end": 689.881,
      "text": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 120,
      "sourceShot": "#120",
      "start": 689.881,
      "end": 696.093,
      "text": "第二，職場結論先行，批評前先肯定對方的優點。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 121,
      "sourceShot": "#121",
      "start": 696.093,
      "end": 702.543,
      "text": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 122,
      "sourceShot": "#122",
      "start": 702.543,
      "end": 708.381,
      "text": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 123,
      "sourceShot": "#123",
      "start": 708.381,
      "end": 713.056,
      "text": "謝謝大家，我們下期讀書會再見。",
      "section": "6. 全書統整與結語"
    }
  ]
};
