window.APP_DATA={
  "title": "《99%的人輸在不會表達》",
  "version": "V2-手繪插畫男聲",
  "voice": "Chinese (Taiwan) - YunJhe",
  "voiceDurationSeconds": 713.112,
  "spokenDurationSeconds": 560.801,
  "sourceSentenceCount": 123,
  "visualSegmentCount": 244,
  "segments": [
    {
      "id": "\\#001-1",
      "start": 0.1,
      "end": 2.269,
      "duration": 2.169,
      "narration": "你身邊有沒有一種人，明明工作能力極強？",
      "subtitle": "你身邊有沒有一種人，明明工作能力極強？",
      "section": "0. 片頭與提問",
      "sourceShot": "#001",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#001-2",
      "start": 2.269,
      "end": 4.437,
      "duration": 2.168,
      "narration": "你身邊有沒有一種人，明明工作能力極強？",
      "subtitle": "你身邊有沒有一種人，明明工作能力極強？",
      "section": "0. 片頭與提問",
      "sourceShot": "#001",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#002-1",
      "start": 4.437,
      "end": 6.45,
      "duration": 2.013,
      "narration": "但每次開會輪到他發言，他就無比緊張？",
      "subtitle": "但每次開會輪到他發言，他就無比緊張？",
      "section": "0. 片頭與提問",
      "sourceShot": "#002",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#002-2",
      "start": 6.45,
      "end": 8.462,
      "duration": 2.012,
      "narration": "但每次開會輪到他發言，他就無比緊張？",
      "subtitle": "但每次開會輪到他發言，他就無比緊張？",
      "section": "0. 片頭與提問",
      "sourceShot": "#002",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#003-1",
      "start": 8.462,
      "end": 10.756,
      "duration": 2.294,
      "narration": "最後他發言冷場連連，風頭全被別人搶走？",
      "subtitle": "最後他發言冷場連連，風頭全被別人搶走？",
      "section": "0. 片頭與提問",
      "sourceShot": "#003",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#003-2",
      "start": 10.756,
      "end": 13.05,
      "duration": 2.294,
      "narration": "最後他發言冷場連連，風頭全被別人搶走？",
      "subtitle": "最後他發言冷場連連，風頭全被別人搶走？",
      "section": "0. 片頭與提問",
      "sourceShot": "#003",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#004-1",
      "start": 13.05,
      "end": 15.175,
      "duration": 2.125,
      "narration": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "subtitle": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "section": "0. 片頭與提問",
      "sourceShot": "#004",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#004-2",
      "start": 15.175,
      "end": 17.3,
      "duration": 2.125,
      "narration": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "subtitle": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "section": "0. 片頭與提問",
      "sourceShot": "#004",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#005-1",
      "start": 17.3,
      "end": 19.406,
      "duration": 2.106,
      "narration": "對我們而言，你的心裡是不是也曾感到委屈？",
      "subtitle": "對我們而言，你的心裡是不是也曾感到委屈？",
      "section": "0. 片頭與提問",
      "sourceShot": "#005",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#005-2",
      "start": 19.406,
      "end": 21.512,
      "duration": 2.106,
      "narration": "對我們而言，你的心裡是不是也曾感到委屈？",
      "subtitle": "對我們而言，你的心裡是不是也曾感到委屈？",
      "section": "0. 片頭與提問",
      "sourceShot": "#005",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#006-1",
      "start": 21.512,
      "end": 25.612,
      "duration": 4.1,
      "narration": "或者，你是不是也常對外人客客氣氣？",
      "subtitle": "或者，你是不是也常對外人客客氣氣？",
      "section": "0. 片頭與提問",
      "sourceShot": "#006",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#007-1",
      "start": 25.612,
      "end": 27.612,
      "duration": 2.0,
      "narration": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "subtitle": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "section": "0. 片頭與提問",
      "sourceShot": "#007",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#007-2",
      "start": 27.612,
      "end": 29.612,
      "duration": 2.0,
      "narration": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "subtitle": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "section": "0. 片頭與提問",
      "sourceShot": "#007",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#008-1",
      "start": 29.612,
      "end": 31.537,
      "duration": 1.925,
      "narration": "我們都以為好好說話是一件無關緊要的事。",
      "subtitle": "我們都以為好好說話是一件無關緊要的事。",
      "section": "0. 片頭與提問",
      "sourceShot": "#008",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#008-2",
      "start": 31.537,
      "end": 33.462,
      "duration": 1.925,
      "narration": "我們都以為好好說話是一件無關緊要的事。",
      "subtitle": "我們都以為好好說話是一件無關緊要的事。",
      "section": "0. 片頭與提問",
      "sourceShot": "#008",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#009-1",
      "start": 33.462,
      "end": 35.694,
      "duration": 2.232,
      "narration": "卻不知道九九％的人，都輸在不會表達上。",
      "subtitle": "卻不知道九九％的人，都輸在不會表達上。",
      "section": "0. 片頭與提問",
      "sourceShot": "#009",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#009-2",
      "start": 35.694,
      "end": 37.925,
      "duration": 2.231,
      "narration": "卻不知道九九％的人，都輸在不會表達上。",
      "subtitle": "卻不知道九九％的人，都輸在不會表達上。",
      "section": "0. 片頭與提問",
      "sourceShot": "#009",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#010-1",
      "start": 37.925,
      "end": 40.037,
      "duration": 2.112,
      "narration": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "subtitle": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "section": "0. 片頭與提問",
      "sourceShot": "#010",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#010-2",
      "start": 40.037,
      "end": 42.15,
      "duration": 2.113,
      "narration": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "subtitle": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "section": "0. 片頭與提問",
      "sourceShot": "#010",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#011-1",
      "start": 42.15,
      "end": 44.263,
      "duration": 2.113,
      "narration": "這本書將帶我們看懂生活中所有的溝通死角。",
      "subtitle": "這本書將帶我們看懂生活中所有的溝通死角。",
      "section": "0. 片頭與提問",
      "sourceShot": "#011",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#011-2",
      "start": 44.263,
      "end": 46.375,
      "duration": 2.112,
      "narration": "這本書將帶我們看懂生活中所有的溝通死角。",
      "subtitle": "這本書將帶我們看懂生活中所有的溝通死角。",
      "section": "0. 片頭與提問",
      "sourceShot": "#011",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#012-1",
      "start": 46.375,
      "end": 48.706,
      "duration": 2.331,
      "narration": "無論是職場應對、陌生破冰、還是家庭相處。",
      "subtitle": "無論是職場應對、陌生破冰、還是家庭相處。",
      "section": "0. 片頭與提問",
      "sourceShot": "#012",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#012-2",
      "start": 48.706,
      "end": 51.037,
      "duration": 2.331,
      "narration": "無論是職場應對、陌生破冰、還是家庭相處。",
      "subtitle": "無論是職場應對、陌生破冰、還是家庭相處。",
      "section": "0. 片頭與提問",
      "sourceShot": "#012",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#013-1",
      "start": 51.037,
      "end": 53.2,
      "duration": 2.163,
      "narration": "話說對了，人生中所有的麻煩，就沒了。",
      "subtitle": "話說對了，人生中所有的麻煩，就沒了。",
      "section": "0. 片頭與提問",
      "sourceShot": "#013",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#013-2",
      "start": 53.2,
      "end": 55.362,
      "duration": 2.162,
      "narration": "話說對了，人生中所有的麻煩，就沒了。",
      "subtitle": "話說對了，人生中所有的麻煩，就沒了。",
      "section": "0. 片頭與提問",
      "sourceShot": "#013",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#014-1",
      "start": 55.362,
      "end": 57.756,
      "duration": 2.394,
      "narration": "《99%的人輸在不會表達》是一本溝通聖經。",
      "subtitle": "《99%的人輸在不會表達》是一本溝通聖經。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#014",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#014-2",
      "start": 57.756,
      "end": 60.15,
      "duration": 2.394,
      "narration": "《99%的人輸在不會表達》是一本溝通聖經。",
      "subtitle": "《99%的人輸在不會表達》是一本溝通聖經。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#014",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#015-1",
      "start": 60.15,
      "end": 62.412,
      "duration": 2.262,
      "narration": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "subtitle": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#015",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#015-2",
      "start": 62.412,
      "end": 64.675,
      "duration": 2.263,
      "narration": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "subtitle": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#015",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#016-1",
      "start": 64.675,
      "end": 66.918,
      "duration": 2.243,
      "narration": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "subtitle": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#016",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#016-2",
      "start": 66.918,
      "end": 69.162,
      "duration": 2.244,
      "narration": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "subtitle": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#016",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#017-1",
      "start": 69.162,
      "end": 71.162,
      "duration": 2.0,
      "narration": "李勁在書中，提出了一個非常震撼的觀點。",
      "subtitle": "李勁在書中，提出了一個非常震撼的觀點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#017",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#017-2",
      "start": 71.162,
      "end": 73.162,
      "duration": 2.0,
      "narration": "李勁在書中，提出了一個非常震撼的觀點。",
      "subtitle": "李勁在書中，提出了一個非常震撼的觀點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#017",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#018-1",
      "start": 73.162,
      "end": 75.412,
      "duration": 2.25,
      "narration": "一個人的成功，只有百分之十五取決於專業技術。",
      "subtitle": "一個人的成功，只有百分之十五取決於專業技術。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#018",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#018-2",
      "start": 75.412,
      "end": 77.662,
      "duration": 2.25,
      "narration": "一個人的成功，只有百分之十五取決於專業技術。",
      "subtitle": "一個人的成功，只有百分之十五取決於專業技術。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#018",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#019-1",
      "start": 77.662,
      "end": 79.744,
      "duration": 2.082,
      "narration": "而其餘的百分之八十五，全取決於有效溝通。",
      "subtitle": "而其餘的百分之八十五，全取決於有效溝通。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#019",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#019-2",
      "start": 79.744,
      "end": 81.825,
      "duration": 2.081,
      "narration": "而其餘的百分之八十五，全取決於有效溝通。",
      "subtitle": "而其餘的百分之八十五，全取決於有效溝通。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#019",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#020-1",
      "start": 81.825,
      "end": 83.975,
      "duration": 2.15,
      "narration": "這本書想解決能力優秀、卻不會表達的痛點。",
      "subtitle": "這本書想解決能力優秀、卻不會表達的痛點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#020",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#020-2",
      "start": 83.975,
      "end": 86.125,
      "duration": 2.15,
      "narration": "這本書想解決能力優秀、卻不會表達的痛點。",
      "subtitle": "這本書想解決能力優秀、卻不會表達的痛點。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#020",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#021-1",
      "start": 86.125,
      "end": 88.456,
      "duration": 2.331,
      "narration": "它非常適合職場人士、樂齡族與家庭經營者。",
      "subtitle": "它非常適合職場人士、樂齡族與家庭經營者。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#021",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#021-2",
      "start": 88.456,
      "end": 90.787,
      "duration": 2.331,
      "narration": "它非常適合職場人士、樂齡族與家庭經營者。",
      "subtitle": "它非常適合職場人士、樂齡族與家庭經營者。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#021",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#022-1",
      "start": 90.787,
      "end": 92.95,
      "duration": 2.163,
      "narration": "全書十二個章節，呈現出嚴密的遞進架構。",
      "subtitle": "全書十二個章節，呈現出嚴密的遞進架構。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#022",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#022-2",
      "start": 92.95,
      "end": 95.112,
      "duration": 2.162,
      "narration": "全書十二個章節，呈現出嚴密的遞進架構。",
      "subtitle": "全書十二個章節，呈現出嚴密的遞進架構。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#022",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#023-1",
      "start": 95.112,
      "end": 97.237,
      "duration": 2.125,
      "narration": "今天我將為大家，進行最完整的逐章拆解。",
      "subtitle": "今天我將為大家，進行最完整的逐章拆解。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#023",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#023-2",
      "start": 97.237,
      "end": 99.362,
      "duration": 2.125,
      "narration": "今天我將為大家，進行最完整的逐章拆解。",
      "subtitle": "今天我將為大家，進行最完整的逐章拆解。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#023",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#024-1",
      "start": 99.362,
      "end": 102.049,
      "duration": 2.687,
      "narration": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "subtitle": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#024",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#024-2",
      "start": 102.049,
      "end": 104.737,
      "duration": 2.688,
      "narration": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "subtitle": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "section": "1. 本書定位與閱讀動機",
      "sourceShot": "#024",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#025-1",
      "start": 104.737,
      "end": 107.062,
      "duration": 2.325,
      "narration": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "subtitle": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#025",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#025-2",
      "start": 107.062,
      "end": 109.387,
      "duration": 2.325,
      "narration": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "subtitle": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#025",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#026-1",
      "start": 109.387,
      "end": 111.519,
      "duration": 2.132,
      "narration": "明明很有才華，卻常因為緊張而不敢開口？",
      "subtitle": "明明很有才華，卻常因為緊張而不敢開口？",
      "section": "2. 第一章至第三章",
      "sourceShot": "#026",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#026-2",
      "start": 111.519,
      "end": 113.65,
      "duration": 2.131,
      "narration": "明明很有才華，卻常因為緊張而不敢開口？",
      "subtitle": "明明很有才華，卻常因為緊張而不敢開口？",
      "section": "2. 第一章至第三章",
      "sourceShot": "#026",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#027-1",
      "start": 113.65,
      "end": 115.856,
      "duration": 2.206,
      "narration": "作者指出，社交緊張大多源自於過強的自尊心。",
      "subtitle": "作者指出，社交緊張大多源自於過強的自尊心。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#027",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#027-2",
      "start": 115.856,
      "end": 118.062,
      "duration": 2.206,
      "narration": "作者指出，社交緊張大多源自於過強的自尊心。",
      "subtitle": "作者指出，社交緊張大多源自於過強的自尊心。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#027",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#028-1",
      "start": 118.062,
      "end": 120.337,
      "duration": 2.275,
      "narration": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "subtitle": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#028",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#028-2",
      "start": 120.337,
      "end": 122.612,
      "duration": 2.275,
      "narration": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "subtitle": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#028",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#029-1",
      "start": 122.612,
      "end": 124.806,
      "duration": 2.194,
      "narration": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "subtitle": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#029",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#029-2",
      "start": 124.806,
      "end": 127.0,
      "duration": 2.194,
      "narration": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "subtitle": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#029",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#030-1",
      "start": 127.0,
      "end": 129.238,
      "duration": 2.238,
      "narration": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "subtitle": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#030",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#030-2",
      "start": 129.238,
      "end": 131.475,
      "duration": 2.237,
      "narration": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "subtitle": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#030",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#031-1",
      "start": 131.475,
      "end": 133.681,
      "duration": 2.206,
      "narration": "我們也可以在開口之前，進行黃金心理暗示法。",
      "subtitle": "我們也可以在開口之前，進行黃金心理暗示法。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#031",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#031-2",
      "start": 133.681,
      "end": 135.887,
      "duration": 2.206,
      "narration": "我們也可以在開口之前，進行黃金心理暗示法。",
      "subtitle": "我們也可以在開口之前，進行黃金心理暗示法。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#031",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#032-1",
      "start": 135.887,
      "end": 138.5,
      "duration": 2.613,
      "narration": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "subtitle": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#032",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#032-2",
      "start": 138.5,
      "end": 141.112,
      "duration": 2.612,
      "narration": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "subtitle": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#032",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#033-1",
      "start": 141.112,
      "end": 143.424,
      "duration": 2.312,
      "narration": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "subtitle": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#033",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#033-2",
      "start": 143.424,
      "end": 145.737,
      "duration": 2.313,
      "narration": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "subtitle": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#033",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#034-1",
      "start": 145.737,
      "end": 148.012,
      "duration": 2.275,
      "narration": "不追求完美表現，每天練習對店員微笑對視吧。",
      "subtitle": "不追求完美表現，每天練習對店員微笑對視吧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#034",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#034-2",
      "start": 148.012,
      "end": 150.287,
      "duration": 2.275,
      "narration": "不追求完美表現，每天練習對店員微笑對視吧。",
      "subtitle": "不追求完美表現，每天練習對店員微笑對視吧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#034",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#035-1",
      "start": 150.287,
      "end": 152.644,
      "duration": 2.357,
      "narration": "第二章，先學會閱人，然後說到對方的心理去。",
      "subtitle": "第二章，先學會閱人，然後說到對方的心理去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#035",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#035-2",
      "start": 152.644,
      "end": 155.0,
      "duration": 2.356,
      "narration": "第二章，先學會閱人，然後說到對方的心理去。",
      "subtitle": "第二章，先學會閱人，然後說到對方的心理去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#035",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#036-1",
      "start": 155.0,
      "end": 157.118,
      "duration": 2.118,
      "narration": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "subtitle": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#036",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#036-2",
      "start": 157.118,
      "end": 159.237,
      "duration": 2.119,
      "narration": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "subtitle": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#036",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#037-1",
      "start": 159.237,
      "end": 161.5,
      "duration": 2.263,
      "narration": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "subtitle": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#037",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#037-2",
      "start": 161.5,
      "end": 163.762,
      "duration": 2.262,
      "narration": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "subtitle": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#037",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#038-1",
      "start": 163.762,
      "end": 166.024,
      "duration": 2.262,
      "narration": "葛天專門花了半個月的時間，去研究中國美術史。",
      "subtitle": "葛天專門花了半個月的時間，去研究中國美術史。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#038",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#038-2",
      "start": 166.024,
      "end": 168.287,
      "duration": 2.263,
      "narration": "葛天專門花了半個月的時間，去研究中國美術史。",
      "subtitle": "葛天專門花了半個月的時間，去研究中國美術史。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#038",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#039-1",
      "start": 168.287,
      "end": 170.625,
      "duration": 2.338,
      "narration": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "subtitle": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#039",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#039-2",
      "start": 170.625,
      "end": 172.962,
      "duration": 2.337,
      "narration": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "subtitle": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#039",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#040-1",
      "start": 172.962,
      "end": 175.162,
      "duration": 2.2,
      "narration": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "subtitle": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#040",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#040-2",
      "start": 175.162,
      "end": 177.362,
      "duration": 2.2,
      "narration": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "subtitle": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#040",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#041-1",
      "start": 177.362,
      "end": 179.756,
      "duration": 2.394,
      "narration": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "subtitle": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#041",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#041-2",
      "start": 179.756,
      "end": 182.15,
      "duration": 2.394,
      "narration": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "subtitle": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#041",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#042-1",
      "start": 182.15,
      "end": 184.375,
      "duration": 2.225,
      "narration": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "subtitle": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#042",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#042-2",
      "start": 184.375,
      "end": 186.6,
      "duration": 2.225,
      "narration": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "subtitle": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#042",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#043-1",
      "start": 186.6,
      "end": 188.962,
      "duration": 2.362,
      "narration": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "subtitle": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#043",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#043-2",
      "start": 188.962,
      "end": 191.325,
      "duration": 2.363,
      "narration": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "subtitle": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#043",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#044-1",
      "start": 191.325,
      "end": 193.518,
      "duration": 2.193,
      "narration": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "subtitle": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#044",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#044-2",
      "start": 193.518,
      "end": 195.712,
      "duration": 2.194,
      "narration": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "subtitle": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#044",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#045-1",
      "start": 195.712,
      "end": 198.062,
      "duration": 2.35,
      "narration": "第三章，掌握好的開場，就是成功的一半以上。",
      "subtitle": "第三章，掌握好的開場，就是成功的一半以上。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#045",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#045-2",
      "start": 198.062,
      "end": 200.412,
      "duration": 2.35,
      "narration": "第三章，掌握好的開場，就是成功的一半以上。",
      "subtitle": "第三章，掌握好的開場，就是成功的一半以上。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#045",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#046-1",
      "start": 200.412,
      "end": 202.512,
      "duration": 2.1,
      "narration": "初次見面的最初三十秒，決定了第一印象。",
      "subtitle": "初次見面的最初三十秒，決定了第一印象。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#046",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#046-2",
      "start": 202.512,
      "end": 204.612,
      "duration": 2.1,
      "narration": "初次見面的最初三十秒，決定了第一印象。",
      "subtitle": "初次見面的最初三十秒，決定了第一印象。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#046",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#047-1",
      "start": 204.612,
      "end": 207.075,
      "duration": 2.463,
      "narration": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "subtitle": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#047",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#047-2",
      "start": 207.075,
      "end": 209.537,
      "duration": 2.462,
      "narration": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "subtitle": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#047",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#048-1",
      "start": 209.537,
      "end": 211.899,
      "duration": 2.362,
      "narration": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "subtitle": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#048",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#048-2",
      "start": 211.899,
      "end": 214.262,
      "duration": 2.363,
      "narration": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "subtitle": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#048",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#049-1",
      "start": 214.262,
      "end": 216.512,
      "duration": 2.25,
      "narration": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "subtitle": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#049",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#049-2",
      "start": 216.512,
      "end": 218.762,
      "duration": 2.25,
      "narration": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "subtitle": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#049",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#050-1",
      "start": 218.762,
      "end": 221.049,
      "duration": 2.287,
      "narration": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "subtitle": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#050",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#050-2",
      "start": 221.049,
      "end": 223.337,
      "duration": 2.288,
      "narration": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "subtitle": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#050",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#051-1",
      "start": 223.337,
      "end": 225.562,
      "duration": 2.225,
      "narration": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "subtitle": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#051",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#051-2",
      "start": 225.562,
      "end": 227.787,
      "duration": 2.225,
      "narration": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "subtitle": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#051",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#052-1",
      "start": 227.787,
      "end": 230.012,
      "duration": 2.225,
      "narration": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "subtitle": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#052",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#052-2",
      "start": 230.012,
      "end": 232.237,
      "duration": 2.225,
      "narration": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "subtitle": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#052",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#053-1",
      "start": 232.237,
      "end": 234.625,
      "duration": 2.388,
      "narration": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "subtitle": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#053",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#053-2",
      "start": 234.625,
      "end": 237.012,
      "duration": 2.387,
      "narration": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "subtitle": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "section": "2. 第一章至第三章",
      "sourceShot": "#053",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#054-1",
      "start": 237.012,
      "end": 239.399,
      "duration": 2.387,
      "narration": "第四章，說話只說三分，點到為止反而更有分量。",
      "subtitle": "第四章，說話只說三分，點到為止反而更有分量。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#054",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#054-2",
      "start": 239.399,
      "end": 241.787,
      "duration": 2.388,
      "narration": "第四章，說話只說三分，點到為止反而更有分量。",
      "subtitle": "第四章，說話只說三分，點到為止反而更有分量。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#054",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#055-1",
      "start": 241.787,
      "end": 244.168,
      "duration": 2.381,
      "narration": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "subtitle": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#055",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#055-2",
      "start": 244.168,
      "end": 246.55,
      "duration": 2.382,
      "narration": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "subtitle": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#055",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#056-1",
      "start": 246.55,
      "end": 248.556,
      "duration": 2.006,
      "narration": "批評他人之前，必須先給對方戴高帽子。",
      "subtitle": "批評他人之前，必須先給對方戴高帽子。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#056",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#056-2",
      "start": 248.556,
      "end": 250.562,
      "duration": 2.006,
      "narration": "批評他人之前，必須先給對方戴高帽子。",
      "subtitle": "批評他人之前，必須先給對方戴高帽子。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#056",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#057-1",
      "start": 250.562,
      "end": 252.95,
      "duration": 2.388,
      "narration": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "subtitle": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#057",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#057-2",
      "start": 252.95,
      "end": 255.337,
      "duration": 2.387,
      "narration": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "subtitle": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#057",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#058-1",
      "start": 255.337,
      "end": 257.462,
      "duration": 2.125,
      "narration": "提出不同意見時要繞圈子說，用商量的口吻。",
      "subtitle": "提出不同意見時要繞圈子說，用商量的口吻。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#058",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#058-2",
      "start": 257.462,
      "end": 259.587,
      "duration": 2.125,
      "narration": "提出不同意見時要繞圈子說，用商量的口吻。",
      "subtitle": "提出不同意見時要繞圈子說，用商量的口吻。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#058",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#059-1",
      "start": 259.587,
      "end": 262.037,
      "duration": 2.45,
      "narration": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "subtitle": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#059",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#059-2",
      "start": 262.037,
      "end": 264.487,
      "duration": 2.45,
      "narration": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "subtitle": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#059",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#060-1",
      "start": 264.487,
      "end": 267.106,
      "duration": 2.619,
      "narration": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "subtitle": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#060",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#060-2",
      "start": 267.106,
      "end": 269.725,
      "duration": 2.619,
      "narration": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "subtitle": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#060",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#061-1",
      "start": 269.725,
      "end": 271.825,
      "duration": 2.1,
      "narration": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "subtitle": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#061",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#061-2",
      "start": 271.825,
      "end": 273.925,
      "duration": 2.1,
      "narration": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "subtitle": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#061",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#062-1",
      "start": 273.925,
      "end": 276.087,
      "duration": 2.162,
      "narration": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "subtitle": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#062",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#062-2",
      "start": 276.087,
      "end": 278.25,
      "duration": 2.163,
      "narration": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "subtitle": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#062",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#063-1",
      "start": 278.25,
      "end": 280.594,
      "duration": 2.344,
      "narration": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "subtitle": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#063",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#063-2",
      "start": 280.594,
      "end": 282.937,
      "duration": 2.343,
      "narration": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "subtitle": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#063",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#064-1",
      "start": 282.937,
      "end": 285.256,
      "duration": 2.319,
      "narration": "口才不是你聊個不停，而是專注聽完對方說法。",
      "subtitle": "口才不是你聊個不停，而是專注聽完對方說法。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#064",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#064-2",
      "start": 285.256,
      "end": 287.575,
      "duration": 2.319,
      "narration": "口才不是你聊個不停，而是專注聽完對方說法。",
      "subtitle": "口才不是你聊個不停，而是專注聽完對方說法。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#064",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#065-1",
      "start": 287.575,
      "end": 289.769,
      "duration": 2.194,
      "narration": "學會承認「不知道」，反而能給對方表現機會。",
      "subtitle": "學會承認「不知道」，反而能給對方表現機會。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#065",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#065-2",
      "start": 289.769,
      "end": 291.964,
      "duration": 2.195,
      "narration": "學會承認「不知道」，反而能給對方表現機會。",
      "subtitle": "學會承認「不知道」，反而能給對方表現機會。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#065",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#066-1",
      "start": 291.964,
      "end": 294.114,
      "duration": 2.15,
      "narration": "不要一開口就說「不對」，用認同包裝否定。",
      "subtitle": "不要一開口就說「不對」，用認同包裝否定。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#066",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#066-2",
      "start": 294.114,
      "end": 296.264,
      "duration": 2.15,
      "narration": "不要一開口就說「不對」，用認同包裝否定。",
      "subtitle": "不要一開口就說「不對」，用認同包裝否定。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#066",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#067-1",
      "start": 296.264,
      "end": 298.745,
      "duration": 2.481,
      "narration": "只要你會提問、拋球，話題不深也能延續熱度。",
      "subtitle": "只要你會提問、拋球，話題不深也能延續熱度。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#067",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#067-2",
      "start": 298.745,
      "end": 301.226,
      "duration": 2.481,
      "narration": "只要你會提問、拋球，話題不深也能延續熱度。",
      "subtitle": "只要你會提問、拋球，話題不深也能延續熱度。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#067",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#068-1",
      "start": 301.226,
      "end": 303.851,
      "duration": 2.625,
      "narration": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "subtitle": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#068",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#068-2",
      "start": 303.851,
      "end": 306.476,
      "duration": 2.625,
      "narration": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "subtitle": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#068",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#069-1",
      "start": 306.476,
      "end": 308.726,
      "duration": 2.25,
      "narration": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "subtitle": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#069",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#069-2",
      "start": 308.726,
      "end": 310.976,
      "duration": 2.25,
      "narration": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "subtitle": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#069",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#070-1",
      "start": 310.976,
      "end": 313.545,
      "duration": 2.569,
      "narration": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "subtitle": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#070",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#070-2",
      "start": 313.545,
      "end": 316.114,
      "duration": 2.569,
      "narration": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "subtitle": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#070",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#071-1",
      "start": 316.114,
      "end": 318.295,
      "duration": 2.181,
      "narration": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "subtitle": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#071",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#071-2",
      "start": 318.295,
      "end": 320.476,
      "duration": 2.181,
      "narration": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "subtitle": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#071",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#072-1",
      "start": 320.476,
      "end": 322.908,
      "duration": 2.432,
      "narration": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "subtitle": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#072",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#072-2",
      "start": 322.908,
      "end": 325.339,
      "duration": 2.431,
      "narration": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "subtitle": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#072",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#073-1",
      "start": 325.339,
      "end": 327.739,
      "duration": 2.4,
      "narration": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "subtitle": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#073",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#073-2",
      "start": 327.739,
      "end": 330.139,
      "duration": 2.4,
      "narration": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "subtitle": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#073",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#074-1",
      "start": 330.139,
      "end": 332.507,
      "duration": 2.368,
      "narration": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "subtitle": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#074",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#074-2",
      "start": 332.507,
      "end": 334.876,
      "duration": 2.369,
      "narration": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "subtitle": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#074",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#075-1",
      "start": 334.876,
      "end": 337.076,
      "duration": 2.2,
      "narration": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "subtitle": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#075",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#075-2",
      "start": 337.076,
      "end": 339.276,
      "duration": 2.2,
      "narration": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "subtitle": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "section": "3. 第四章至第六章",
      "sourceShot": "#075",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#076-1",
      "start": 339.276,
      "end": 341.726,
      "duration": 2.45,
      "narration": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "subtitle": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#076",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#076-2",
      "start": 341.726,
      "end": 344.176,
      "duration": 2.45,
      "narration": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "subtitle": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#076",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#077-1",
      "start": 344.176,
      "end": 346.401,
      "duration": 2.225,
      "narration": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "subtitle": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#077",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#077-2",
      "start": 346.401,
      "end": 348.626,
      "duration": 2.225,
      "narration": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "subtitle": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#077",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#078-1",
      "start": 348.626,
      "end": 350.938,
      "duration": 2.312,
      "narration": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "subtitle": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#078",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#078-2",
      "start": 350.938,
      "end": 353.251,
      "duration": 2.313,
      "narration": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "subtitle": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#078",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#079-1",
      "start": 353.251,
      "end": 355.639,
      "duration": 2.388,
      "narration": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "subtitle": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#079",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#079-2",
      "start": 355.639,
      "end": 358.026,
      "duration": 2.387,
      "narration": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "subtitle": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#079",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#080-1",
      "start": 358.026,
      "end": 360.464,
      "duration": 2.438,
      "narration": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "subtitle": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#080",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#080-2",
      "start": 360.464,
      "end": 362.901,
      "duration": 2.437,
      "narration": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "subtitle": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#080",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#081-1",
      "start": 362.901,
      "end": 365.214,
      "duration": 2.313,
      "narration": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "subtitle": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#081",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#081-2",
      "start": 365.214,
      "end": 367.526,
      "duration": 2.312,
      "narration": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "subtitle": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#081",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#082-1",
      "start": 367.526,
      "end": 369.976,
      "duration": 2.45,
      "narration": "第八章，公司和社團開會，說什麼才容易被接受。",
      "subtitle": "第八章，公司和社團開會，說什麼才容易被接受。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#082",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#082-2",
      "start": 369.976,
      "end": 372.426,
      "duration": 2.45,
      "narration": "第八章，公司和社團開會，說什麼才容易被接受。",
      "subtitle": "第八章，公司和社團開會，說什麼才容易被接受。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#082",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#083-1",
      "start": 372.426,
      "end": 374.645,
      "duration": 2.219,
      "narration": "在公司或團體中，只會默默做事很難被看見。",
      "subtitle": "在公司或團體中，只會默默做事很難被看見。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#083",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#083-2",
      "start": 374.645,
      "end": 376.864,
      "duration": 2.219,
      "narration": "在公司或團體中，只會默默做事很難被看見。",
      "subtitle": "在公司或團體中，只會默默做事很難被看見。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#083",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#084-1",
      "start": 376.864,
      "end": 379.202,
      "duration": 2.338,
      "narration": "主動且得體向主管匯報工作，是生存的必修課。",
      "subtitle": "主動且得體向主管匯報工作，是生存的必修課。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#084",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#084-2",
      "start": 379.202,
      "end": 381.539,
      "duration": 2.337,
      "narration": "主動且得體向主管匯報工作，是生存的必修課。",
      "subtitle": "主動且得體向主管匯報工作，是生存的必修課。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#084",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#085-1",
      "start": 381.539,
      "end": 383.976,
      "duration": 2.437,
      "narration": "匯報要結論先行、條理清晰，展現組織能力。",
      "subtitle": "匯報要結論先行、條理清晰，展現組織能力。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#085",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#085-2",
      "start": 383.976,
      "end": 386.414,
      "duration": 2.438,
      "narration": "匯報要結論先行、條理清晰，展現組織能力。",
      "subtitle": "匯報要結論先行、條理清晰，展現組織能力。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#085",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#086-1",
      "start": 386.414,
      "end": 388.614,
      "duration": 2.2,
      "narration": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "subtitle": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#086",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#086-2",
      "start": 388.614,
      "end": 390.814,
      "duration": 2.2,
      "narration": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "subtitle": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#086",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#087-1",
      "start": 390.814,
      "end": 393.008,
      "duration": 2.194,
      "narration": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "subtitle": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#087",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#087-2",
      "start": 393.008,
      "end": 395.201,
      "duration": 2.193,
      "narration": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "subtitle": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#087",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#088-1",
      "start": 395.201,
      "end": 397.508,
      "duration": 2.307,
      "narration": "不發牢騷，只提建設性方案，才能贏得支持。",
      "subtitle": "不發牢騷，只提建設性方案，才能贏得支持。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#088",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#088-2",
      "start": 397.508,
      "end": 399.814,
      "duration": 2.306,
      "narration": "不發牢騷，只提建設性方案，才能贏得支持。",
      "subtitle": "不發牢騷，只提建設性方案，才能贏得支持。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#088",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#089-1",
      "start": 399.814,
      "end": 402.127,
      "duration": 2.313,
      "narration": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "subtitle": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#089",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#089-2",
      "start": 402.127,
      "end": 404.439,
      "duration": 2.312,
      "narration": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "subtitle": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#089",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#090-1",
      "start": 404.439,
      "end": 406.82,
      "duration": 2.381,
      "narration": "訊息和電話不是任性工具，必須充分尊重時間。",
      "subtitle": "訊息和電話不是任性工具，必須充分尊重時間。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#090",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#090-2",
      "start": 406.82,
      "end": 409.201,
      "duration": 2.381,
      "narration": "訊息和電話不是任性工具，必須充分尊重時間。",
      "subtitle": "訊息和電話不是任性工具，必須充分尊重時間。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#090",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#091-1",
      "start": 409.201,
      "end": 411.514,
      "duration": 2.313,
      "narration": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "subtitle": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#091",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#091-2",
      "start": 411.514,
      "end": 413.826,
      "duration": 2.312,
      "narration": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "subtitle": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#091",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#092-1",
      "start": 413.826,
      "end": 416.251,
      "duration": 2.425,
      "narration": "善用引導式提問，先引導對方在交談中說「是」。",
      "subtitle": "善用引導式提問，先引導對方在交談中說「是」。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#092",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#092-2",
      "start": 416.251,
      "end": 418.676,
      "duration": 2.425,
      "narration": "善用引導式提問，先引導對方在交談中說「是」。",
      "subtitle": "善用引導式提問，先引導對方在交談中說「是」。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#092",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#093-1",
      "start": 418.676,
      "end": 421.001,
      "duration": 2.325,
      "narration": "引導對方相信，那本來就是他自己的明智想法。",
      "subtitle": "引導對方相信，那本來就是他自己的明智想法。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#093",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#093-2",
      "start": 421.001,
      "end": 423.326,
      "duration": 2.325,
      "narration": "引導對方相信，那本來就是他自己的明智想法。",
      "subtitle": "引導對方相信，那本來就是他自己的明智想法。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#093",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\*\\*\\#094-1",
      "start": 423.326,
      "end": 425.645,
      "duration": 2.319,
      "narration": "面對被拒絕時，要展現出大度且成熟的態度。",
      "subtitle": "面對被拒絕時，要展現出大度且成熟的態度。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#094",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\*\\*\\#094-2",
      "start": 425.645,
      "end": 427.964,
      "duration": 2.319,
      "narration": "面對被拒絕時，要展現出大度且成熟的態度。",
      "subtitle": "面對被拒絕時，要展現出大度且成熟的態度。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#094",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#095-1",
      "start": 427.964,
      "end": 430.132,
      "duration": 2.168,
      "narration": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "subtitle": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#095",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#095-2",
      "start": 430.132,
      "end": 432.301,
      "duration": 2.169,
      "narration": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "subtitle": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#095",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#096-1",
      "start": 432.301,
      "end": 434.558,
      "duration": 2.257,
      "narration": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "subtitle": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#096",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#096-2",
      "start": 434.558,
      "end": 436.814,
      "duration": 2.256,
      "narration": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "subtitle": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#096",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#097-1",
      "start": 436.814,
      "end": 439.095,
      "duration": 2.281,
      "narration": "其實會前與會後的非正式溝通，往往決定成敗。",
      "subtitle": "其實會前與會後的非正式溝通，往往決定成敗。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#097",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#097-2",
      "start": 439.095,
      "end": 441.376,
      "duration": 2.281,
      "narration": "其實會前與會後的非正式溝通，往往決定成敗。",
      "subtitle": "其實會前與會後的非正式溝通，往往決定成敗。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#097",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#098-1",
      "start": 441.376,
      "end": 443.726,
      "duration": 2.35,
      "narration": "發言要在專業內容中，注入適度的熱切與熱情。",
      "subtitle": "發言要在專業內容中，注入適度的熱切與熱情。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#098",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#098-2",
      "start": 443.726,
      "end": 446.076,
      "duration": 2.35,
      "narration": "發言要在專業內容中，注入適度的熱切與熱情。",
      "subtitle": "發言要在專業內容中，注入適度的熱切與熱情。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#098",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#099-1",
      "start": 446.076,
      "end": 448.408,
      "duration": 2.332,
      "narration": "給出一個強而有力的結尾，明確指出下一步行動。",
      "subtitle": "給出一個強而有力的結尾，明確指出下一步行動。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#099",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#099-2",
      "start": 448.408,
      "end": 450.739,
      "duration": 2.331,
      "narration": "給出一個強而有力的結尾，明確指出下一步行動。",
      "subtitle": "給出一個強而有力的結尾，明確指出下一步行動。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#099",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#100-1",
      "start": 450.739,
      "end": 452.995,
      "duration": 2.256,
      "narration": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "subtitle": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#100",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#100-2",
      "start": 452.995,
      "end": 455.251,
      "duration": 2.256,
      "narration": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "subtitle": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#100",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#101-1",
      "start": 455.251,
      "end": 457.488,
      "duration": 2.237,
      "narration": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "subtitle": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#101",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#101-2",
      "start": 457.488,
      "end": 459.726,
      "duration": 2.238,
      "narration": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "subtitle": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "section": "4. 第七章至第十章",
      "sourceShot": "#101",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#102-1",
      "start": 459.726,
      "end": 462.22,
      "duration": 2.494,
      "narration": "第十一章，九九％的人不懂如何和親近家人表達。",
      "subtitle": "第十一章，九九％的人不懂如何和親近家人表達。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#102",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#102-2",
      "start": 462.22,
      "end": 464.714,
      "duration": 2.494,
      "narration": "第十一章，九九％的人不懂如何和親近家人表達。",
      "subtitle": "第十一章，九九％的人不懂如何和親近家人表達。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#102",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#103-1",
      "start": 464.714,
      "end": 466.982,
      "duration": 2.268,
      "narration": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "subtitle": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#103",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#103-2",
      "start": 466.982,
      "end": 469.251,
      "duration": 2.269,
      "narration": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "subtitle": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#103",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#104-1",
      "start": 469.251,
      "end": 471.413,
      "duration": 2.162,
      "narration": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "subtitle": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#104",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#104-2",
      "start": 471.413,
      "end": 473.576,
      "duration": 2.163,
      "narration": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "subtitle": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#104",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#105-1",
      "start": 473.576,
      "end": 475.758,
      "duration": 2.182,
      "narration": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "subtitle": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#105",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#105-2",
      "start": 475.758,
      "end": 477.939,
      "duration": 2.181,
      "narration": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "subtitle": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#105",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#106-1",
      "start": 477.939,
      "end": 480.32,
      "duration": 2.381,
      "narration": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "subtitle": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#106",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#106-2",
      "start": 480.32,
      "end": 482.701,
      "duration": 2.381,
      "narration": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "subtitle": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#106",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#107-1",
      "start": 482.701,
      "end": 484.964,
      "duration": 2.263,
      "narration": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "subtitle": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#107",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#107-2",
      "start": 484.964,
      "end": 487.226,
      "duration": 2.262,
      "narration": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "subtitle": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#107",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#108-1",
      "start": 487.226,
      "end": 489.645,
      "duration": 2.419,
      "narration": "每天進家門前，強迫自己做好角色切換三秒。",
      "subtitle": "每天進家門前，強迫自己做好角色切換三秒。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#108",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#108-2",
      "start": 489.645,
      "end": 492.064,
      "duration": 2.419,
      "narration": "每天進家門前，強迫自己做好角色切換三秒。",
      "subtitle": "每天進家門前，強迫自己做好角色切換三秒。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#108",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#109-1",
      "start": 492.064,
      "end": 494.32,
      "duration": 2.256,
      "narration": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "subtitle": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#109",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#109-2",
      "start": 494.32,
      "end": 496.576,
      "duration": 2.256,
      "narration": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "subtitle": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#109",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#110-1",
      "start": 496.576,
      "end": 498.832,
      "duration": 2.256,
      "narration": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "subtitle": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#110",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#110-2",
      "start": 498.832,
      "end": 501.089,
      "duration": 2.257,
      "narration": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "subtitle": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#110",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#111-1",
      "start": 501.089,
      "end": 503.257,
      "duration": 2.168,
      "narration": "肯定你的愛人，他才會長成你理想中的樣子。",
      "subtitle": "肯定你的愛人，他才會長成你理想中的樣子。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#111",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#111-2",
      "start": 503.257,
      "end": 505.426,
      "duration": 2.169,
      "narration": "肯定你的愛人，他才會長成你理想中的樣子。",
      "subtitle": "肯定你的愛人，他才會長成你理想中的樣子。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#111",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#112-1",
      "start": 505.426,
      "end": 507.876,
      "duration": 2.45,
      "narration": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "subtitle": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#112",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#112-2",
      "start": 507.876,
      "end": 510.326,
      "duration": 2.45,
      "narration": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "subtitle": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#112",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#113-1",
      "start": 510.326,
      "end": 512.538,
      "duration": 2.212,
      "narration": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "subtitle": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#113",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#113-2",
      "start": 512.538,
      "end": 514.751,
      "duration": 2.213,
      "narration": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "subtitle": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#113",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#114-1",
      "start": 514.751,
      "end": 516.882,
      "duration": 2.131,
      "narration": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "subtitle": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#114",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#114-2",
      "start": 516.882,
      "end": 519.014,
      "duration": 2.132,
      "narration": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "subtitle": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#114",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#115-1",
      "start": 519.014,
      "end": 521.302,
      "duration": 2.288,
      "narration": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "subtitle": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#115",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#115-2",
      "start": 521.302,
      "end": 523.589,
      "duration": 2.287,
      "narration": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "subtitle": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "section": "5. 第十一章至第十二章",
      "sourceShot": "#115",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#116-1",
      "start": 523.589,
      "end": 525.814,
      "duration": 2.225,
      "narration": "看完這十二個章節，你是不是也有很深的觸動？",
      "subtitle": "看完這十二個章節，你是不是也有很深的觸動？",
      "section": "6. 全書統整與結語",
      "sourceShot": "#116",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#116-2",
      "start": 525.814,
      "end": 528.039,
      "duration": 2.225,
      "narration": "看完這十二個章節，你是不是也有很深的觸動？",
      "subtitle": "看完這十二個章節，你是不是也有很深的觸動？",
      "section": "6. 全書統整與結語",
      "sourceShot": "#116",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#117-1",
      "start": 528.039,
      "end": 530.427,
      "duration": 2.388,
      "narration": "表達力不是口才炫技，而是理解與尊重的修行。",
      "subtitle": "表達力不是口才炫技，而是理解與尊重的修行。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#117",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#117-2",
      "start": 530.427,
      "end": 532.814,
      "duration": 2.387,
      "narration": "表達力不是口才炫技，而是理解與尊重的修行。",
      "subtitle": "表達力不是口才炫技，而是理解與尊重的修行。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#117",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#118-1",
      "start": 532.814,
      "end": 535.101,
      "duration": 2.287,
      "narration": "今天，我為大家規劃了可立即實踐的三項行動。",
      "subtitle": "今天，我為大家規劃了可立即實踐的三項行動。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#118",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#118-2",
      "start": 535.101,
      "end": 537.389,
      "duration": 2.288,
      "narration": "今天，我為大家規劃了可立即實踐的三項行動。",
      "subtitle": "今天，我為大家規劃了可立即實踐的三項行動。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#118",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#119-1",
      "start": 537.389,
      "end": 539.827,
      "duration": 2.438,
      "narration": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "subtitle": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#119",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#119-2",
      "start": 539.827,
      "end": 542.264,
      "duration": 2.437,
      "narration": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "subtitle": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#119",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#120-1",
      "start": 542.264,
      "end": 544.702,
      "duration": 2.438,
      "narration": "第二，職場結論先行，批評前先肯定對方的優點。",
      "subtitle": "第二，職場結論先行，批評前先肯定對方的優點。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#120",
      "motion": "zoom-in",
      "description": null
    },
    {
      "id": "\\#120-2",
      "start": 544.702,
      "end": 547.139,
      "duration": 2.437,
      "narration": "第二，職場結論先行，批評前先肯定對方的優點。",
      "subtitle": "第二，職場結論先行，批評前先肯定對方的優點。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#120",
      "motion": "pan-right",
      "description": null
    },
    {
      "id": "\\#121-1",
      "start": 547.139,
      "end": 549.783,
      "duration": 2.644,
      "narration": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "subtitle": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#121",
      "motion": "pan-left",
      "description": null
    },
    {
      "id": "\\#121-2",
      "start": 549.783,
      "end": 552.426,
      "duration": 2.643,
      "narration": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "subtitle": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#121",
      "motion": "pan-down",
      "description": null
    },
    {
      "id": "\\#122-1",
      "start": 552.426,
      "end": 554.795,
      "duration": 2.369,
      "narration": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "subtitle": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#122",
      "motion": "pan-up",
      "description": null
    },
    {
      "id": "\\#122-2",
      "start": 554.795,
      "end": 557.164,
      "duration": 2.369,
      "narration": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "subtitle": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#122",
      "motion": "zoom-out",
      "description": null
    },
    {
      "id": "\\#123-1",
      "start": 557.164,
      "end": 560.801,
      "duration": 3.637,
      "narration": "謝謝大家，我們下期讀書會再見。",
      "subtitle": "謝謝大家，我們下期讀書會再見。",
      "section": "6. 全書統整與結語",
      "sourceShot": "#123",
      "motion": "zoom-in",
      "description": null
    }
  ],
  "captions": [
    {
      "id": 1,
      "sourceShot": "#001",
      "start": 0.1,
      "end": 4.437,
      "text": "你身邊有沒有一種人，明明工作能力極強？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 2,
      "sourceShot": "#002",
      "start": 4.437,
      "end": 8.462,
      "text": "但每次開會輪到他發言，他就無比緊張？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 3,
      "sourceShot": "#003",
      "start": 8.462,
      "end": 13.05,
      "text": "最後他發言冷場連連，風頭全被別人搶走？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 4,
      "sourceShot": "#004",
      "start": 13.05,
      "end": 17.3,
      "text": "看著別人只靠一張嘴，就獲得所有的賞識。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 5,
      "sourceShot": "#005",
      "start": 17.3,
      "end": 21.512,
      "text": "對我們而言，你的心裡是不是也曾感到委屈？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 6,
      "sourceShot": "#006",
      "start": 21.512,
      "end": 25.612,
      "text": "或者，你是不是也常對外人客客氣氣？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 7,
      "sourceShot": "#007",
      "start": 25.612,
      "end": 29.612,
      "text": "卻把最壞的脾氣與無聲的沉默留給家人？",
      "section": "0. 片頭與提問"
    },
    {
      "id": 8,
      "sourceShot": "#008",
      "start": 29.612,
      "end": 33.462,
      "text": "我們都以為好好說話是一件無關緊要的事。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 9,
      "sourceShot": "#009",
      "start": 33.462,
      "end": 37.925,
      "text": "卻不知道九九％的人，都輸在不會表達上。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 10,
      "sourceShot": "#010",
      "start": 37.925,
      "end": 42.15,
      "text": "今天，我們一起來聊聊李勁寫的暢銷經典。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 11,
      "sourceShot": "#011",
      "start": 42.15,
      "end": 46.375,
      "text": "這本書將帶我們看懂生活中所有的溝通死角。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 12,
      "sourceShot": "#012",
      "start": 46.375,
      "end": 51.037,
      "text": "無論是職場應對、陌生破冰、還是家庭相處。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 13,
      "sourceShot": "#013",
      "start": 51.037,
      "end": 55.362,
      "text": "話說對了，人生中所有的麻煩，就沒了。",
      "section": "0. 片頭與提問"
    },
    {
      "id": 14,
      "sourceShot": "#014",
      "start": 55.362,
      "end": 60.15,
      "text": "《99%的人輸在不會表達》是一本溝通聖經。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 15,
      "sourceShot": "#015",
      "start": 60.15,
      "end": 64.675,
      "text": "這本書曾經榮登暢銷書排行榜長達二十一個月。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 16,
      "sourceShot": "#016",
      "start": 64.675,
      "end": 69.162,
      "text": "在台灣，這本書也深受許多讀書會的強力推薦。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 17,
      "sourceShot": "#017",
      "start": 69.162,
      "end": 73.162,
      "text": "李勁在書中，提出了一個非常震撼的觀點。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 18,
      "sourceShot": "#018",
      "start": 73.162,
      "end": 77.662,
      "text": "一個人的成功，只有百分之十五取決於專業技術。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 19,
      "sourceShot": "#019",
      "start": 77.662,
      "end": 81.825,
      "text": "而其餘的百分之八十五，全取決於有效溝通。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 20,
      "sourceShot": "#020",
      "start": 81.825,
      "end": 86.125,
      "text": "這本書想解決能力優秀、卻不會表達的痛點。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 21,
      "sourceShot": "#021",
      "start": 86.125,
      "end": 90.787,
      "text": "它非常適合職場人士、樂齡族與家庭經營者。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 22,
      "sourceShot": "#022",
      "start": 90.787,
      "end": 95.112,
      "text": "全書十二個章節，呈現出嚴密的遞進架構。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 23,
      "sourceShot": "#023",
      "start": 95.112,
      "end": 99.362,
      "text": "今天我將為大家，進行最完整的逐章拆解。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 24,
      "sourceShot": "#024",
      "start": 99.362,
      "end": 104.737,
      "text": "準備好了嗎？讓我們一起拿回這八五％的主導權。",
      "section": "1. 本書定位與閱讀動機"
    },
    {
      "id": 25,
      "sourceShot": "#025",
      "start": 104.737,
      "end": 109.387,
      "text": "第一章，先讓自己勇敢開口，別輸在不會表達。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 26,
      "sourceShot": "#026",
      "start": 109.387,
      "end": 113.65,
      "text": "明明很有才華，卻常因為緊張而不敢開口？",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 27,
      "sourceShot": "#027",
      "start": 113.65,
      "end": 118.062,
      "text": "作者指出，社交緊張大多源自於過強的自尊心。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 28,
      "sourceShot": "#028",
      "start": 118.062,
      "end": 122.612,
      "text": "其實，微笑就是生活之中跨越敵意最動聽的話。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 29,
      "sourceShot": "#029",
      "start": 122.612,
      "end": 127.0,
      "text": "面對服務生的刁難，大鼻子女士用微笑化解。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 30,
      "sourceShot": "#030",
      "start": 127.0,
      "end": 131.475,
      "text": "就像西雅圖魚市的魚販，把賣魚變成拋接藝術。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 31,
      "sourceShot": "#031",
      "start": 131.475,
      "end": 135.887,
      "text": "我們也可以在開口之前，進行黃金心理暗示法。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 32,
      "sourceShot": "#032",
      "start": 135.887,
      "end": 141.112,
      "text": "穿戴整齊、調整音量，眼神接觸能投射正面磁場。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 33,
      "sourceShot": "#033",
      "start": 141.112,
      "end": 145.737,
      "text": "心直口快並不是優點，通常只是教養欠佳罷了。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 34,
      "sourceShot": "#034",
      "start": 145.737,
      "end": 150.287,
      "text": "不追求完美表現，每天練習對店員微笑對視吧。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 35,
      "sourceShot": "#035",
      "start": 150.287,
      "end": 155.0,
      "text": "第二章，先學會閱人，然後說到對方的心理去。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 36,
      "sourceShot": "#036",
      "start": 155.0,
      "end": 159.237,
      "text": "要去誰的山頭，我們就得學唱對方的歌謠。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 37,
      "sourceShot": "#037",
      "start": 159.237,
      "end": 163.762,
      "text": "葛天為了能拉近與對方的距離，他做了很多功課。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 38,
      "sourceShot": "#038",
      "start": 163.762,
      "end": 168.287,
      "text": "葛天專門花了半個月的時間，去研究中國美術史。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 39,
      "sourceShot": "#039",
      "start": 168.287,
      "end": 172.962,
      "text": "最終古怪的大師視他為知音，爽快答應出任顧問。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 40,
      "sourceShot": "#040",
      "start": 172.962,
      "end": 177.362,
      "text": "聽話要聽聲，鑼鼓聽音，多咀嚼一下弦外之音。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 41,
      "sourceShot": "#041",
      "start": 177.362,
      "end": 182.15,
      "text": "語速突然變快代表焦慮，語速突然變慢代表隱瞞。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 42,
      "sourceShot": "#042",
      "start": 182.15,
      "end": 186.6,
      "text": "誇張的肢體動作常透露出對方內心的不耐煩。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 43,
      "sourceShot": "#043",
      "start": 186.6,
      "end": 191.325,
      "text": "讀懂對方的隱形需求，我們才能夠說到對方心坎裡。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 44,
      "sourceShot": "#044",
      "start": 191.325,
      "end": 195.712,
      "text": "在台灣日常生活中，這也是建立好交情的捷徑。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 45,
      "sourceShot": "#045",
      "start": 195.712,
      "end": 200.412,
      "text": "第三章，掌握好的開場，就是成功的一半以上。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 46,
      "sourceShot": "#046",
      "start": 200.412,
      "end": 204.612,
      "text": "初次見面的最初三十秒，決定了第一印象。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 47,
      "sourceShot": "#047",
      "start": 204.612,
      "end": 209.537,
      "text": "韓女士在國稅局等候時，與身旁的女士白目寒暄。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 48,
      "sourceShot": "#048",
      "start": 209.537,
      "end": 214.262,
      "text": "得知對方來辦離婚，她不經思考便心直口快踩雷。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 49,
      "sourceShot": "#049",
      "start": 214.262,
      "end": 218.762,
      "text": "這導致氣氛極度尷尬，對方臉色大變立刻離去。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 50,
      "sourceShot": "#050",
      "start": 218.762,
      "end": 223.337,
      "text": "柴契爾夫人就是刻意練深沉聲音，才贏得選民。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 51,
      "sourceShot": "#051",
      "start": 223.337,
      "end": 227.787,
      "text": "握手的靈魂在於眼神接觸，而不是單純的力道。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 52,
      "sourceShot": "#052",
      "start": 227.787,
      "end": 232.237,
      "text": "稱謂用錯就是災難，讚美配飾最不容易出錯。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 53,
      "sourceShot": "#053",
      "start": 232.237,
      "end": 237.012,
      "text": "在聚會上，大方讚美，是快速破冰的絕佳技巧。",
      "section": "2. 第一章至第三章"
    },
    {
      "id": 54,
      "sourceShot": "#054",
      "start": 237.012,
      "end": 241.787,
      "text": "第四章，說話只說三分，點到為止反而更有分量。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 55,
      "sourceShot": "#055",
      "start": 241.787,
      "end": 246.55,
      "text": "話說得太滿，承諾太絕對，往往讓自己沒退路。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 56,
      "sourceShot": "#056",
      "start": 246.55,
      "end": 250.562,
      "text": "批評他人之前，必須先給對方戴高帽子。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 57,
      "sourceShot": "#057",
      "start": 250.562,
      "end": 255.337,
      "text": "當你想反駁時，先肯定優點，再溫和給予建議。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 58,
      "sourceShot": "#058",
      "start": 255.337,
      "end": 259.587,
      "text": "提出不同意見時要繞圈子說，用商量的口吻。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 59,
      "sourceShot": "#059",
      "start": 259.587,
      "end": 264.487,
      "text": "作家二月河生病拒絕採訪，記者不放棄繞圈子邀請。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 60,
      "sourceShot": "#060",
      "start": 264.487,
      "end": 269.725,
      "text": "記者不提採訪，只聊身體和健身，最終打動二月河。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 61,
      "sourceShot": "#061",
      "start": 269.725,
      "end": 273.925,
      "text": "在爭辯中，吵贏了往往意味著關係徹底疏遠。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 62,
      "sourceShot": "#062",
      "start": 273.925,
      "end": 278.25,
      "text": "把無謂的口舌勝利讓給對方，才是成熟的智者。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 63,
      "sourceShot": "#063",
      "start": 278.25,
      "end": 282.937,
      "text": "第五章，將陌生人變成朋友的絕招在於專注傾聽。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 64,
      "sourceShot": "#064",
      "start": 282.937,
      "end": 287.575,
      "text": "口才不是你聊個不停，而是專注聽完對方說法。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 65,
      "sourceShot": "#065",
      "start": 287.575,
      "end": 291.964,
      "text": "學會承認「不知道」，反而能給對方表現機會。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 66,
      "sourceShot": "#066",
      "start": 291.964,
      "end": 296.264,
      "text": "不要一開口就說「不對」，用認同包裝否定。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 67,
      "sourceShot": "#067",
      "start": 296.264,
      "end": 301.226,
      "text": "只要你會提問、拋球，話題不深也能延續熱度。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 68,
      "sourceShot": "#068",
      "start": 301.226,
      "end": 306.476,
      "text": "多問「你覺得呢？」，讓對方成為對話的主角。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 69,
      "sourceShot": "#069",
      "start": 306.476,
      "end": 310.976,
      "text": "避開薪水、婚姻、宗教與政治等隱私雷區。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 70,
      "sourceShot": "#070",
      "start": 310.976,
      "end": 316.114,
      "text": "第六章，化解生活尷尬和冷場，自嘲是最高智慧。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 71,
      "sourceShot": "#071",
      "start": 316.114,
      "end": 320.476,
      "text": "忘記名字時不要慌，誠實且慢速介紹自己破冰。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 72,
      "sourceShot": "#072",
      "start": 320.476,
      "end": 325.339,
      "text": "一旦說了蠢話，迅速、真誠地道歉是唯一解藥。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 73,
      "sourceShot": "#073",
      "start": 325.339,
      "end": 330.139,
      "text": "面對兩方爭吵要你評判時，微笑遞台階優雅退場。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 74,
      "sourceShot": "#074",
      "start": 330.139,
      "end": 334.876,
      "text": "朱莉晚年發福遭媒體刁難，自嘲驚豔了整個全場。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 75,
      "sourceShot": "#075",
      "start": 334.876,
      "end": 339.276,
      "text": "自嘲是最高級的幽默，也是最溫暖的安全閥。",
      "section": "3. 第四章至第六章"
    },
    {
      "id": 76,
      "sourceShot": "#076",
      "start": 339.276,
      "end": 344.176,
      "text": "第七章，說話的分寸，是談判桌上的尊貴防線。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 77,
      "sourceShot": "#077",
      "start": 344.176,
      "end": 348.626,
      "text": "開玩笑的前提是，必須雙方都覺得好笑才行。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 78,
      "sourceShot": "#078",
      "start": 348.626,
      "end": 353.251,
      "text": "別人的自嘲是他人的謙遜，旁人絕不能隨意附和。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 79,
      "sourceShot": "#079",
      "start": 353.251,
      "end": 358.026,
      "text": "讚美必須點到為止，過度的虛美聽起來極像反諷。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 80,
      "sourceShot": "#080",
      "start": 358.026,
      "end": 362.901,
      "text": "戒除有害口頭禪，在發言前刻意減慢語速留白。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 81,
      "sourceShot": "#081",
      "start": 362.901,
      "end": 367.526,
      "text": "不打聽隱私、守住秘密，是贏得信任的基礎。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 82,
      "sourceShot": "#082",
      "start": 367.526,
      "end": 372.426,
      "text": "第八章，公司和社團開會，說什麼才容易被接受。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 83,
      "sourceShot": "#083",
      "start": 372.426,
      "end": 376.864,
      "text": "在公司或團體中，只會默默做事很難被看見。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 84,
      "sourceShot": "#084",
      "start": 376.864,
      "end": 381.539,
      "text": "主動且得體向主管匯報工作，是生存的必修課。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 85,
      "sourceShot": "#085",
      "start": 381.539,
      "end": 386.414,
      "text": "匯報要結論先行、條理清晰，展現組織能力。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 86,
      "sourceShot": "#086",
      "start": 386.414,
      "end": 390.814,
      "text": "勝美與Andy激烈爭辯，吵贏了卻被迫離職。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 87,
      "sourceShot": "#087",
      "start": 390.814,
      "end": 395.201,
      "text": "在話裡溫和劃定界限，就不會被當成濫好人。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 88,
      "sourceShot": "#088",
      "start": 395.201,
      "end": 399.814,
      "text": "不發牢騷，只提建設性方案，才能贏得支持。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 89,
      "sourceShot": "#089",
      "start": 399.814,
      "end": 404.439,
      "text": "第九章，用對心機，巧妙地去改變別人的潛意識。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 90,
      "sourceShot": "#090",
      "start": 404.439,
      "end": 409.201,
      "text": "訊息和電話不是任性工具，必須充分尊重時間。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 91,
      "sourceShot": "#091",
      "start": 409.201,
      "end": 413.826,
      "text": "說服的關鍵是站在對方的立場，包裝實質利益。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 92,
      "sourceShot": "#092",
      "start": 413.826,
      "end": 418.676,
      "text": "善用引導式提問，先引導對方在交談中說「是」。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 93,
      "sourceShot": "#093",
      "start": 418.676,
      "end": 423.326,
      "text": "引導對方相信，那本來就是他自己的明智想法。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 94,
      "sourceShot": "#094",
      "start": 423.326,
      "end": 427.964,
      "text": "面對被拒絕時，要展現出大度且成熟的態度。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 95,
      "sourceShot": "#095",
      "start": 427.964,
      "end": 432.301,
      "text": "第十章，不著痕跡地抓住所有關鍵的表現機會。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 96,
      "sourceShot": "#096",
      "start": 432.301,
      "end": 436.814,
      "text": "在開會時保持沉默，會釋放出你沒想法的訊號。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 97,
      "sourceShot": "#097",
      "start": 436.814,
      "end": 441.376,
      "text": "其實會前與會後的非正式溝通，往往決定成敗。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 98,
      "sourceShot": "#098",
      "start": 441.376,
      "end": 446.076,
      "text": "發言要在專業內容中，注入適度的熱切與熱情。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 99,
      "sourceShot": "#099",
      "start": 446.076,
      "end": 450.739,
      "text": "給出一個強而有力的結尾，明確指出下一步行動。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 100,
      "sourceShot": "#100",
      "start": 450.739,
      "end": 455.251,
      "text": "面對會議故意挑釁的人，保持微笑並優雅轉移。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 101,
      "sourceShot": "#101",
      "start": 455.251,
      "end": 459.726,
      "text": "在該發光的舞台上沉默，是對才華最大的荒廢。",
      "section": "4. 第七章至第十章"
    },
    {
      "id": 102,
      "sourceShot": "#102",
      "start": 459.726,
      "end": 464.714,
      "text": "第十一章，九九％的人不懂如何和親近家人表達。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 103,
      "sourceShot": "#103",
      "start": 464.714,
      "end": 469.251,
      "text": "我們常對客戶客氣，卻對最親近的家人不耐煩。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 104,
      "sourceShot": "#104",
      "start": 469.251,
      "end": 473.576,
      "text": "家庭不是講理的法庭，而是講愛的情感歸宿。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 105,
      "sourceShot": "#105",
      "start": 473.576,
      "end": 477.939,
      "text": "與家人溝通要溫火慢燉，一點一滴分享感受。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 106,
      "sourceShot": "#106",
      "start": 477.939,
      "end": 482.701,
      "text": "不要用高期待逼迫孩子，關心孩子的心情與生活。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 107,
      "sourceShot": "#107",
      "start": 482.701,
      "end": 487.226,
      "text": "家人的傾訴往往只想被聽見，而非尋求對錯。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 108,
      "sourceShot": "#108",
      "start": 487.226,
      "end": 492.064,
      "text": "每天進家門前，強迫自己做好角色切換三秒。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 109,
      "sourceShot": "#109",
      "start": 492.064,
      "end": 496.576,
      "text": "第十二章，談完戀愛之後，我們到底該談些什麼。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 110,
      "sourceShot": "#110",
      "start": 496.576,
      "end": 501.089,
      "text": "戀愛過後，咄咄逼人的表達絕對要不到幸福。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 111,
      "sourceShot": "#111",
      "start": 501.089,
      "end": 505.426,
      "text": "肯定你的愛人，他才會長成你理想中的樣子。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 112,
      "sourceShot": "#112",
      "start": 505.426,
      "end": 510.326,
      "text": "爭吵時避免人身攻擊，主動喊停、大度示弱。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 113,
      "sourceShot": "#113",
      "start": 510.326,
      "end": 514.751,
      "text": "在親密關係中，要永久戒除「你總是」等詞彙。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 114,
      "sourceShot": "#114",
      "start": 514.751,
      "end": 519.014,
      "text": "偶爾真誠且善意的謊言，能避免不必要的摩擦。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 115,
      "sourceShot": "#115",
      "start": 519.014,
      "end": 523.589,
      "text": "吵贏了爭辯卻輸了感情，是世界上最愚蠢的事。",
      "section": "5. 第十一章至第十二章"
    },
    {
      "id": 116,
      "sourceShot": "#116",
      "start": 523.589,
      "end": 528.039,
      "text": "看完這十二個章節，你是不是也有很深的觸動？",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 117,
      "sourceShot": "#117",
      "start": 528.039,
      "end": 532.814,
      "text": "表達力不是口才炫技，而是理解與尊重的修行。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 118,
      "sourceShot": "#118",
      "start": 532.814,
      "end": 537.389,
      "text": "今天，我為大家規劃了可立即實踐的三項行動。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 119,
      "sourceShot": "#119",
      "start": 537.389,
      "end": 542.264,
      "text": "第一，進門前三秒，把工作壓力和緊繃留在門外。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 120,
      "sourceShot": "#120",
      "start": 542.264,
      "end": 547.139,
      "text": "第二，職場結論先行，批評前先肯定對方的優點。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 121,
      "sourceShot": "#121",
      "start": 547.139,
      "end": 552.426,
      "text": "第三，每會必主動發言，永久戒除「你總是」指責。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 122,
      "sourceShot": "#122",
      "start": 552.426,
      "end": 557.164,
      "text": "說話對了，事就成了，我們在溫暖的表達中成長。",
      "section": "6. 全書統整與結語"
    },
    {
      "id": 123,
      "sourceShot": "#123",
      "start": 557.164,
      "end": 560.801,
      "text": "謝謝大家，我們下期讀書會再見。",
      "section": "6. 全書統整與結語"
    }
  ]
};
