const captionAt=(scene,time)=>{const at=Math.round(Number(time)*1000)/1000;const lines=scene.captionLines?.length?scene.captionLines:[{text:scene.caption||scene.text,start:scene.start,end:scene.end}];return lines.find(line=>at>=line.start&&at<line.end)?.text||lines.at(-1).text};
const data=window.BLACK_SWAN_SCENES;
const chapterData=window.BLACK_SWAN_CHAPTERS;
const audio=document.querySelector('#audio'),img=document.querySelector('#scene-image'),sub=document.querySelector('#subtitle'),intro=document.querySelector('#chapter-intro'),seek=document.querySelector('#seek'),stage=document.querySelector('#stage'),counter=document.querySelector('#counter'),now=document.querySelector('#now'),length=document.querySelector('#length'),toggle=document.querySelector('#toggle'),debug=document.querySelector('#debug'),debugText=document.querySelector('#debug-text'),scenes=data.scenes;
let active=null,raf=0,dragging=false,pendingSeek=null;
const findScene=value=>{const t=Math.round(Number(value)*1000)/1000;let l=0,h=scenes.length-1;while(l<=h){const m=(l+h)>>1,s=scenes[m],start=Math.round(s.start*1000)/1000,end=Math.round(s.end*1000)/1000;if(t<start)h=m-1;else if(t>=end)l=m+1;else return s}return t>=Math.round(scenes.at(-1).end*1000)/1000?scenes.at(-1):scenes[0]};
const fmt=t=>{const n=Math.max(0,Math.floor(t)),m=Math.floor(n/60);return String(m).padStart(2,'0')+':'+String(n%60).padStart(2,'0')};
const maxTime=()=>Number.isFinite(audio.duration)&&audio.duration>0?audio.duration:data.duration;
function syncFromMasterTime(){const t=Number.isFinite(audio.currentTime)?audio.currentTime:0,s=findScene(t);if(!dragging)seek.value=String(t);now.textContent=fmt(dragging?findScene(Number(seek.value)).start:t);length.textContent=fmt(maxTime());sub.textContent=captionAt(s,t);if(s!==active){active=s;img.src=s.image;img.alt='第 '+s.sceneNo+' 幕';counter.textContent='第 '+s.sceneNo+' / '+scenes.length+' 幕';stage.className='stage motion-'+((s.sceneNo-1)%6)}const c=chapterData.chapters.find(x=>x.id===s.chapterId);intro.textContent=c?.title||s.chapterTitle;intro.classList.toggle('show',Boolean(c&&t-c.start<2.5));document.querySelectorAll('#chapter-list button').forEach(b=>b.classList.toggle('active',b.dataset.id===s.chapterId));if(debug.classList.contains('show'))debugText.textContent=' | Master '+t.toFixed(2)+'s | Scene '+s.sceneNo+' '+s.start.toFixed(2)+'–'+s.end.toFixed(2)+' | '+(audio.paused?'paused':'playing')}
function frame(){syncFromMasterTime();if(!audio.paused)raf=requestAnimationFrame(frame);else raf=0}
function applySeek(value){const raw=Math.min(Math.max(0,Number(value)||0),maxTime()),target=findScene(raw).start;if(audio.readyState<1){pendingSeek=target;audio.load();return}audio.currentTime=target;syncFromMasterTime()}
function seekTo(value){dragging=false;applySeek(value)}
function commitSlider(){dragging=false;applySeek(Number(seek.value))}
toggle.onclick=()=>audio.paused?audio.play():audio.pause();document.querySelector('#back').onclick=()=>seekTo(audio.currentTime-10);document.querySelector('#next').onclick=()=>seekTo(audio.currentTime+10);
seek.addEventListener('pointerdown',()=>{dragging=true});seek.addEventListener('input',()=>{dragging=true;now.textContent=fmt(findScene(Number(seek.value)).start)});seek.addEventListener('change',commitSlider);seek.addEventListener('keyup',e=>{if(e.key.startsWith('Arrow')||e.key==='Home'||e.key==='End')commitSlider()});
for(const c of chapterData.chapters){const b=document.createElement('button');b.type='button';b.dataset.id=c.id;b.textContent=c.title;b.addEventListener('click',()=>seekTo(c.start));document.querySelector('#chapter-list').append(b)}
audio.onplay=()=>{toggle.textContent='暫停';if(!raf)raf=requestAnimationFrame(frame)};audio.onpause=()=>{toggle.textContent='播放';syncFromMasterTime()};audio.ontimeupdate=syncFromMasterTime;audio.onloadedmetadata=()=>{if(pendingSeek!==null){const target=pendingSeek;pendingSeek=null;applySeek(target)}syncFromMasterTime()};audio.onseeked=syncFromMasterTime;if(new URLSearchParams(location.search).has('debug'))debug.classList.add('show');syncFromMasterTime();
