window.READING_DATA = {
  "project": {
    "title": "【被遺忘的大多數】自然旁白響應式動態閱讀版",
    "duration": 612.557,
    "imageCount": 144,
    "imageInterval": 4.254,
    "audioAvailable": true,
    "audioStatus": "已接入外部 TTS 實際旁白，音檔長度 10 分 12.56 秒；圖片依實際音檔平均分配。",
    "animationRule": "同一段落固定運鏡方向，圖片以雙圖淡入淡出銜接，避免黑畫面與運鏡突然歸零。左上角段落標題在該段期間持續顯示；版面支援桌機、手機直立與橫放。",
    "audioFile": "audio/narration-zhTW.mp3",
    "audioSubtitleFile": "audio/narration-zhTW.srt",
    "audioVoice": "zh-TW-YunJheNeural",
    "audioRate": "-30%"
  },
  "captions": [
    {
      "id": 1,
      "start": 0.1,
      "end": 3.046,
      "text": "你敢相信嗎？",
      "tone": "語氣帶有諷刺的驚嘆"
    },
    {
      "id": 2,
      "start": 2.996,
      "end": 10.639,
      "text": "這座島嶼，2024年的人均GDP正式突破了三萬五千美金。",
      "tone": "語氣帶有諷刺的驚嘆"
    },
    {
      "id": 3,
      "start": 10.639,
      "end": 16.782,
      "text": "我們超越了日本，連續三年把韓國踩在腳下。",
      "tone": "語氣帶有諷刺的驚嘆"
    },
    {
      "id": 4,
      "start": 16.782,
      "end": 23.728,
      "text": "一間台積電的市值，就打敗了韓國前十大企業的總和。",
      "tone": "語氣帶有諷刺的驚嘆"
    },
    {
      "id": 5,
      "start": 23.728,
      "end": 29.067,
      "text": "聽起來，我們站在世界之巔，對吧？",
      "tone": "語氣轉為低沉、質疑"
    },
    {
      "id": 6,
      "start": 29.167,
      "end": 33.274,
      "text": "但歡迎來到真實世界。",
      "tone": "語氣轉為低沉、質疑"
    },
    {
      "id": 7,
      "start": 33.224,
      "end": 38.581,
      "text": "這裡的實質薪資，倒退了整整二十年。",
      "tone": "依劇情自然轉折"
    },
    {
      "id": 8,
      "start": 38.581,
      "end": 47.009,
      "text": "現在年輕人領到的薪水，購買力跟你出生的那一年，幾乎一模一樣。",
      "tone": "依劇情自然轉折"
    },
    {
      "id": 9,
      "start": 47.009,
      "end": 53.599,
      "text": "全台灣有超過三百萬勞工，月薪連四萬塊都不到。",
      "tone": "依劇情自然轉折"
    },
    {
      "id": 10,
      "start": 53.599,
      "end": 59.456,
      "text": "數字不會騙人，但有人正在用數字騙你。",
      "tone": "語氣加重"
    },
    {
      "id": 11,
      "start": 59.556,
      "end": 66.609,
      "text": "那些漂亮的GDP成長，到底，跟你我有什麼關係？",
      "tone": "語氣加重"
    },
    {
      "id": 12,
      "start": 66.559,
      "end": 74.738,
      "text": "走進台北東區的精品咖啡館，一杯手沖要兩百，一塊蛋糕一百六。",
      "tone": "第十名：200塊的絕望"
    },
    {
      "id": 13,
      "start": 74.738,
      "end": 82.577,
      "text": "年輕人拿著最新款的iPhone，拍下照片，配上「好好生活」。",
      "tone": "第十名：200塊的絕望"
    },
    {
      "id": 14,
      "start": 82.577,
      "end": 85.863,
      "text": "你以為這是優渥？",
      "tone": "第十名：200塊的絕望"
    },
    {
      "id": 15,
      "start": 85.863,
      "end": 91.541,
      "text": "錯了，這恰恰是因為窮到骨子裡的絕望。",
      "tone": "第十名：200塊的絕望"
    },
    {
      "id": 16,
      "start": 91.641,
      "end": 102.533,
      "text": "現在年輕人流傳一句話：「反正存錢也買不起房，不如把錢花掉，至少今天活得開心。",
      "tone": "語氣帶點無奈的嘲諷"
    },
    {
      "id": 17,
      "start": 102.483,
      "end": 106.287,
      "text": "」這叫「絕望消費」。",
      "tone": "語氣帶點無奈的嘲諷"
    },
    {
      "id": 18,
      "start": 106.287,
      "end": 114.091,
      "text": "當奮鬥改變不了命運，這口精品咖啡，就成了唯一的止痛藥。",
      "tone": "語氣帶點無奈的嘲諷"
    },
    {
      "id": 19,
      "start": 114.091,
      "end": 123.823,
      "text": "而同一時間，三條街外，七十歲的阿婆，正在為了一把蔥，爭得面紅耳赤。",
      "tone": "語氣帶點無奈的嘲諷"
    },
    {
      "id": 20,
      "start": 123.823,
      "end": 127.43,
      "text": "接下來這個更魔幻。",
      "tone": "第九名：外勞都比你有錢"
    },
    {
      "id": 21,
      "start": 127.53,
      "end": 136.744,
      "text": "2024年，台灣工地的泰國移工，月薪可以拿到六到八萬，還包吃包住。",
      "tone": "第九名：外勞都比你有錢"
    },
    {
      "id": 22,
      "start": 136.694,
      "end": 144.855,
      "text": "而同一個工地的台灣大學畢業助理，起薪三萬多，還得自己付房租。",
      "tone": "第九名：外勞都比你有錢"
    },
    {
      "id": 23,
      "start": 144.855,
      "end": 153.033,
      "text": "科技業大舉引進菲律賓、印度工程師，起薪直接七萬加補貼。",
      "tone": "語氣提高，帶著荒謬感"
    },
    {
      "id": 24,
      "start": 153.033,
      "end": 160.355,
      "text": "而進不了台積電的本地理科碩士，只能去系統廠領四萬五。",
      "tone": "語氣提高，帶著荒謬感"
    },
    {
      "id": 25,
      "start": 160.355,
      "end": 165.837,
      "text": "台灣年輕人的起薪，已經被外勞超車了。",
      "tone": "語氣提高，帶著荒謬感"
    },
    {
      "id": 26,
      "start": 165.937,
      "end": 176.222,
      "text": "這不是歧視，這是警訊，除了半導體，我們幾乎沒有其他產業能帶動薪資成長。",
      "tone": "語氣提高，帶著荒謬感"
    },
    {
      "id": 27,
      "start": 176.172,
      "end": 183.726,
      "text": "台灣創下一個全球第一的紀錄：大學錄取率突破百分之百。",
      "tone": "第八名：學歷是最大的騙局"
    },
    {
      "id": 28,
      "start": 183.726,
      "end": 189.779,
      "text": "只要會呼吸、會寫字，就有大學讀。",
      "tone": "第八名：學歷是最大的騙局"
    },
    {
      "id": 29,
      "start": 189.779,
      "end": 195.672,
      "text": "但當人人都是大學生，文憑就成了廢紙。",
      "tone": "第八名：學歷是最大的騙局"
    },
    {
      "id": 30,
      "start": 195.672,
      "end": 204.333,
      "text": "現在碩士畢業，最好的工作可能是去超商當儲備店長，月薪三萬三。",
      "tone": "語氣帶著諷刺的計算"
    },
    {
      "id": 31,
      "start": 204.433,
      "end": 210.468,
      "text": "三十年前，高中畢業生起薪就有兩萬八。",
      "tone": "語氣帶著諷刺的計算"
    },
    {
      "id": 32,
      "start": 210.418,
      "end": 216.258,
      "text": "你多讀了七年書，價值竟然只多了幾千塊？",
      "tone": "語氣帶著諷刺的計算"
    },
    {
      "id": 33,
      "start": 216.258,
      "end": 224.133,
      "text": "家裡砸了兩百萬供你讀書，畢業後不吃不喝要四十七個月才能還清。",
      "tone": "語氣帶著諷刺的計算"
    },
    {
      "id": 34,
      "start": 224.133,
      "end": 228.579,
      "text": "這筆帳，怎麼算都算不平。",
      "tone": "語氣帶著諷刺的計算"
    },
    {
      "id": 35,
      "start": 228.579,
      "end": 241.008,
      "text": "在台北，一間沒廚房、沒陽台、廁所還要側身進去的七坪套房，月租一萬五，這還是佛心價。",
      "tone": "第七名：房租在吃你的未來"
    },
    {
      "id": 36,
      "start": 241.108,
      "end": 248.197,
      "text": "而台北三十歲以下年輕人的薪資中位數，只有三萬六。",
      "tone": "第七名：房租在吃你的未來"
    },
    {
      "id": 37,
      "start": 248.147,
      "end": 257.861,
      "text": "扣掉房租、吃飯、交通，一個月只剩六千塊，你要拿來應付看病和紅包。",
      "tone": "語氣越來越沉重"
    },
    {
      "id": 38,
      "start": 257.861,
      "end": 264.29,
      "text": "你攢一輩子，連個停車位的頭期款都湊不齊。",
      "tone": "語氣越來越沉重"
    },
    {
      "id": 39,
      "start": 264.29,
      "end": 266.95,
      "text": "去中南部？",
      "tone": "語氣越來越沉重"
    },
    {
      "id": 40,
      "start": 266.95,
      "end": 273.647,
      "text": "房價是便宜了，但你的薪水，也會跟著對半砍。",
      "tone": "語氣越來越沉重"
    },
    {
      "id": 41,
      "start": 273.747,
      "end": 277.568,
      "text": "這是一個無解的死局。",
      "tone": "語氣越來越沉重"
    },
    {
      "id": 42,
      "start": 277.518,
      "end": 287.804,
      "text": "2004年，一個排骨便當六十塊，2024年，一百二十塊，物價翻了一倍。",
      "tone": "第六名：物價飛漲與薪水凍結"
    },
    {
      "id": 43,
      "start": 287.804,
      "end": 295.732,
      "text": "但大學起薪，從兩萬八只漲到三萬二，漲幅僅僅百分之十四。",
      "tone": "第六名：物價飛漲與薪水凍結"
    },
    {
      "id": 44,
      "start": 295.732,
      "end": 300.072,
      "text": "剩下的百分之八十六跑去哪了？",
      "tone": "語氣帶著憤怒的質問"
    },
    {
      "id": 45,
      "start": 300.072,
      "end": 308.232,
      "text": "流進了企業利潤、流進了股東口袋，變成了那漂亮的GDP數字。",
      "tone": "語氣帶著憤怒的質問"
    },
    {
      "id": 46,
      "start": 308.332,
      "end": 319.332,
      "text": "你就像在一艘下沉的船上，薪水沒漲，但水電、健保、房租，每一樣都在漲。",
      "tone": "語氣帶著憤怒的質問"
    },
    {
      "id": 47,
      "start": 319.282,
      "end": 325.674,
      "text": "水位越來越高，你的頭，離水面越來越近。",
      "tone": "語氣帶著憤怒的質問"
    },
    {
      "id": 48,
      "start": 325.674,
      "end": 333.532,
      "text": "官方統計，台灣工時全球第四高，年均超過兩千小時。",
      "tone": "第五名：隱形的LINE加班"
    },
    {
      "id": 49,
      "start": 333.532,
      "end": 339.21,
      "text": "但真實數字更恐怖，因為還有「LINE加班」。",
      "tone": "第五名：隱形的LINE加班"
    },
    {
      "id": 50,
      "start": 339.21,
      "end": 348.603,
      "text": "下班回家躺在沙發上，主管一則訊息過來：「數據更新一下，謝謝。",
      "tone": "語氣轉為無奈與疲憊"
    },
    {
      "id": 51,
      "start": 348.703,
      "end": 353.274,
      "text": "」沒有加班費，你敢不回嗎？",
      "tone": "語氣轉為無奈與疲憊"
    },
    {
      "id": 52,
      "start": 353.224,
      "end": 357.974,
      "text": "你不回，年終考核就拿叉。",
      "tone": "語氣轉為無奈與疲憊"
    },
    {
      "id": 53,
      "start": 357.974,
      "end": 364.92,
      "text": "這種隱形加班，每年至少吞噬掉台灣勞工兩千億的薪資。",
      "tone": "語氣轉為無奈與疲憊"
    },
    {
      "id": 54,
      "start": 364.92,
      "end": 373.028,
      "text": "企業用「責任感」當話術，讓你即便累垮，也要為「公司這個家」賣命。",
      "tone": "語氣轉為無奈與疲憊"
    },
    {
      "id": 55,
      "start": 373.028,
      "end": 381.188,
      "text": "台積電入職五年的工程師，2023年分紅加獎金大約三百萬。",
      "tone": "第四名：財富分配的畸形劇本"
    },
    {
      "id": 56,
      "start": 381.288,
      "end": 389.395,
      "text": "這是一個在餐廳端盤子的年輕人，要工作六年半才拿得到的錢。",
      "tone": "第四名：財富分配的畸形劇本"
    },
    {
      "id": 57,
      "start": 389.345,
      "end": 396.13,
      "text": "台灣的財富不是創造得少，而是分配得極其畸形。",
      "tone": "語氣變得嚴肅、批判"
    },
    {
      "id": 58,
      "start": 396.13,
      "end": 404.148,
      "text": "半導體業拿走了社會最多的利潤，但受益的人口，不到百分之三。",
      "tone": "語氣變得嚴肅、批判"
    },
    {
      "id": 59,
      "start": 404.148,
      "end": 416.684,
      "text": "剩下九成七的人，在傳統產業和服務業拼命，他們創造的GDP一樣真實，但分到的，連湯渣都算不上。",
      "tone": "語氣變得嚴肅、批判"
    },
    {
      "id": 60,
      "start": 416.684,
      "end": 426.023,
      "text": "在台灣，如果你高中選了文組，你的人生路徑，就被砍掉了百分之八十。",
      "tone": "第三名：文組的經濟死刑"
    },
    {
      "id": 61,
      "start": 426.123,
      "end": 434.908,
      "text": "中文碩士起薪三萬，機械學士進台積電年薪破百萬，差距是三倍。",
      "tone": "第三名：文組的經濟死刑"
    },
    {
      "id": 62,
      "start": 434.858,
      "end": 443.34,
      "text": "這導致了殘酷的篩選：考不上理工科的人，在階級上被永久降等。",
      "tone": "語氣帶著憐憫與不捨"
    },
    {
      "id": 63,
      "start": 443.34,
      "end": 449.126,
      "text": "我們的社會只需要工程師，不需要詩人。",
      "tone": "語氣帶著憐憫與不捨"
    },
    {
      "id": 64,
      "start": 449.126,
      "end": 458.448,
      "text": "難道愛文學、愛藝術的孩子，唯一的錯，就是出生在一個只看數據的社會嗎？",
      "tone": "語氣帶著憐憫與不捨"
    },
    {
      "id": 65,
      "start": 458.448,
      "end": 468.18,
      "text": "我們來算一題小學數學：台北一間中古公寓兩千五百萬，房貸每月要還七萬六。",
      "tone": "第二名：買房是數學上的不可能"
    },
    {
      "id": 66,
      "start": 468.28,
      "end": 474.619,
      "text": "但三十到四十歲人的月薪中位數，只有五萬二。",
      "tone": "第二名：買房是數學上的不可能"
    },
    {
      "id": 67,
      "start": 474.569,
      "end": 481.694,
      "text": "你的薪水連房貸都還不起，更別提那五百萬的頭期款。",
      "tone": "第二名：買房是數學上的不可能"
    },
    {
      "id": 68,
      "start": 481.694,
      "end": 486.087,
      "text": "所以年輕人選擇「躺平」。",
      "tone": "語氣變為冷酷的理性"
    },
    {
      "id": 69,
      "start": 486.087,
      "end": 494.408,
      "text": "這不是懶惰，而是在算完所有可能性之後，唯一剩下的理性結論。",
      "tone": "語氣變為冷酷的理性"
    },
    {
      "id": 70,
      "start": 494.408,
      "end": 503.962,
      "text": "2024年台灣出生率全球倒數第一，因為大家發現，連養活自己都快沒能力了。",
      "tone": "語氣變為冷酷的理性"
    },
    {
      "id": 71,
      "start": 504.062,
      "end": 511.437,
      "text": "最後，這是台灣最醜陋的傷疤：兩個完全平行的世界。",
      "tone": "第一名：科技權貴與社畜的階級折疊"
    },
    {
      "id": 72,
      "start": 511.387,
      "end": 520.208,
      "text": "一邊，住在重劃區豪宅，開著特斯拉，討論小孩去美國參加夏令營。",
      "tone": "第一名：科技權貴與社畜的階級折疊"
    },
    {
      "id": 73,
      "start": 520.208,
      "end": 530.387,
      "text": "另一邊，擠在牆壁爬滿壁癌的40年老屋，騎著15年的機車，晚餐吃八十塊的雞腿飯。",
      "tone": "第一名：科技權貴與社畜的階級折疊"
    },
    {
      "id": 74,
      "start": 530.387,
      "end": 536.262,
      "text": "台積電處長一年的薪水，三千到五千萬。",
      "tone": "語氣沉痛，達到頂點"
    },
    {
      "id": 75,
      "start": 536.262,
      "end": 547.351,
      "text": "那是超商店員，不吃不喝工作一百三十九年——從清朝光緒年間幹到現在，才賺得到的錢。",
      "tone": "語氣沉痛，達到頂點"
    },
    {
      "id": 76,
      "start": 547.451,
      "end": 557.451,
      "text": "他們在同一個路口等紅燈，距離只有一條斑馬線，但階級差距，卻是一整個世紀。",
      "tone": "語氣沉痛，達到頂點"
    },
    {
      "id": 77,
      "start": 557.401,
      "end": 567.901,
      "text": "台灣的悲劇不在於它不富有，而是它太富有，卻把財富，堆在不到百分之三的人身上。",
      "tone": "語氣沉穩、緩慢，帶著力量"
    },
    {
      "id": 78,
      "start": 567.901,
      "end": 572.722,
      "text": "GDP往上走，薪資往底掉。",
      "tone": "語氣沉穩、緩慢，帶著力量"
    },
    {
      "id": 79,
      "start": 572.722,
      "end": 582.079,
      "text": "當全世界都在讚頌這座科技島時，你，卻連下個月的房租都付不出來。",
      "tone": "語氣沉穩、緩慢，帶著力量"
    },
    {
      "id": 80,
      "start": 582.079,
      "end": 591.561,
      "text": "最可怕的不是賺不到錢，而是二十歲的年輕人，已經放棄了對未來的所有想像。",
      "tone": "語氣轉為深切"
    },
    {
      "id": 81,
      "start": 591.661,
      "end": 598.393,
      "text": "如果看完這些你感覺被刺痛了，那代表你還沒有麻木。",
      "tone": "畫面全黑，浮現字幕"
    },
    {
      "id": 82,
      "start": 598.343,
      "end": 605.843,
      "text": "留言告訴我們，這十個怪象中，你，正經歷著哪一個？",
      "tone": "畫面全黑，浮現字幕"
    },
    {
      "id": 83,
      "start": 605.843,
      "end": 612.557,
      "text": "【被遺忘的大多數】 我們，都是繁榮背後的真相。",
      "tone": "最後浮現標題"
    }
  ],
  "timeline": [
    {
      "id": "natural-001",
      "start": 0.0,
      "end": 4.254,
      "time": "00:00",
      "image": "assets/images/scene-001.webp",
      "sourceFullVersionImage": "scene-001-0000.webp",
      "motion": "push",
      "heading": "開場：繁榮悖論",
      "captionId": 1,
      "showHeading": true,
      "visualTopic": "城市天際線",
      "selectionReason": "旁白第 1 段：你敢相信嗎？ → 城市天際線"
    },
    {
      "id": "natural-002",
      "start": 4.254,
      "end": 8.508,
      "time": "00:04",
      "image": "assets/images/scene-002.webp",
      "sourceFullVersionImage": "scene-005.webp",
      "motion": "diagonal",
      "heading": "開場：繁榮悖論",
      "captionId": 2,
      "showHeading": false,
      "visualTopic": "城市天際線",
      "selectionReason": "旁白第 2 段：這座島嶼，2024年的人均GDP正式突破了三萬五千美金。 → 城市天際線"
    },
    {
      "id": "natural-003",
      "start": 8.508,
      "end": 12.762,
      "time": "00:08",
      "image": "assets/images/scene-003.webp",
      "sourceFullVersionImage": "scene-009.webp",
      "motion": "pan-left",
      "heading": "開場：繁榮悖論",
      "captionId": 2,
      "showHeading": false,
      "visualTopic": "城市天際線",
      "selectionReason": "旁白第 2 段：這座島嶼，2024年的人均GDP正式突破了三萬五千美金。 → 城市天際線"
    },
    {
      "id": "natural-004",
      "start": 12.762,
      "end": 17.016,
      "time": "00:12",
      "image": "assets/images/scene-004.webp",
      "sourceFullVersionImage": "scene-001-0000.webp",
      "motion": "push",
      "heading": "開場：繁榮悖論",
      "captionId": 3,
      "showHeading": false,
      "visualTopic": "城市天際線",
      "selectionReason": "旁白第 3 段：我們超越了日本，連續三年把韓國踩在腳下。 → 城市天際線"
    },
    {
      "id": "natural-005",
      "start": 17.016,
      "end": 21.27,
      "time": "00:17",
      "image": "assets/images/scene-005.webp",
      "sourceFullVersionImage": "scene-005.webp",
      "motion": "diagonal",
      "heading": "開場：繁榮悖論",
      "captionId": 4,
      "showHeading": false,
      "visualTopic": "城市天際線",
      "selectionReason": "旁白第 4 段：一間台積電的市值，就打敗了韓國前十大企業的總和。 → 城市天際線"
    },
    {
      "id": "natural-006",
      "start": 21.27,
      "end": 25.524,
      "time": "00:21",
      "image": "assets/images/scene-006.webp",
      "sourceFullVersionImage": "scene-009.webp",
      "motion": "pan-left",
      "heading": "開場：繁榮悖論",
      "captionId": 4,
      "showHeading": false,
      "visualTopic": "城市天際線",
      "selectionReason": "旁白第 4 段：一間台積電的市值，就打敗了韓國前十大企業的總和。 → 城市天際線"
    },
    {
      "id": "natural-007",
      "start": 25.524,
      "end": 29.778,
      "time": "00:25",
      "image": "assets/images/scene-007.webp",
      "sourceFullVersionImage": "scene-008.webp",
      "motion": "pull",
      "heading": "開場：繁榮悖論",
      "captionId": 5,
      "showHeading": false,
      "visualTopic": "繁華街頭凝視城市",
      "selectionReason": "旁白第 5 段：聽起來，我們站在世界之巔，對吧？ → 繁華街頭凝視城市"
    },
    {
      "id": "natural-008",
      "start": 29.778,
      "end": 34.032,
      "time": "00:29",
      "image": "assets/images/scene-008.webp",
      "sourceFullVersionImage": "scene-004.webp",
      "motion": "pan-left",
      "heading": "開場：繁榮悖論",
      "captionId": 6,
      "showHeading": false,
      "visualTopic": "繁華街頭凝視城市",
      "selectionReason": "旁白第 6 段：但歡迎來到真實世界。 → 繁華街頭凝視城市"
    },
    {
      "id": "natural-009",
      "start": 34.032,
      "end": 38.286,
      "time": "00:34",
      "image": "assets/images/scene-009.webp",
      "sourceFullVersionImage": "scene-003-0010.webp",
      "motion": "pull",
      "heading": "開場：繁榮悖論",
      "captionId": 7,
      "showHeading": false,
      "visualTopic": "老舊公寓與鐵皮屋",
      "selectionReason": "旁白第 7 段：這裡的實質薪資，倒退了整整二十年。 → 老舊公寓與鐵皮屋"
    },
    {
      "id": "natural-010",
      "start": 38.286,
      "end": 42.54,
      "time": "00:38",
      "image": "assets/images/scene-010.webp",
      "sourceFullVersionImage": "scene-007.webp",
      "motion": "pan-right",
      "heading": "開場：繁榮悖論",
      "captionId": 8,
      "showHeading": false,
      "visualTopic": "老舊公寓與鐵皮屋",
      "selectionReason": "旁白第 8 段：現在年輕人領到的薪水，購買力跟你出生的那一年，幾乎一模一樣。 → 老舊公寓與鐵皮屋"
    },
    {
      "id": "natural-011",
      "start": 42.54,
      "end": 46.794,
      "time": "00:42",
      "image": "assets/images/scene-011.webp",
      "sourceFullVersionImage": "scene-003-0010.webp",
      "motion": "pull",
      "heading": "開場：繁榮悖論",
      "captionId": 8,
      "showHeading": false,
      "visualTopic": "老舊公寓與鐵皮屋",
      "selectionReason": "旁白第 8 段：現在年輕人領到的薪水，購買力跟你出生的那一年，幾乎一模一樣。 → 老舊公寓與鐵皮屋"
    },
    {
      "id": "natural-012",
      "start": 46.794,
      "end": 51.048,
      "time": "00:46",
      "image": "assets/images/scene-012.webp",
      "sourceFullVersionImage": "scene-007.webp",
      "motion": "pan-right",
      "heading": "開場：繁榮悖論",
      "captionId": 9,
      "showHeading": false,
      "visualTopic": "老舊公寓與鐵皮屋",
      "selectionReason": "旁白第 9 段：全台灣有超過三百萬勞工，月薪連四萬塊都不到。 → 老舊公寓與鐵皮屋"
    },
    {
      "id": "natural-013",
      "start": 51.048,
      "end": 55.302,
      "time": "00:51",
      "image": "assets/images/scene-013.webp",
      "sourceFullVersionImage": "scene-003-0010.webp",
      "motion": "pull",
      "heading": "開場：繁榮悖論",
      "captionId": 9,
      "showHeading": false,
      "visualTopic": "老舊公寓與鐵皮屋",
      "selectionReason": "旁白第 9 段：全台灣有超過三百萬勞工，月薪連四萬塊都不到。 → 老舊公寓與鐵皮屋"
    },
    {
      "id": "natural-014",
      "start": 55.302,
      "end": 59.556,
      "time": "00:55",
      "image": "assets/images/scene-014.webp",
      "sourceFullVersionImage": "scene-008.webp",
      "motion": "pull",
      "heading": "開場：繁榮悖論",
      "captionId": 10,
      "showHeading": false,
      "visualTopic": "繁華街頭凝視城市",
      "selectionReason": "旁白第 10 段：數字不會騙人，但有人正在用數字騙你。 → 繁華街頭凝視城市"
    },
    {
      "id": "natural-015",
      "start": 59.556,
      "end": 63.81,
      "time": "00:59",
      "image": "assets/images/scene-015.webp",
      "sourceFullVersionImage": "scene-004.webp",
      "motion": "pan-left",
      "heading": "開場：繁榮悖論",
      "captionId": 11,
      "showHeading": false,
      "visualTopic": "繁華街頭凝視城市",
      "selectionReason": "旁白第 11 段：那些漂亮的GDP成長，到底，跟你我有什麼關係？ → 繁華街頭凝視城市"
    },
    {
      "id": "natural-016",
      "start": 63.81,
      "end": 68.064,
      "time": "01:03",
      "image": "assets/images/scene-016.webp",
      "sourceFullVersionImage": "scene-008.webp",
      "motion": "pull",
      "heading": "開場：繁榮悖論",
      "captionId": 11,
      "showHeading": false,
      "visualTopic": "繁華街頭凝視城市",
      "selectionReason": "旁白第 11 段：那些漂亮的GDP成長，到底，跟你我有什麼關係？ → 繁華街頭凝視城市"
    },
    {
      "id": "natural-017",
      "start": 68.064,
      "end": 72.318,
      "time": "01:08",
      "image": "assets/images/scene-017.webp",
      "sourceFullVersionImage": "scene-011.webp",
      "motion": "pan-right",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 12,
      "showHeading": true,
      "visualTopic": "手沖咖啡與蛋糕",
      "selectionReason": "旁白第 12 段：走進台北東區的精品咖啡館，一杯手沖要兩百，一塊蛋糕一百六。 → 手沖咖啡與蛋糕"
    },
    {
      "id": "natural-018",
      "start": 72.318,
      "end": 76.572,
      "time": "01:12",
      "image": "assets/images/scene-018.webp",
      "sourceFullVersionImage": "scene-016.webp",
      "motion": "pan-right",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 12,
      "showHeading": false,
      "visualTopic": "手沖咖啡與蛋糕",
      "selectionReason": "旁白第 12 段：走進台北東區的精品咖啡館，一杯手沖要兩百，一塊蛋糕一百六。 → 手沖咖啡與蛋糕"
    },
    {
      "id": "natural-019",
      "start": 76.572,
      "end": 80.826,
      "time": "01:16",
      "image": "assets/images/scene-019.webp",
      "sourceFullVersionImage": "scene-012.webp",
      "motion": "pull",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 13,
      "showHeading": false,
      "visualTopic": "拍攝咖啡的空洞表情",
      "selectionReason": "旁白第 13 段：年輕人拿著最新款的iPhone，拍下照片，配上「好好生活」。 → 拍攝咖啡的空洞表情"
    },
    {
      "id": "natural-020",
      "start": 80.826,
      "end": 85.08,
      "time": "01:20",
      "image": "assets/images/scene-020.webp",
      "sourceFullVersionImage": "scene-017.webp",
      "motion": "pull",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 14,
      "showHeading": false,
      "visualTopic": "拍攝咖啡的空洞表情",
      "selectionReason": "旁白第 14 段：你以為這是優渥？ → 拍攝咖啡的空洞表情"
    },
    {
      "id": "natural-021",
      "start": 85.08,
      "end": 89.334,
      "time": "01:25",
      "image": "assets/images/scene-021.webp",
      "sourceFullVersionImage": "scene-014.webp",
      "motion": "diagonal",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 15,
      "showHeading": false,
      "visualTopic": "空錢包咖啡館",
      "selectionReason": "旁白第 15 段：錯了，這恰恰是因為窮到骨子裡的絕望。 → 空錢包咖啡館"
    },
    {
      "id": "natural-022",
      "start": 89.334,
      "end": 93.588,
      "time": "01:29",
      "image": "assets/images/scene-022.webp",
      "sourceFullVersionImage": "scene-019.webp",
      "motion": "diagonal",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 15,
      "showHeading": false,
      "visualTopic": "空錢包咖啡館",
      "selectionReason": "旁白第 15 段：錯了，這恰恰是因為窮到骨子裡的絕望。 → 空錢包咖啡館"
    },
    {
      "id": "natural-023",
      "start": 93.588,
      "end": 97.842,
      "time": "01:33",
      "image": "assets/images/scene-023.webp",
      "sourceFullVersionImage": "scene-024.webp",
      "motion": "diagonal",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 16,
      "showHeading": false,
      "visualTopic": "空錢包咖啡館",
      "selectionReason": "旁白第 16 段：現在年輕人流傳一句話：「反正存錢也買不起房，不如把錢花掉，至少今天活得開心。 → 空錢包咖啡館"
    },
    {
      "id": "natural-024",
      "start": 97.842,
      "end": 102.096,
      "time": "01:37",
      "image": "assets/images/scene-024.webp",
      "sourceFullVersionImage": "scene-029.webp",
      "motion": "diagonal",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 16,
      "showHeading": false,
      "visualTopic": "空錢包咖啡館",
      "selectionReason": "旁白第 16 段：現在年輕人流傳一句話：「反正存錢也買不起房，不如把錢花掉，至少今天活得開心。 → 空錢包咖啡館"
    },
    {
      "id": "natural-025",
      "start": 102.096,
      "end": 106.35,
      "time": "01:42",
      "image": "assets/images/scene-025.webp",
      "sourceFullVersionImage": "scene-010.webp",
      "motion": "push",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 17,
      "showHeading": false,
      "visualTopic": "咖啡止痛藥",
      "selectionReason": "旁白第 17 段：」這叫「絕望消費」。 → 咖啡止痛藥"
    },
    {
      "id": "natural-026",
      "start": 106.35,
      "end": 110.604,
      "time": "01:46",
      "image": "assets/images/scene-026.webp",
      "sourceFullVersionImage": "scene-015.webp",
      "motion": "push",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 18,
      "showHeading": false,
      "visualTopic": "咖啡止痛藥",
      "selectionReason": "旁白第 18 段：當奮鬥改變不了命運，這口精品咖啡，就成了唯一的止痛藥。 → 咖啡止痛藥"
    },
    {
      "id": "natural-027",
      "start": 110.604,
      "end": 114.858,
      "time": "01:50",
      "image": "assets/images/scene-027.webp",
      "sourceFullVersionImage": "scene-020.webp",
      "motion": "push",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 18,
      "showHeading": false,
      "visualTopic": "咖啡止痛藥",
      "selectionReason": "旁白第 18 段：當奮鬥改變不了命運，這口精品咖啡，就成了唯一的止痛藥。 → 咖啡止痛藥"
    },
    {
      "id": "natural-028",
      "start": 114.858,
      "end": 119.112,
      "time": "01:54",
      "image": "assets/images/scene-028.webp",
      "sourceFullVersionImage": "scene-013.webp",
      "motion": "pan-left",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 19,
      "showHeading": false,
      "visualTopic": "傳統市場討價還價",
      "selectionReason": "旁白第 19 段：而同一時間，三條街外，七十歲的阿婆，正在為了一把蔥，爭得面紅耳赤。 → 傳統市場討價還價"
    },
    {
      "id": "natural-029",
      "start": 119.112,
      "end": 123.366,
      "time": "01:59",
      "image": "assets/images/scene-029.webp",
      "sourceFullVersionImage": "scene-018.webp",
      "motion": "pan-left",
      "heading": "第十名：200塊的絕望消費",
      "captionId": 19,
      "showHeading": false,
      "visualTopic": "傳統市場討價還價",
      "selectionReason": "旁白第 19 段：而同一時間，三條街外，七十歲的阿婆，正在為了一把蔥，爭得面紅耳赤。 → 傳統市場討價還價"
    },
    {
      "id": "natural-030",
      "start": 123.366,
      "end": 127.62,
      "time": "02:03",
      "image": "assets/images/scene-030.webp",
      "sourceFullVersionImage": "scene-034.webp",
      "motion": "push",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 20,
      "showHeading": true,
      "visualTopic": "工地與辦公大樓交界",
      "selectionReason": "旁白第 20 段：接下來這個更魔幻。 → 工地與辦公大樓交界"
    },
    {
      "id": "natural-031",
      "start": 127.62,
      "end": 131.874,
      "time": "02:07",
      "image": "assets/images/scene-031.webp",
      "sourceFullVersionImage": "scene-036.webp",
      "motion": "pull",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 21,
      "showHeading": false,
      "visualTopic": "移工數鈔票",
      "selectionReason": "旁白第 21 段：2024年，台灣工地的泰國移工，月薪可以拿到六到八萬，還包吃包住。 → 移工數鈔票"
    },
    {
      "id": "natural-032",
      "start": 131.874,
      "end": 136.128,
      "time": "02:11",
      "image": "assets/images/scene-032.webp",
      "sourceFullVersionImage": "scene-041.webp",
      "motion": "pull",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 21,
      "showHeading": false,
      "visualTopic": "移工數鈔票",
      "selectionReason": "旁白第 21 段：2024年，台灣工地的泰國移工，月薪可以拿到六到八萬，還包吃包住。 → 移工數鈔票"
    },
    {
      "id": "natural-033",
      "start": 136.128,
      "end": 140.382,
      "time": "02:16",
      "image": "assets/images/scene-033.webp",
      "sourceFullVersionImage": "scene-037.webp",
      "motion": "pan-left",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 22,
      "showHeading": false,
      "visualTopic": "畢業生薄薪資單",
      "selectionReason": "旁白第 22 段：而同一個工地的台灣大學畢業助理，起薪三萬多，還得自己付房租。 → 畢業生薄薪資單"
    },
    {
      "id": "natural-034",
      "start": 140.382,
      "end": 144.636,
      "time": "02:20",
      "image": "assets/images/scene-034.webp",
      "sourceFullVersionImage": "scene-042.webp",
      "motion": "pan-left",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 22,
      "showHeading": false,
      "visualTopic": "畢業生薄薪資單",
      "selectionReason": "旁白第 22 段：而同一個工地的台灣大學畢業助理，起薪三萬多，還得自己付房租。 → 畢業生薄薪資單"
    },
    {
      "id": "natural-035",
      "start": 144.636,
      "end": 148.89,
      "time": "02:24",
      "image": "assets/images/scene-035.webp",
      "sourceFullVersionImage": "scene-038.webp",
      "motion": "diagonal",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 23,
      "showHeading": false,
      "visualTopic": "科技辦公室工程師",
      "selectionReason": "旁白第 23 段：科技業大舉引進菲律賓、印度工程師，起薪直接七萬加補貼。 → 科技辦公室工程師"
    },
    {
      "id": "natural-036",
      "start": 148.89,
      "end": 153.144,
      "time": "02:28",
      "image": "assets/images/scene-036.webp",
      "sourceFullVersionImage": "scene-043.webp",
      "motion": "diagonal",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 23,
      "showHeading": false,
      "visualTopic": "科技辦公室工程師",
      "selectionReason": "旁白第 23 段：科技業大舉引進菲律賓、印度工程師，起薪直接七萬加補貼。 → 科技辦公室工程師"
    },
    {
      "id": "natural-037",
      "start": 153.144,
      "end": 157.398,
      "time": "02:33",
      "image": "assets/images/scene-037.webp",
      "sourceFullVersionImage": "scene-048.webp",
      "motion": "diagonal",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 24,
      "showHeading": false,
      "visualTopic": "科技辦公室工程師",
      "selectionReason": "旁白第 24 段：而進不了台積電的本地理科碩士，只能去系統廠領四萬五。 → 科技辦公室工程師"
    },
    {
      "id": "natural-038",
      "start": 157.398,
      "end": 161.652,
      "time": "02:37",
      "image": "assets/images/scene-038.webp",
      "sourceFullVersionImage": "scene-053.webp",
      "motion": "diagonal",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 24,
      "showHeading": false,
      "visualTopic": "科技辦公室工程師",
      "selectionReason": "旁白第 24 段：而進不了台積電的本地理科碩士，只能去系統廠領四萬五。 → 科技辦公室工程師"
    },
    {
      "id": "natural-039",
      "start": 161.652,
      "end": 165.906,
      "time": "02:41",
      "image": "assets/images/scene-039.webp",
      "sourceFullVersionImage": "scene-035.webp",
      "motion": "pan-right",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 25,
      "showHeading": false,
      "visualTopic": "薪資階梯",
      "selectionReason": "旁白第 25 段：台灣年輕人的起薪，已經被外勞超車了。 → 薪資階梯"
    },
    {
      "id": "natural-040",
      "start": 165.906,
      "end": 170.16,
      "time": "02:45",
      "image": "assets/images/scene-040.webp",
      "sourceFullVersionImage": "scene-039.webp",
      "motion": "push",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 26,
      "showHeading": false,
      "visualTopic": "工地與辦公大樓交界",
      "selectionReason": "旁白第 26 段：這不是歧視，這是警訊，除了半導體，我們幾乎沒有其他產業能帶動薪資成長。 → 工地與辦公大樓交界"
    },
    {
      "id": "natural-041",
      "start": 170.16,
      "end": 174.414,
      "time": "02:50",
      "image": "assets/images/scene-041.webp",
      "sourceFullVersionImage": "scene-044.webp",
      "motion": "push",
      "heading": "第九名：外勞都比你有錢",
      "captionId": 26,
      "showHeading": false,
      "visualTopic": "工地與辦公大樓交界",
      "selectionReason": "旁白第 26 段：這不是歧視，這是警訊，除了半導體，我們幾乎沒有其他產業能帶動薪資成長。 → 工地與辦公大樓交界"
    },
    {
      "id": "natural-042",
      "start": 174.414,
      "end": 178.668,
      "time": "02:54",
      "image": "assets/images/scene-042.webp",
      "sourceFullVersionImage": "scene-056.webp",
      "motion": "pan-right",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 27,
      "showHeading": true,
      "visualTopic": "畢業典禮",
      "selectionReason": "旁白第 27 段：台灣創下一個全球第一的紀錄：大學錄取率突破百分之百。 → 畢業典禮"
    },
    {
      "id": "natural-043",
      "start": 178.668,
      "end": 182.922,
      "time": "02:58",
      "image": "assets/images/scene-043.webp",
      "sourceFullVersionImage": "scene-061.webp",
      "motion": "pan-right",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 27,
      "showHeading": false,
      "visualTopic": "畢業典禮",
      "selectionReason": "旁白第 27 段：台灣創下一個全球第一的紀錄：大學錄取率突破百分之百。 → 畢業典禮"
    },
    {
      "id": "natural-044",
      "start": 182.922,
      "end": 187.176,
      "time": "03:02",
      "image": "assets/images/scene-044.webp",
      "sourceFullVersionImage": "scene-066.webp",
      "motion": "pan-right",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 28,
      "showHeading": false,
      "visualTopic": "畢業典禮",
      "selectionReason": "旁白第 28 段：只要會呼吸、會寫字，就有大學讀。 → 畢業典禮"
    },
    {
      "id": "natural-045",
      "start": 187.176,
      "end": 191.43,
      "time": "03:07",
      "image": "assets/images/scene-045.webp",
      "sourceFullVersionImage": "scene-071.webp",
      "motion": "pan-right",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 28,
      "showHeading": false,
      "visualTopic": "畢業典禮",
      "selectionReason": "旁白第 28 段：只要會呼吸、會寫字，就有大學讀。 → 畢業典禮"
    },
    {
      "id": "natural-046",
      "start": 191.43,
      "end": 195.684,
      "time": "03:11",
      "image": "assets/images/scene-046.webp",
      "sourceFullVersionImage": "scene-057.webp",
      "motion": "pull",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 29,
      "showHeading": false,
      "visualTopic": "學位證書",
      "selectionReason": "旁白第 29 段：但當人人都是大學生，文憑就成了廢紙。 → 學位證書"
    },
    {
      "id": "natural-047",
      "start": 195.684,
      "end": 199.938,
      "time": "03:15",
      "image": "assets/images/scene-047.webp",
      "sourceFullVersionImage": "scene-058.webp",
      "motion": "pan-left",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 30,
      "showHeading": false,
      "visualTopic": "便利商店工作",
      "selectionReason": "旁白第 30 段：現在碩士畢業，最好的工作可能是去超商當儲備店長，月薪三萬三。 → 便利商店工作"
    },
    {
      "id": "natural-048",
      "start": 199.938,
      "end": 204.192,
      "time": "03:19",
      "image": "assets/images/scene-048.webp",
      "sourceFullVersionImage": "scene-063.webp",
      "motion": "pan-left",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 30,
      "showHeading": false,
      "visualTopic": "便利商店工作",
      "selectionReason": "旁白第 30 段：現在碩士畢業，最好的工作可能是去超商當儲備店長，月薪三萬三。 → 便利商店工作"
    },
    {
      "id": "natural-049",
      "start": 204.192,
      "end": 208.446,
      "time": "03:24",
      "image": "assets/images/scene-049.webp",
      "sourceFullVersionImage": "scene-068.webp",
      "motion": "pan-left",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 31,
      "showHeading": false,
      "visualTopic": "便利商店工作",
      "selectionReason": "旁白第 31 段：三十年前，高中畢業生起薪就有兩萬八。 → 便利商店工作"
    },
    {
      "id": "natural-050",
      "start": 208.446,
      "end": 212.7,
      "time": "03:28",
      "image": "assets/images/scene-050.webp",
      "sourceFullVersionImage": "scene-062.webp",
      "motion": "pull",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 32,
      "showHeading": false,
      "visualTopic": "學位證書",
      "selectionReason": "旁白第 32 段：你多讀了七年書，價值竟然只多了幾千塊？ → 學位證書"
    },
    {
      "id": "natural-051",
      "start": 212.7,
      "end": 216.954,
      "time": "03:32",
      "image": "assets/images/scene-051.webp",
      "sourceFullVersionImage": "scene-067.webp",
      "motion": "pull",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 32,
      "showHeading": false,
      "visualTopic": "學位證書",
      "selectionReason": "旁白第 32 段：你多讀了七年書，價值竟然只多了幾千塊？ → 學位證書"
    },
    {
      "id": "natural-052",
      "start": 216.954,
      "end": 221.208,
      "time": "03:36",
      "image": "assets/images/scene-052.webp",
      "sourceFullVersionImage": "scene-055.webp",
      "motion": "push",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 33,
      "showHeading": false,
      "visualTopic": "教育成本",
      "selectionReason": "旁白第 33 段：家裡砸了兩百萬供你讀書，畢業後不吃不喝要四十七個月才能還清。 → 教育成本"
    },
    {
      "id": "natural-053",
      "start": 221.208,
      "end": 225.462,
      "time": "03:41",
      "image": "assets/images/scene-053.webp",
      "sourceFullVersionImage": "scene-060.webp",
      "motion": "push",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 33,
      "showHeading": false,
      "visualTopic": "教育成本",
      "selectionReason": "旁白第 33 段：家裡砸了兩百萬供你讀書，畢業後不吃不喝要四十七個月才能還清。 → 教育成本"
    },
    {
      "id": "natural-054",
      "start": 225.462,
      "end": 229.716,
      "time": "03:45",
      "image": "assets/images/scene-054.webp",
      "sourceFullVersionImage": "scene-065.webp",
      "motion": "push",
      "heading": "第八名：學歷是最大的騙局",
      "captionId": 34,
      "showHeading": false,
      "visualTopic": "教育成本",
      "selectionReason": "旁白第 34 段：這筆帳，怎麼算都算不平。 → 教育成本"
    },
    {
      "id": "natural-055",
      "start": 229.716,
      "end": 233.97,
      "time": "03:49",
      "image": "assets/images/scene-055.webp",
      "sourceFullVersionImage": "scene-079.webp",
      "motion": "pan-left",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 35,
      "showHeading": true,
      "visualTopic": "七坪無廚房套房",
      "selectionReason": "旁白第 35 段：在台北，一間沒廚房、沒陽台、廁所還要側身進去的七坪套房，月租一萬五，這還是佛心價。 → 七坪無廚房套房"
    },
    {
      "id": "natural-056",
      "start": 233.97,
      "end": 238.224,
      "time": "03:53",
      "image": "assets/images/scene-056.webp",
      "sourceFullVersionImage": "scene-084.webp",
      "motion": "pan-left",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 35,
      "showHeading": false,
      "visualTopic": "七坪無廚房套房",
      "selectionReason": "旁白第 35 段：在台北，一間沒廚房、沒陽台、廁所還要側身進去的七坪套房，月租一萬五，這還是佛心價。 → 七坪無廚房套房"
    },
    {
      "id": "natural-057",
      "start": 238.224,
      "end": 242.478,
      "time": "03:58",
      "image": "assets/images/scene-057.webp",
      "sourceFullVersionImage": "scene-089.webp",
      "motion": "pan-left",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 35,
      "showHeading": false,
      "visualTopic": "七坪無廚房套房",
      "selectionReason": "旁白第 35 段：在台北，一間沒廚房、沒陽台、廁所還要側身進去的七坪套房，月租一萬五，這還是佛心價。 → 七坪無廚房套房"
    },
    {
      "id": "natural-058",
      "start": 242.478,
      "end": 246.732,
      "time": "04:02",
      "image": "assets/images/scene-058.webp",
      "sourceFullVersionImage": "scene-080.webp",
      "motion": "diagonal",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 36,
      "showHeading": false,
      "visualTopic": "薪水被房租交通切割",
      "selectionReason": "旁白第 36 段：而台北三十歲以下年輕人的薪資中位數，只有三萬六。 → 薪水被房租交通切割"
    },
    {
      "id": "natural-059",
      "start": 246.732,
      "end": 250.986,
      "time": "04:06",
      "image": "assets/images/scene-059.webp",
      "sourceFullVersionImage": "scene-077.webp",
      "motion": "pan-right",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 37,
      "showHeading": false,
      "visualTopic": "房租生活帳單",
      "selectionReason": "旁白第 37 段：扣掉房租、吃飯、交通，一個月只剩六千塊，你要拿來應付看病和紅包。 → 房租生活帳單"
    },
    {
      "id": "natural-060",
      "start": 250.986,
      "end": 255.24,
      "time": "04:10",
      "image": "assets/images/scene-060.webp",
      "sourceFullVersionImage": "scene-082.webp",
      "motion": "pan-right",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 37,
      "showHeading": false,
      "visualTopic": "房租生活帳單",
      "selectionReason": "旁白第 37 段：扣掉房租、吃飯、交通，一個月只剩六千塊，你要拿來應付看病和紅包。 → 房租生活帳單"
    },
    {
      "id": "natural-061",
      "start": 255.24,
      "end": 259.494,
      "time": "04:15",
      "image": "assets/images/scene-061.webp",
      "sourceFullVersionImage": "scene-087.webp",
      "motion": "pan-right",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 37,
      "showHeading": false,
      "visualTopic": "房租生活帳單",
      "selectionReason": "旁白第 37 段：扣掉房租、吃飯、交通，一個月只剩六千塊，你要拿來應付看病和紅包。 → 房租生活帳單"
    },
    {
      "id": "natural-062",
      "start": 259.494,
      "end": 263.748,
      "time": "04:19",
      "image": "assets/images/scene-062.webp",
      "sourceFullVersionImage": "scene-092.webp",
      "motion": "pan-right",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 38,
      "showHeading": false,
      "visualTopic": "房租生活帳單",
      "selectionReason": "旁白第 38 段：你攢一輩子，連個停車位的頭期款都湊不齊。 → 房租生活帳單"
    },
    {
      "id": "natural-063",
      "start": 263.748,
      "end": 268.002,
      "time": "04:23",
      "image": "assets/images/scene-063.webp",
      "sourceFullVersionImage": "scene-076.webp",
      "motion": "push",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 39,
      "showHeading": false,
      "visualTopic": "窗邊昂貴住宅",
      "selectionReason": "旁白第 39 段：去中南部？ → 窗邊昂貴住宅"
    },
    {
      "id": "natural-064",
      "start": 268.002,
      "end": 272.256,
      "time": "04:28",
      "image": "assets/images/scene-064.webp",
      "sourceFullVersionImage": "scene-081.webp",
      "motion": "push",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 40,
      "showHeading": false,
      "visualTopic": "窗邊昂貴住宅",
      "selectionReason": "旁白第 40 段：房價是便宜了，但你的薪水，也會跟著對半砍。 → 窗邊昂貴住宅"
    },
    {
      "id": "natural-065",
      "start": 272.256,
      "end": 276.51,
      "time": "04:32",
      "image": "assets/images/scene-065.webp",
      "sourceFullVersionImage": "scene-077.webp",
      "motion": "pan-right",
      "heading": "第七名：房租在吃你的未來",
      "captionId": 41,
      "showHeading": false,
      "visualTopic": "房租生活帳單",
      "selectionReason": "旁白第 41 段：這是一個無解的死局。 → 房租生活帳單"
    },
    {
      "id": "natural-066",
      "start": 276.51,
      "end": 280.764,
      "time": "04:36",
      "image": "assets/images/scene-066.webp",
      "sourceFullVersionImage": "scene-101.webp",
      "motion": "diagonal",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 42,
      "showHeading": true,
      "visualTopic": "新舊排骨便當",
      "selectionReason": "旁白第 42 段：2004年，一個排骨便當六十塊，2024年，一百二十塊，物價翻了一倍。 → 新舊排骨便當"
    },
    {
      "id": "natural-067",
      "start": 280.764,
      "end": 285.018,
      "time": "04:40",
      "image": "assets/images/scene-067.webp",
      "sourceFullVersionImage": "scene-106.webp",
      "motion": "diagonal",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 42,
      "showHeading": false,
      "visualTopic": "新舊排骨便當",
      "selectionReason": "旁白第 42 段：2004年，一個排骨便當六十塊，2024年，一百二十塊，物價翻了一倍。 → 新舊排骨便當"
    },
    {
      "id": "natural-068",
      "start": 285.018,
      "end": 289.272,
      "time": "04:45",
      "image": "assets/images/scene-068.webp",
      "sourceFullVersionImage": "scene-111.webp",
      "motion": "diagonal",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 42,
      "showHeading": false,
      "visualTopic": "新舊排骨便當",
      "selectionReason": "旁白第 42 段：2004年，一個排骨便當六十塊，2024年，一百二十塊，物價翻了一倍。 → 新舊排骨便當"
    },
    {
      "id": "natural-069",
      "start": 289.272,
      "end": 293.526,
      "time": "04:49",
      "image": "assets/images/scene-069.webp",
      "sourceFullVersionImage": "scene-098.webp",
      "motion": "pan-right",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 43,
      "showHeading": false,
      "visualTopic": "新舊帳單",
      "selectionReason": "旁白第 43 段：但大學起薪，從兩萬八只漲到三萬二，漲幅僅僅百分之十四。 → 新舊帳單"
    },
    {
      "id": "natural-070",
      "start": 293.526,
      "end": 297.78,
      "time": "04:53",
      "image": "assets/images/scene-070.webp",
      "sourceFullVersionImage": "scene-103.webp",
      "motion": "pan-right",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 43,
      "showHeading": false,
      "visualTopic": "新舊帳單",
      "selectionReason": "旁白第 43 段：但大學起薪，從兩萬八只漲到三萬二，漲幅僅僅百分之十四。 → 新舊帳單"
    },
    {
      "id": "natural-071",
      "start": 297.78,
      "end": 302.034,
      "time": "04:57",
      "image": "assets/images/scene-071.webp",
      "sourceFullVersionImage": "scene-108.webp",
      "motion": "pan-right",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 44,
      "showHeading": false,
      "visualTopic": "新舊帳單",
      "selectionReason": "旁白第 44 段：剩下的百分之八十六跑去哪了？ → 新舊帳單"
    },
    {
      "id": "natural-072",
      "start": 302.034,
      "end": 306.288,
      "time": "05:02",
      "image": "assets/images/scene-072.webp",
      "sourceFullVersionImage": "scene-100.webp",
      "motion": "pan-left",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 45,
      "showHeading": false,
      "visualTopic": "沉船與固定薪資",
      "selectionReason": "旁白第 45 段：流進了企業利潤、流進了股東口袋，變成了那漂亮的GDP數字。 → 沉船與固定薪資"
    },
    {
      "id": "natural-073",
      "start": 306.288,
      "end": 310.542,
      "time": "05:06",
      "image": "assets/images/scene-073.webp",
      "sourceFullVersionImage": "scene-105.webp",
      "motion": "pan-left",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 46,
      "showHeading": false,
      "visualTopic": "沉船與固定薪資",
      "selectionReason": "旁白第 46 段：你就像在一艘下沉的船上，薪水沒漲，但水電、健保、房租，每一樣都在漲。 → 沉船與固定薪資"
    },
    {
      "id": "natural-074",
      "start": 310.542,
      "end": 314.796,
      "time": "05:10",
      "image": "assets/images/scene-074.webp",
      "sourceFullVersionImage": "scene-110.webp",
      "motion": "pan-left",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 46,
      "showHeading": false,
      "visualTopic": "沉船與固定薪資",
      "selectionReason": "旁白第 46 段：你就像在一艘下沉的船上，薪水沒漲，但水電、健保、房租，每一樣都在漲。 → 沉船與固定薪資"
    },
    {
      "id": "natural-075",
      "start": 314.796,
      "end": 319.05,
      "time": "05:14",
      "image": "assets/images/scene-075.webp",
      "sourceFullVersionImage": "scene-115.webp",
      "motion": "pan-left",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 46,
      "showHeading": false,
      "visualTopic": "沉船與固定薪資",
      "selectionReason": "旁白第 46 段：你就像在一艘下沉的船上，薪水沒漲，但水電、健保、房租，每一樣都在漲。 → 沉船與固定薪資"
    },
    {
      "id": "natural-076",
      "start": 319.05,
      "end": 323.304,
      "time": "05:19",
      "image": "assets/images/scene-076.webp",
      "sourceFullVersionImage": "scene-097.webp",
      "motion": "push",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 47,
      "showHeading": false,
      "visualTopic": "淹水城市",
      "selectionReason": "旁白第 47 段：水位越來越高，你的頭，離水面越來越近。 → 淹水城市"
    },
    {
      "id": "natural-077",
      "start": 323.304,
      "end": 327.558,
      "time": "05:23",
      "image": "assets/images/scene-077.webp",
      "sourceFullVersionImage": "scene-099.webp",
      "motion": "pull",
      "heading": "第六名：物價飛漲與薪水凍結",
      "captionId": 47,
      "showHeading": false,
      "visualTopic": "只剩頭部露出水面",
      "selectionReason": "旁白第 47 段：水位越來越高，你的頭，離水面越來越近。 → 只剩頭部露出水面"
    },
    {
      "id": "natural-078",
      "start": 327.558,
      "end": 331.812,
      "time": "05:27",
      "image": "assets/images/scene-078.webp",
      "sourceFullVersionImage": "scene-122.webp",
      "motion": "diagonal",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 48,
      "showHeading": true,
      "visualTopic": "辦公桌延伸到客廳",
      "selectionReason": "旁白第 48 段：官方統計，台灣工時全球第四高，年均超過兩千小時。 → 辦公桌延伸到客廳"
    },
    {
      "id": "natural-079",
      "start": 331.812,
      "end": 336.066,
      "time": "05:31",
      "image": "assets/images/scene-079.webp",
      "sourceFullVersionImage": "scene-121.webp",
      "motion": "pan-left",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 49,
      "showHeading": false,
      "visualTopic": "訊息通知像雨",
      "selectionReason": "旁白第 49 段：但真實數字更恐怖，因為還有「LINE加班」。 → 訊息通知像雨"
    },
    {
      "id": "natural-080",
      "start": 336.066,
      "end": 340.32,
      "time": "05:36",
      "image": "assets/images/scene-080.webp",
      "sourceFullVersionImage": "scene-126.webp",
      "motion": "pan-left",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 49,
      "showHeading": false,
      "visualTopic": "訊息通知像雨",
      "selectionReason": "旁白第 49 段：但真實數字更恐怖，因為還有「LINE加班」。 → 訊息通知像雨"
    },
    {
      "id": "natural-081",
      "start": 340.32,
      "end": 344.574,
      "time": "05:40",
      "image": "assets/images/scene-081.webp",
      "sourceFullVersionImage": "scene-119.webp",
      "motion": "pan-right",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 50,
      "showHeading": false,
      "visualTopic": "沙發仍被工作追趕",
      "selectionReason": "旁白第 50 段：下班回家躺在沙發上，主管一則訊息過來：「數據更新一下，謝謝。 → 沙發仍被工作追趕"
    },
    {
      "id": "natural-082",
      "start": 344.574,
      "end": 348.828,
      "time": "05:44",
      "image": "assets/images/scene-082.webp",
      "sourceFullVersionImage": "scene-124.webp",
      "motion": "pan-right",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 50,
      "showHeading": false,
      "visualTopic": "沙發仍被工作追趕",
      "selectionReason": "旁白第 50 段：下班回家躺在沙發上，主管一則訊息過來：「數據更新一下，謝謝。 → 沙發仍被工作追趕"
    },
    {
      "id": "natural-083",
      "start": 348.828,
      "end": 353.082,
      "time": "05:48",
      "image": "assets/images/scene-083.webp",
      "sourceFullVersionImage": "scene-118.webp",
      "motion": "push",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 51,
      "showHeading": false,
      "visualTopic": "夜色手機",
      "selectionReason": "旁白第 51 段：」沒有加班費，你敢不回嗎？ → 夜色手機"
    },
    {
      "id": "natural-084",
      "start": 353.082,
      "end": 357.336,
      "time": "05:53",
      "image": "assets/images/scene-084.webp",
      "sourceFullVersionImage": "scene-131.webp",
      "motion": "pan-left",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 52,
      "showHeading": false,
      "visualTopic": "訊息通知像雨",
      "selectionReason": "旁白第 52 段：你不回，年終考核就拿叉。 → 訊息通知像雨"
    },
    {
      "id": "natural-085",
      "start": 357.336,
      "end": 361.59,
      "time": "05:57",
      "image": "assets/images/scene-085.webp",
      "sourceFullVersionImage": "scene-127.webp",
      "motion": "diagonal",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 53,
      "showHeading": false,
      "visualTopic": "辦公桌延伸到客廳",
      "selectionReason": "旁白第 53 段：這種隱形加班，每年至少吞噬掉台灣勞工兩千億的薪資。 → 辦公桌延伸到客廳"
    },
    {
      "id": "natural-086",
      "start": 361.59,
      "end": 365.844,
      "time": "06:01",
      "image": "assets/images/scene-086.webp",
      "sourceFullVersionImage": "scene-132.webp",
      "motion": "diagonal",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 53,
      "showHeading": false,
      "visualTopic": "辦公桌延伸到客廳",
      "selectionReason": "旁白第 53 段：這種隱形加班，每年至少吞噬掉台灣勞工兩千億的薪資。 → 辦公桌延伸到客廳"
    },
    {
      "id": "natural-087",
      "start": 365.844,
      "end": 370.098,
      "time": "06:05",
      "image": "assets/images/scene-087.webp",
      "sourceFullVersionImage": "scene-120.webp",
      "motion": "pull",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 54,
      "showHeading": false,
      "visualTopic": "手機照亮疲憊主角",
      "selectionReason": "旁白第 54 段：企業用「責任感」當話術，讓你即便累垮，也要為「公司這個家」賣命。 → 手機照亮疲憊主角"
    },
    {
      "id": "natural-088",
      "start": 370.098,
      "end": 374.352,
      "time": "06:10",
      "image": "assets/images/scene-088.webp",
      "sourceFullVersionImage": "scene-125.webp",
      "motion": "pull",
      "heading": "第五名：隱形的LINE加班",
      "captionId": 54,
      "showHeading": false,
      "visualTopic": "手機照亮疲憊主角",
      "selectionReason": "旁白第 54 段：企業用「責任感」當話術，讓你即便累垮，也要為「公司這個家」賣命。 → 手機照亮疲憊主角"
    },
    {
      "id": "natural-089",
      "start": 374.352,
      "end": 378.606,
      "time": "06:14",
      "image": "assets/images/scene-089.webp",
      "sourceFullVersionImage": "scene-139.webp",
      "motion": "push",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 55,
      "showHeading": true,
      "visualTopic": "工程師獎金",
      "selectionReason": "旁白第 55 段：台積電入職五年的工程師，2023年分紅加獎金大約三百萬。 → 工程師獎金"
    },
    {
      "id": "natural-090",
      "start": 378.606,
      "end": 382.86,
      "time": "06:18",
      "image": "assets/images/scene-090.webp",
      "sourceFullVersionImage": "scene-144.webp",
      "motion": "push",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 55,
      "showHeading": false,
      "visualTopic": "工程師獎金",
      "selectionReason": "旁白第 55 段：台積電入職五年的工程師，2023年分紅加獎金大約三百萬。 → 工程師獎金"
    },
    {
      "id": "natural-091",
      "start": 382.86,
      "end": 387.114,
      "time": "06:22",
      "image": "assets/images/scene-091.webp",
      "sourceFullVersionImage": "scene-143.webp",
      "motion": "diagonal",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 56,
      "showHeading": false,
      "visualTopic": "餐廳服務員",
      "selectionReason": "旁白第 56 段：這是一個在餐廳端盤子的年輕人，要工作六年半才拿得到的錢。 → 餐廳服務員"
    },
    {
      "id": "natural-092",
      "start": 387.114,
      "end": 391.368,
      "time": "06:27",
      "image": "assets/images/scene-092.webp",
      "sourceFullVersionImage": "scene-148.webp",
      "motion": "diagonal",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 56,
      "showHeading": false,
      "visualTopic": "餐廳服務員",
      "selectionReason": "旁白第 56 段：這是一個在餐廳端盤子的年輕人，要工作六年半才拿得到的錢。 → 餐廳服務員"
    },
    {
      "id": "natural-093",
      "start": 391.368,
      "end": 395.622,
      "time": "06:31",
      "image": "assets/images/scene-093.webp",
      "sourceFullVersionImage": "scene-140.webp",
      "motion": "pan-right",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 57,
      "showHeading": false,
      "visualTopic": "收入樓梯",
      "selectionReason": "旁白第 57 段：台灣的財富不是創造得少，而是分配得極其畸形。 → 收入樓梯"
    },
    {
      "id": "natural-094",
      "start": 395.622,
      "end": 399.876,
      "time": "06:35",
      "image": "assets/images/scene-094.webp",
      "sourceFullVersionImage": "scene-142.webp",
      "motion": "pan-left",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 58,
      "showHeading": false,
      "visualTopic": "財富集中高塔",
      "selectionReason": "旁白第 58 段：半導體業拿走了社會最多的利潤，但受益的人口，不到百分之三。 → 財富集中高塔"
    },
    {
      "id": "natural-095",
      "start": 399.876,
      "end": 404.13,
      "time": "06:39",
      "image": "assets/images/scene-095.webp",
      "sourceFullVersionImage": "scene-147.webp",
      "motion": "pan-left",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 58,
      "showHeading": false,
      "visualTopic": "財富集中高塔",
      "selectionReason": "旁白第 58 段：半導體業拿走了社會最多的利潤，但受益的人口，不到百分之三。 → 財富集中高塔"
    },
    {
      "id": "natural-096",
      "start": 404.13,
      "end": 408.384,
      "time": "06:44",
      "image": "assets/images/scene-096.webp",
      "sourceFullVersionImage": "scene-141.webp",
      "motion": "pull",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 59,
      "showHeading": false,
      "visualTopic": "科技大樓與傳統工廠",
      "selectionReason": "旁白第 59 段：剩下九成七的人，在傳統產業和服務業拼命，他們創造的GDP一樣真實，但分到的，連湯渣都算不上。 → 科技大樓與傳統工廠"
    },
    {
      "id": "natural-097",
      "start": 408.384,
      "end": 412.638,
      "time": "06:48",
      "image": "assets/images/scene-097.webp",
      "sourceFullVersionImage": "scene-152.webp",
      "motion": "pan-left",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 59,
      "showHeading": false,
      "visualTopic": "財富集中高塔",
      "selectionReason": "旁白第 59 段：剩下九成七的人，在傳統產業和服務業拼命，他們創造的GDP一樣真實，但分到的，連湯渣都算不上。 → 財富集中高塔"
    },
    {
      "id": "natural-098",
      "start": 412.638,
      "end": 416.892,
      "time": "06:52",
      "image": "assets/images/scene-098.webp",
      "sourceFullVersionImage": "scene-146.webp",
      "motion": "pull",
      "heading": "第四名：財富分配的畸形劇本",
      "captionId": 59,
      "showHeading": false,
      "visualTopic": "科技大樓與傳統工廠",
      "selectionReason": "旁白第 59 段：剩下九成七的人，在傳統產業和服務業拼命，他們創造的GDP一樣真實，但分到的，連湯渣都算不上。 → 科技大樓與傳統工廠"
    },
    {
      "id": "natural-099",
      "start": 416.892,
      "end": 421.146,
      "time": "06:56",
      "image": "assets/images/scene-099.webp",
      "sourceFullVersionImage": "scene-160.webp",
      "motion": "push",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 60,
      "showHeading": true,
      "visualTopic": "文學道路障礙",
      "selectionReason": "旁白第 60 段：在台灣，如果你高中選了文組，你的人生路徑，就被砍掉了百分之八十。 → 文學道路障礙"
    },
    {
      "id": "natural-100",
      "start": 421.146,
      "end": 425.4,
      "time": "07:01",
      "image": "assets/images/scene-100.webp",
      "sourceFullVersionImage": "scene-165.webp",
      "motion": "push",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 60,
      "showHeading": false,
      "visualTopic": "文學道路障礙",
      "selectionReason": "旁白第 60 段：在台灣，如果你高中選了文組，你的人生路徑，就被砍掉了百分之八十。 → 文學道路障礙"
    },
    {
      "id": "natural-101",
      "start": 425.4,
      "end": 429.654,
      "time": "07:05",
      "image": "assets/images/scene-101.webp",
      "sourceFullVersionImage": "scene-164.webp",
      "motion": "diagonal",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 61,
      "showHeading": false,
      "visualTopic": "詩人與工程機台",
      "selectionReason": "旁白第 61 段：中文碩士起薪三萬，機械學士進台積電年薪破百萬，差距是三倍。 → 詩人與工程機台"
    },
    {
      "id": "natural-102",
      "start": 429.654,
      "end": 433.908,
      "time": "07:09",
      "image": "assets/images/scene-102.webp",
      "sourceFullVersionImage": "scene-169.webp",
      "motion": "diagonal",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 61,
      "showHeading": false,
      "visualTopic": "詩人與工程機台",
      "selectionReason": "旁白第 61 段：中文碩士起薪三萬，機械學士進台積電年薪破百萬，差距是三倍。 → 詩人與工程機台"
    },
    {
      "id": "natural-103",
      "start": 433.908,
      "end": 438.162,
      "time": "07:13",
      "image": "assets/images/scene-103.webp",
      "sourceFullVersionImage": "scene-163.webp",
      "motion": "pan-left",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 62,
      "showHeading": false,
      "visualTopic": "電路板與書頁",
      "selectionReason": "旁白第 62 段：這導致了殘酷的篩選：考不上理工科的人，在階級上被永久降等。 → 電路板與書頁"
    },
    {
      "id": "natural-104",
      "start": 438.162,
      "end": 442.416,
      "time": "07:18",
      "image": "assets/images/scene-104.webp",
      "sourceFullVersionImage": "scene-168.webp",
      "motion": "pan-left",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 62,
      "showHeading": false,
      "visualTopic": "電路板與書頁",
      "selectionReason": "旁白第 62 段：這導致了殘酷的篩選：考不上理工科的人，在階級上被永久降等。 → 電路板與書頁"
    },
    {
      "id": "natural-105",
      "start": 442.416,
      "end": 446.67,
      "time": "07:22",
      "image": "assets/images/scene-105.webp",
      "sourceFullVersionImage": "scene-174.webp",
      "motion": "diagonal",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 63,
      "showHeading": false,
      "visualTopic": "詩人與工程機台",
      "selectionReason": "旁白第 63 段：我們的社會只需要工程師，不需要詩人。 → 詩人與工程機台"
    },
    {
      "id": "natural-106",
      "start": 446.67,
      "end": 450.924,
      "time": "07:26",
      "image": "assets/images/scene-106.webp",
      "sourceFullVersionImage": "scene-179.webp",
      "motion": "diagonal",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 63,
      "showHeading": false,
      "visualTopic": "詩人與工程機台",
      "selectionReason": "旁白第 63 段：我們的社會只需要工程師，不需要詩人。 → 詩人與工程機台"
    },
    {
      "id": "natural-107",
      "start": 450.924,
      "end": 455.178,
      "time": "07:30",
      "image": "assets/images/scene-107.webp",
      "sourceFullVersionImage": "scene-161.webp",
      "motion": "pan-right",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 64,
      "showHeading": false,
      "visualTopic": "抱著書的主角",
      "selectionReason": "旁白第 64 段：難道愛文學、愛藝術的孩子，唯一的錯，就是出生在一個只看數據的社會嗎？ → 抱著書的主角"
    },
    {
      "id": "natural-108",
      "start": 455.178,
      "end": 459.432,
      "time": "07:35",
      "image": "assets/images/scene-108.webp",
      "sourceFullVersionImage": "scene-162.webp",
      "motion": "pull",
      "heading": "第三名：文組的經濟死刑",
      "captionId": 64,
      "showHeading": false,
      "visualTopic": "文學書筆記",
      "selectionReason": "旁白第 64 段：難道愛文學、愛藝術的孩子，唯一的錯，就是出生在一個只看數據的社會嗎？ → 文學書筆記"
    },
    {
      "id": "natural-109",
      "start": 459.432,
      "end": 463.686,
      "time": "07:39",
      "image": "assets/images/scene-109.webp",
      "sourceFullVersionImage": "scene-181.webp",
      "motion": "push",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 65,
      "showHeading": true,
      "visualTopic": "負數計算機",
      "selectionReason": "旁白第 65 段：我們來算一題小學數學：台北一間中古公寓兩千五百萬，房貸每月要還七萬六。 → 負數計算機"
    },
    {
      "id": "natural-110",
      "start": 463.686,
      "end": 467.94,
      "time": "07:43",
      "image": "assets/images/scene-110.webp",
      "sourceFullVersionImage": "scene-184.webp",
      "motion": "pan-left",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 65,
      "showHeading": false,
      "visualTopic": "房貸高牆",
      "selectionReason": "旁白第 65 段：我們來算一題小學數學：台北一間中古公寓兩千五百萬，房貸每月要還七萬六。 → 房貸高牆"
    },
    {
      "id": "natural-111",
      "start": 467.94,
      "end": 472.194,
      "time": "07:47",
      "image": "assets/images/scene-111.webp",
      "sourceFullVersionImage": "scene-189.webp",
      "motion": "pan-left",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 66,
      "showHeading": false,
      "visualTopic": "房貸高牆",
      "selectionReason": "旁白第 66 段：但三十到四十歲人的月薪中位數，只有五萬二。 → 房貸高牆"
    },
    {
      "id": "natural-112",
      "start": 472.194,
      "end": 476.448,
      "time": "07:52",
      "image": "assets/images/scene-112.webp",
      "sourceFullVersionImage": "scene-194.webp",
      "motion": "pan-left",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 66,
      "showHeading": false,
      "visualTopic": "房貸高牆",
      "selectionReason": "旁白第 66 段：但三十到四十歲人的月薪中位數，只有五萬二。 → 房貸高牆"
    },
    {
      "id": "natural-113",
      "start": 476.448,
      "end": 480.702,
      "time": "07:56",
      "image": "assets/images/scene-113.webp",
      "sourceFullVersionImage": "scene-182.webp",
      "motion": "pan-right",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 67,
      "showHeading": false,
      "visualTopic": "遙不可及房屋",
      "selectionReason": "旁白第 67 段：你的薪水連房貸都還不起，更別提那五百萬的頭期款。 → 遙不可及房屋"
    },
    {
      "id": "natural-114",
      "start": 480.702,
      "end": 484.956,
      "time": "08:00",
      "image": "assets/images/scene-114.webp",
      "sourceFullVersionImage": "scene-185.webp",
      "motion": "diagonal",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 68,
      "showHeading": false,
      "visualTopic": "躺平看天花板",
      "selectionReason": "旁白第 68 段：所以年輕人選擇「躺平」。 → 躺平看天花板"
    },
    {
      "id": "natural-115",
      "start": 484.956,
      "end": 489.21,
      "time": "08:04",
      "image": "assets/images/scene-115.webp",
      "sourceFullVersionImage": "scene-186.webp",
      "motion": "push",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 69,
      "showHeading": false,
      "visualTopic": "負數計算機",
      "selectionReason": "旁白第 69 段：這不是懶惰，而是在算完所有可能性之後，唯一剩下的理性結論。 → 負數計算機"
    },
    {
      "id": "natural-116",
      "start": 489.21,
      "end": 493.464,
      "time": "08:09",
      "image": "assets/images/scene-116.webp",
      "sourceFullVersionImage": "scene-191.webp",
      "motion": "push",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 69,
      "showHeading": false,
      "visualTopic": "負數計算機",
      "selectionReason": "旁白第 69 段：這不是懶惰，而是在算完所有可能性之後，唯一剩下的理性結論。 → 負數計算機"
    },
    {
      "id": "natural-117",
      "start": 493.464,
      "end": 497.718,
      "time": "08:13",
      "image": "assets/images/scene-117.webp",
      "sourceFullVersionImage": "scene-183.webp",
      "motion": "pull",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 70,
      "showHeading": false,
      "visualTopic": "房屋廣告",
      "selectionReason": "旁白第 70 段：2024年台灣出生率全球倒數第一，因為大家發現，連養活自己都快沒能力了。 → 房屋廣告"
    },
    {
      "id": "natural-118",
      "start": 497.718,
      "end": 501.972,
      "time": "08:17",
      "image": "assets/images/scene-118.webp",
      "sourceFullVersionImage": "scene-188.webp",
      "motion": "pull",
      "heading": "第二名：買房是數學上的不可能",
      "captionId": 70,
      "showHeading": false,
      "visualTopic": "房屋廣告",
      "selectionReason": "旁白第 70 段：2024年台灣出生率全球倒數第一，因為大家發現，連養活自己都快沒能力了。 → 房屋廣告"
    },
    {
      "id": "natural-119",
      "start": 501.972,
      "end": 506.226,
      "time": "08:21",
      "image": "assets/images/scene-119.webp",
      "sourceFullVersionImage": "scene-204.webp",
      "motion": "pull",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 71,
      "showHeading": true,
      "visualTopic": "豪宅與壁癌老屋",
      "selectionReason": "旁白第 71 段：最後，這是台灣最醜陋的傷疤：兩個完全平行的世界。 → 豪宅與壁癌老屋"
    },
    {
      "id": "natural-120",
      "start": 506.226,
      "end": 510.48,
      "time": "08:26",
      "image": "assets/images/scene-120.webp",
      "sourceFullVersionImage": "scene-209.webp",
      "motion": "pull",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 71,
      "showHeading": false,
      "visualTopic": "豪宅與壁癌老屋",
      "selectionReason": "旁白第 71 段：最後，這是台灣最醜陋的傷疤：兩個完全平行的世界。 → 豪宅與壁癌老屋"
    },
    {
      "id": "natural-121",
      "start": 510.48,
      "end": 514.734,
      "time": "08:30",
      "image": "assets/images/scene-121.webp",
      "sourceFullVersionImage": "scene-214.webp",
      "motion": "pull",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 72,
      "showHeading": false,
      "visualTopic": "豪宅與壁癌老屋",
      "selectionReason": "旁白第 72 段：一邊，住在重劃區豪宅，開著特斯拉，討論小孩去美國參加夏令營。 → 豪宅與壁癌老屋"
    },
    {
      "id": "natural-122",
      "start": 514.734,
      "end": 518.988,
      "time": "08:34",
      "image": "assets/images/scene-122.webp",
      "sourceFullVersionImage": "scene-219.webp",
      "motion": "pull",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 72,
      "showHeading": false,
      "visualTopic": "豪宅與壁癌老屋",
      "selectionReason": "旁白第 72 段：一邊，住在重劃區豪宅，開著特斯拉，討論小孩去美國參加夏令營。 → 豪宅與壁癌老屋"
    },
    {
      "id": "natural-123",
      "start": 518.988,
      "end": 523.242,
      "time": "08:38",
      "image": "assets/images/scene-123.webp",
      "sourceFullVersionImage": "scene-205.webp",
      "motion": "pan-left",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 73,
      "showHeading": false,
      "visualTopic": "豪華休旅車與老機車",
      "selectionReason": "旁白第 73 段：另一邊，擠在牆壁爬滿壁癌的40年老屋，騎著15年的機車，晚餐吃八十塊的雞腿飯。 → 豪華休旅車與老機車"
    },
    {
      "id": "natural-124",
      "start": 523.242,
      "end": 527.496,
      "time": "08:43",
      "image": "assets/images/scene-124.webp",
      "sourceFullVersionImage": "scene-210.webp",
      "motion": "pan-left",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 73,
      "showHeading": false,
      "visualTopic": "豪華休旅車與老機車",
      "selectionReason": "旁白第 73 段：另一邊，擠在牆壁爬滿壁癌的40年老屋，騎著15年的機車，晚餐吃八十塊的雞腿飯。 → 豪華休旅車與老機車"
    },
    {
      "id": "natural-125",
      "start": 527.496,
      "end": 531.75,
      "time": "08:47",
      "image": "assets/images/scene-125.webp",
      "sourceFullVersionImage": "scene-215.webp",
      "motion": "pan-left",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 73,
      "showHeading": false,
      "visualTopic": "豪華休旅車與老機車",
      "selectionReason": "旁白第 73 段：另一邊，擠在牆壁爬滿壁癌的40年老屋，騎著15年的機車，晚餐吃八十塊的雞腿飯。 → 豪華休旅車與老機車"
    },
    {
      "id": "natural-126",
      "start": 531.75,
      "end": 536.004,
      "time": "08:51",
      "image": "assets/images/scene-126.webp",
      "sourceFullVersionImage": "scene-206.webp",
      "motion": "diagonal",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 74,
      "showHeading": false,
      "visualTopic": "繁榮城市與疲憊勞工",
      "selectionReason": "旁白第 74 段：台積電處長一年的薪水，三千到五千萬。 → 繁榮城市與疲憊勞工"
    },
    {
      "id": "natural-127",
      "start": 536.004,
      "end": 540.258,
      "time": "08:56",
      "image": "assets/images/scene-127.webp",
      "sourceFullVersionImage": "scene-203.webp",
      "motion": "pan-right",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 75,
      "showHeading": false,
      "visualTopic": "同一條街相隔世紀",
      "selectionReason": "旁白第 75 段：那是超商店員，不吃不喝工作一百三十九年——從清朝光緒年間幹到現在，才賺得到的錢。 → 同一條街相隔世紀"
    },
    {
      "id": "natural-128",
      "start": 540.258,
      "end": 544.512,
      "time": "09:00",
      "image": "assets/images/scene-128.webp",
      "sourceFullVersionImage": "scene-208.webp",
      "motion": "pan-right",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 75,
      "showHeading": false,
      "visualTopic": "同一條街相隔世紀",
      "selectionReason": "旁白第 75 段：那是超商店員，不吃不喝工作一百三十九年——從清朝光緒年間幹到現在，才賺得到的錢。 → 同一條街相隔世紀"
    },
    {
      "id": "natural-129",
      "start": 544.512,
      "end": 548.766,
      "time": "09:04",
      "image": "assets/images/scene-129.webp",
      "sourceFullVersionImage": "scene-213.webp",
      "motion": "pan-right",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 75,
      "showHeading": false,
      "visualTopic": "同一條街相隔世紀",
      "selectionReason": "旁白第 75 段：那是超商店員，不吃不喝工作一百三十九年——從清朝光緒年間幹到現在，才賺得到的錢。 → 同一條街相隔世紀"
    },
    {
      "id": "natural-130",
      "start": 548.766,
      "end": 553.02,
      "time": "09:08",
      "image": "assets/images/scene-130.webp",
      "sourceFullVersionImage": "scene-202.webp",
      "motion": "push",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 76,
      "showHeading": false,
      "visualTopic": "兩個世界的斑馬線",
      "selectionReason": "旁白第 76 段：他們在同一個路口等紅燈，距離只有一條斑馬線，但階級差距，卻是一整個世紀。 → 兩個世界的斑馬線"
    },
    {
      "id": "natural-131",
      "start": 553.02,
      "end": 557.274,
      "time": "09:13",
      "image": "assets/images/scene-131.webp",
      "sourceFullVersionImage": "scene-207.webp",
      "motion": "push",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 76,
      "showHeading": false,
      "visualTopic": "兩個世界的斑馬線",
      "selectionReason": "旁白第 76 段：他們在同一個路口等紅燈，距離只有一條斑馬線，但階級差距，卻是一整個世紀。 → 兩個世界的斑馬線"
    },
    {
      "id": "natural-132",
      "start": 557.274,
      "end": 561.528,
      "time": "09:17",
      "image": "assets/images/scene-132.webp",
      "sourceFullVersionImage": "scene-204.webp",
      "motion": "pull",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 77,
      "showHeading": false,
      "visualTopic": "豪宅與壁癌老屋",
      "selectionReason": "旁白第 77 段：台灣的悲劇不在於它不富有，而是它太富有，卻把財富，堆在不到百分之三的人身上。 → 豪宅與壁癌老屋"
    },
    {
      "id": "natural-133",
      "start": 561.528,
      "end": 565.782,
      "time": "09:21",
      "image": "assets/images/scene-133.webp",
      "sourceFullVersionImage": "scene-209.webp",
      "motion": "pull",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 77,
      "showHeading": false,
      "visualTopic": "豪宅與壁癌老屋",
      "selectionReason": "旁白第 77 段：台灣的悲劇不在於它不富有，而是它太富有，卻把財富，堆在不到百分之三的人身上。 → 豪宅與壁癌老屋"
    },
    {
      "id": "natural-134",
      "start": 565.782,
      "end": 570.036,
      "time": "09:25",
      "image": "assets/images/scene-134.webp",
      "sourceFullVersionImage": "scene-211.webp",
      "motion": "diagonal",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 78,
      "showHeading": false,
      "visualTopic": "繁榮城市與疲憊勞工",
      "selectionReason": "旁白第 78 段：GDP往上走，薪資往底掉。 → 繁榮城市與疲憊勞工"
    },
    {
      "id": "natural-135",
      "start": 570.036,
      "end": 574.29,
      "time": "09:30",
      "image": "assets/images/scene-135.webp",
      "sourceFullVersionImage": "scene-216.webp",
      "motion": "diagonal",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 78,
      "showHeading": false,
      "visualTopic": "繁榮城市與疲憊勞工",
      "selectionReason": "旁白第 78 段：GDP往上走，薪資往底掉。 → 繁榮城市與疲憊勞工"
    },
    {
      "id": "natural-136",
      "start": 574.29,
      "end": 578.544,
      "time": "09:34",
      "image": "assets/images/scene-136.webp",
      "sourceFullVersionImage": "scene-218.webp",
      "motion": "pan-right",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 79,
      "showHeading": false,
      "visualTopic": "同一條街相隔世紀",
      "selectionReason": "旁白第 79 段：當全世界都在讚頌這座科技島時，你，卻連下個月的房租都付不出來。 → 同一條街相隔世紀"
    },
    {
      "id": "natural-137",
      "start": 578.544,
      "end": 582.798,
      "time": "09:38",
      "image": "assets/images/scene-137.webp",
      "sourceFullVersionImage": "scene-203.webp",
      "motion": "pan-right",
      "heading": "第一名：科技權貴與社畜的階級折疊",
      "captionId": 79,
      "showHeading": false,
      "visualTopic": "同一條街相隔世紀",
      "selectionReason": "旁白第 79 段：當全世界都在讚頌這座科技島時，你，卻連下個月的房租都付不出來。 → 同一條街相隔世紀"
    },
    {
      "id": "natural-138",
      "start": 582.798,
      "end": 587.052,
      "time": "09:42",
      "image": "assets/images/scene-138.webp",
      "sourceFullVersionImage": "scene-223.webp",
      "motion": "push",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 80,
      "showHeading": true,
      "visualTopic": "繁榮城市陰影",
      "selectionReason": "旁白第 80 段：最可怕的不是賺不到錢，而是二十歲的年輕人，已經放棄了對未來的所有想像。 → 繁榮城市陰影"
    },
    {
      "id": "natural-139",
      "start": 587.052,
      "end": 591.306,
      "time": "09:47",
      "image": "assets/images/scene-139.webp",
      "sourceFullVersionImage": "scene-228.webp",
      "motion": "push",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 80,
      "showHeading": false,
      "visualTopic": "繁榮城市陰影",
      "selectionReason": "旁白第 80 段：最可怕的不是賺不到錢，而是二十歲的年輕人，已經放棄了對未來的所有想像。 → 繁榮城市陰影"
    },
    {
      "id": "natural-140",
      "start": 591.306,
      "end": 595.56,
      "time": "09:51",
      "image": "assets/images/scene-140.webp",
      "sourceFullVersionImage": "scene-227.webp",
      "motion": "diagonal",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 81,
      "showHeading": false,
      "visualTopic": "聚光燈",
      "selectionReason": "旁白第 81 段：如果看完這些你感覺被刺痛了，那代表你還沒有麻木。 → 聚光燈"
    },
    {
      "id": "natural-141",
      "start": 595.56,
      "end": 599.814,
      "time": "09:55",
      "image": "assets/images/scene-141.webp",
      "sourceFullVersionImage": "scene-232.webp",
      "motion": "diagonal",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 81,
      "showHeading": false,
      "visualTopic": "聚光燈",
      "selectionReason": "旁白第 81 段：如果看完這些你感覺被刺痛了，那代表你還沒有麻木。 → 聚光燈"
    },
    {
      "id": "natural-142",
      "start": 599.814,
      "end": 604.068,
      "time": "09:59",
      "image": "assets/images/scene-142.webp",
      "sourceFullVersionImage": "scene-226.webp",
      "motion": "pan-left",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 82,
      "showHeading": false,
      "visualTopic": "沉默直視鏡頭",
      "selectionReason": "旁白第 82 段：留言告訴我們，這十個怪象中，你，正經歷著哪一個？ → 沉默直視鏡頭"
    },
    {
      "id": "natural-143",
      "start": 604.068,
      "end": 608.322,
      "time": "10:04",
      "image": "assets/images/scene-143.webp",
      "sourceFullVersionImage": "scene-224.webp",
      "motion": "pan-right",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 83,
      "showHeading": false,
      "visualTopic": "微弱希望",
      "selectionReason": "旁白第 83 段：【被遺忘的大多數】 我們，都是繁榮背後的真相。 → 微弱希望"
    },
    {
      "id": "natural-144",
      "start": 608.322,
      "end": 612.557,
      "time": "10:08",
      "image": "assets/images/scene-144.webp",
      "sourceFullVersionImage": "scene-225.webp",
      "motion": "pull",
      "heading": "結語：你，被刺痛了嗎？",
      "captionId": 83,
      "showHeading": false,
      "visualTopic": "面向遠方城市",
      "selectionReason": "旁白第 83 段：【被遺忘的大多數】 我們，都是繁榮背後的真相。 → 面向遠方城市"
    }
  ]
};
